### ISSUE TITLE
Disk Attach has some race conditions

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1073]
Following-up on @plotnick 's comment [here](https://github.com/oxidecomputer/omicron/pull/1068/files#r873063471), I think there may be some deeper issues with disk attaching / detaching.

# Background

The following steps attempt to roughly map out the disk attach process:

- 1\) [instance_attach_disk](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L535) - in `app/instance.rs` - is invoked.
- 2\) [instance_list_disks](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L558-L572) is invoked
- 3\) The number of attached disks is [compared against the maximum permitted for the instance](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L574-L579).
- 4\) The [disk state is checked](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L612-L648), only permitting attaching if it is in a valid state.
- 5\) The [instance state is checked](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L650-L678), only permitting attaching if it is in a valid state.
- 6a) **If the instance is running...**
- 6a-1) A request is sent through the [Sled Agent](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L657-L666) to update the disk state. This [attaches the disk to a running instance](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/disk.rs#L180-L192) first...
- 6a-2) ... then [updates the database](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/disk.rs#L196-L200).
- 6b) **If the instance is not running...**
- 6b-1) The [database is updated](https://github.com/oxidecomputer/omicron/blob/a179f03bfe17ec890478c6f482a19b1675217194/nexus/src/app/instance.rs#L674-L677) with the new runtime. 

# Issues

- Between (2) and (3), other disks may be concurrently attached, bypassing the check. This is a TOCTTOU.
- Between (4) and (6a-1), the disk state may be modified before the sled agent request is made. This could result in the sled agent attaching a disk that has been deleted or attached to a different instance.
- Between (5) and (6), the instance state may be modified. The instance has a "state_generation" value for [optimistic concurrency control](https://rfd.shared.oxide.computer/rfd/0192#_transactions_ctes_sagas_generation_numbers), but it is not being checked / modified here.

**Comment by smklein** [comment]
Here's what I've experimented with so far - using `cockroachdb`'s [movr](https://www.cockroachlabs.com/docs/stable/movr.html#:~:text=The%20movr%20dataset%20is%20built,on%20the%20movr%20GitHub%20repository.) dataset as an example.

I did this to make things reproducible - if you copy and paste the following sql to a `test.sql` file, you can invoke:

```bash
$ cockroach demo -f test.sql
```

To see how this CTE works.

My approach is basically the following:
1. Check for existence of both rows (by ID), to improve error reporting regardless of the update.
2. Check for existence of both rows (by conditions). This is equivalent to checking the "state" of the instance / disk.
3. Perform the updates *conditional* on both rows existing with the conditions we want. Ideally, they should both be updated or neither should be updated.
4. Collect the results and return them to the caller. If the update failed, identify whether or not the rows existed at all. If the update succeeds, return the rows we want.

```sql

/* Setup - if you EXPLAIN the `WITH` statement, you'll see no full table scans with these indices */
CREATE INDEX on public.users (id);                                                                                                                                                                                                          
CREATE INDEX on public.vehicles (id); 

WITH
  /* Check for the existence of the tables */
  vehicle_by_id as (
    SELECT public.vehicles.id
    FROM public.vehicles
    WHERE public.vehicles.id='bbbbbbbb-bbbb-4800-8000-00000000000b'
  ),
  owner_by_id as (
    SELECT public.users.id
    FROM public.users
    WHERE public.users.id='bd70a3d7-0a3d-4000-8000-000000000025'
  ),

  /* Check for the WHERE clauses we want to validate. */
  vehicle_info as (
    SELECT
      public.vehicles.id, public.vehicles.type, public.vehicles.status, public.vehicles.owner_id
    FROM public.vehicles
    WHERE (
      public.vehicles.id='bbbbbbbb-bbbb-4800-8000-00000000000b' AND
      public.vehicles.status='available'
    )
    FOR UPDATE
  ),
  owner_info as (
    SELECT *
    FROM public.users
    WHERE (
      public.users.id='bd70a3d7-0a3d-4000-8000-000000000025' AND
      public.users.city='amsterdam'
    )
    FOR UPDATE
  ),

  /* Conditionally update both tables */
  updated_owner as (
    UPDATE public.users
      SET credit_card = REVERSE(credit_card)
    WHERE (
      public.users.id='bd70a3d7-0a3d-4000-8000-000000000025' AND
      EXISTS(SELECT id from vehicle_info) AND
      EXISTS(SELECT id from owner_info)
    )
    RETURNING
      public.users.id,
      public.users.name,
      public.users.city,
      public.users.credit_card
  ),
  updated_vehicle as (
    UPDATE public.vehicles
      SET status = REVERSE(status)
    WHERE
      public.vehicles.id='bbbbbbbb-bbbb-4800-8000-00000000000b' AND
      EXISTS(SELECT id from vehicle_info) AND
      EXISTS(SELECT id from owner_info)
    RETURNING
      public.vehicles.id,
      public.vehicles.status
  ),

  /* Return both tables */
  result as (
    SELECT
      IF(EXISTS(SELECT id FROM vehicle_by_id), 1, 0) as vehicle_exists,
      IF(EXISTS(SELECT id FROM owner_by_id), 1, 0) as owner_exists,
      COALESCE((SELECT * FROM updated_owner), NULL) as updated_owner,
      COALESCE((SELECT * FROM updated_vehicle), NULL) as updated_vehicle
  )
SELECT * from result;
```

**Comment by smklein** [comment]
@bnaecker : I can definitely remove the `IF` - parsing the "does it exist" value as a `BOOL` works fine directly from `EXISTS`.

Also, I can definitely remove the `NULL` argument to `COALESCE` - it's redundant. But I've noticed:

```sql
    result as (                                                                                                                                                                                                                               
      SELECT                                                                                                                                                                                                                                  
        EXISTS(SELECT id FROM vehicle_by_id) as vehicle_exists,
        EXISTS(SELECT id FROM owner_by_id) as owner_exists,
        COALESCE((SELECT * FROM updated_owner)) as updated_owner,
        COALESCE((SELECT * FROM updated_vehicle)) as updated_vehicle
    )     
```

For valid data, produces:

```
  vehicle_exists | owner_exists |  updated_owner  | updated_vehicle
-----------------+--------------+-----------------+--------------------
   true          |  true        | (<USER DATA>)   | (<VEHICLE DATA>)
```

And for invalid data (e.g., user does not exist) produces:

```
  vehicle_exists | owner_exists |  updated_owner  | updated_vehicle
-----------------+--------------+-----------------+--------------------
   true          |  false       | NULL            | NULL
```

However, if I try the following:


```sql
    result as (                                                                                                                                                                                                                               
      SELECT                                                                                                                                                                                                                                  
        EXISTS(SELECT id FROM vehicle_by_id) as vehicle_exists,
        EXISTS(SELECT id FROM owner_by_id) as owner_exists,
        (SELECT * FROM updated_owner) as updated_owner,
        (SELECT * FROM updated_vehicle) as updated_vehicle
    )     
```

Then the query returns the following error:

```
ERROR: subquery must return only one column, found 5
SQLSTATE: 42601
```

**Comment by bnaecker** [comment]
Ah, right. This isn't super well-documented, but the return value of `COALESCE` appears to be a tuple in this circumstance. That means in the result that works, the column `updated_owner` is a tuple where each element is a column from the record.

That is, the entry for the `updated_owner` column of your result record is something like:

```sql
(id, city, type, ...)
```

That might be OK for you, since you could deserialize that tuple in Rust. But you might need (or want) to return a row with each element as a scalar. One way to do that is to name each column explicitly in the last part:

```sql
...,
updated_vehicle AS (...)
SELECT
    EXISTS(SELECT id FROM vehicle_by_id) AS vehicle_exists,
    EXISTS(SELECT id FROM owner_by_id) AS owner_exists,
    id FROM update_vehicle,
    city FROM updated_vehicle,
    type FROM updated_vehicle,
    ...

```

That's definitely more verbose, but I've found writing out the columns to be helpful when developing these complicated queries. There's also probably a way to use CRDB's "tuple unpacking" operation, which looks like `SELECT (tuple).*`, but I'm not sure how to stuff that into this query in a way that makes it any better.

Hope that helps, didn't mean to sidetrack the more critical parts of the query.

**Comment by bnaecker** [comment]
Actually, maybe a better idea is to use a `JOIN` here rather than another CTE:

```sql
updated_vehicle AS (....)
SELECT * FROM
    (SELECT EXISTS(SELECT id FROM vehicle_by_id) AS vehicle_exists),
    (SELECT EXISTS(SELECT id FROM owner_by_id) AS owner_exists),
    updated_owner,
    updated_vehicle
WHERE
    (updated_owner.id = updated_vehicle.owner_id)
```

You'll get rows like:

```sql
  vehicle_exists | owner_exists | id | city | name | address | credit_card | id | city | type | owner_id | creation_time | status | current_location | ext
-----------------+--------------+----+------+------+---------+-------------+----+------+------+----------+---------------+--------+------------------+------
(0 rows)
```
