### ISSUE TITLE
[nexus] Need API to update network interfaces

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#1153]
Add an HTTP entrypoint and attendant queries for updating a network interface. Parameters that can be changed are:

- name
- description
- if NIC is primary

The last one is a bit funny. I think we only want to support designating a new primary NIC, not designating a NIC as a secondary. Instances always have a primary, so we can't support the latter.

**Comment by rmustacc** [comment]
Note as we had additional support for multiple IPs or controlling v4/v6 I'd expect this to also go here.

**Comment by bnaecker** [comment]
Thanks Robert -- I had assumed, incorrectly it seems, that modifying IPs would mean adding a new NIC, not modifying an existing one. I'll keep that in mind, thanks!

**Comment by bnaecker** [comment]
@rmustacc I believe I misread this. You're specifically saying that _adding_ an IP to an interface should be supported, right? For example, we could support adding a V4 address to an existing NIC with only a V6 address. Or does this also include _changing_ a NIC's address from V6 to V4?

**Comment by bnaecker** [comment]
I must be missing something, since I see those as redundant, not independent axes. If the NIC has zero addresses from the V6 subnet of its VPC Subnet, then it seems the answer to the first question is, "no, it doesn't use the V6 part." If it has one or more, then the answer is "yes".

Is there a practical difference between having a version of the protocol "available" to a NIC and it actually having an address from that version?

**Comment by bnaecker** [comment]
Robert and I spoke offline about this. Here's the summary.

The high-level point is that we don't want to preclude future work, by over-constraining the API now. It's true that in some sense the two "axes" we're talking about here are related, not totally independent. But we'd like to allow an API in the future that lets operators control the NICs in two ways: whether they're constrained to IPv4 or IPv6, and how many addresses they have of each of those. Those can be separate knobs in the API, even if they're related concepts. We just want to make sure that what we build now doesn't make that impossible in the future.

An additional point that came up was that there are likely to be additional parameters or flags that we'd like to support on the level of the entire NIC. One example is IP spoofing, which could be a boolean flag indicating if that's supported / allowed.

**Comment by bnaecker** [comment]
Completed in #1186
