### ISSUE TITLE
Should policy response body have resource ID and type on it?

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#1165]
I'm starting to work with the GET and PUT org and project policy endpoints in the console and found it surprising that the policy response body has no reference to the resource the policy is for. I assume this was to keep the `Policy` type simple by not having it know about the resource:

https://github.com/oxidecomputer/omicron/blob/4c933a1119afb8a8ec27c0a88286c80794e1bbe9/nexus/src/external_api/shared.rs#L32-L44

The simplest thing we could do is add a `resource_id` field, though it would be a bit weird if it didn't also indicate the resource type. So that could either be `resource_id: "abc"` and `resource_type: "project"` or we could combine that into one thing: `project_id`. On one hand `project_id` is neater. On the other hand, if a client has a policy and wants to know what kind of resource it is for, `policy.resource_type === "project"` makes a lot more sense than "is `project_id` present?" or some horrible `/^(.+)_id$/` situation. On the _other_ other hand, I don't know why a client would have a policy on hand but not know what kind of resource it came from. You just made the request, buddy.

So I guess the change I'm suggesting is this (sorry for the TS syntax, it's the most concise way to put it):

```diff
 type IdentityType = 'silo_user'

 type ProjectRoles = 'admin' | 'collaborator' | 'viewer'

 type ProjectRolesRoleAssignment = {
   identity_id: string
   identity_type: IdentityType
   role_name: ProjectRoles
 }
 
 type ProjectRolesPolicy = {
+  project_id: string
   role_assignments: ProjectRolesRoleAssignment[]
 }

 type OrganizationRolesPolicy = {
+  organization_id: string
   role_assignments: OrganizationRolesRoleAssignment[]
 }

// etc
```

cc @davepacheco @plotnick

**Comment by davepacheco** [comment]
I think I left it out because it seemed weird to include the type and id when you just made the request on a specific resource.  I don't object to leaving it in though.  I like `resource_id` and `resource_type` (and it seems a lot easier to implement).

**Comment by david-crespo** [comment]
It's true, we don't have `resource_type: 'project'` on the response when you fetch a project.

I would say this is pretty low priority for now. Originally what prompted this is that I wanted to store policy response JSON in my mock API DB basically as-is, which requires resource type and ID because you need to distinguish between org policies and project policies. But then I realized if I have to mess with the object anyway, I might as well imitate the API's actual data model, i.e., each row is a `(resource type, resource id, actor type, actor id)` tuple and then the endpoint aggregates those into a policy object ([source here](https://github.com/oxidecomputer/console/blob/99d417f6b23a86eb5646e417a75b2db103ba7b9e/libs/api-mocks/msw/handlers.ts#L211-L223)). So, bottom line is I don't need the above. In fact, I think I'll close the issue because I don't see a practical problem this solves.
