### ISSUE TITLE
public docs not showing required parameters

### ISSUE THREAD

**Issue by ryaeng** [oxidecomputer/omicron#1203]
The public docs listed below are not showing the correct required parameters. After further investigation, I can see that when I generate the docs locally they appear to be correct. 

How can I go about updating the public facing docs to reflect the changes in the api hosted at docs.oxide.computer?

Create a new organization has no parameters listed when it is required that the user provide name and description.
Create a new project has description and name listed as optional.
Create a new subnet has description, ipv4_block, and name listed as optional.
Create a network interface for an instance has vpc_name, subnet_name, name, and description listed as optional.

https://docs.oxide.computer/api/create-a-new-organization
https://docs.oxide.computer/api/create-a-new-project
https://docs.oxide.computer/api/create-a-subnet-in-a-vpc
https://docs.oxide.computer/api/create-a-network-interface-for-an-instance

**Comment by david-crespo** [comment]
You are correct, the site is out of date. We are working on it.
