### ISSUE TITLE
use main test log for oximeter log in test suite

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#1225]
When we start Nexus and the Sled Agent in the test suite, we use the log from the LogContext that's created for the test itself.  This way, the test log is a unified log with all entries from the test framework, the test itself, Nexus, and the Sled Agent.  But when we start Oximeter, it creates its own log from the config it's passed.  As a result, we don't have the Oximeter log entries in the test log.  It'd be good to get these in there -- it'd have made #1224 a lot easier to debug.

**Comment by bnaecker** [comment]
`oximeter` is pretty chatty at the debug and trace levels. I'll handle this now, but we may need quiet down `oximeter`.

**Comment by bnaecker** [comment]
Closed by #1228
