### ISSUE TITLE
Create an internal instance script

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/omicron#1227]
A script for internal demo use to facilitate population of images.

As part of the regular weekly demos, the "demo'er" often desires to create and boot an instance.
This script should enable populating the rack with some default images that can be booted.

**Comment by leftwo** [comment]
@smklein   Where would we put this script?  In `tools` directory?

**Comment by smklein** [comment]
That seems like a reasonable spot to me ; we could add a subdirectory within there for `populate`-based scripts.

I might add one for pre-populating some projects, for convenience, based on https://github.com/oxidecomputer/remote-access-preview/issues/3

**Comment by bnaecker** [comment]
@leftwo @smklein Seems like this is completed by https://github.com/oxidecomputer/omicron/pull/1281. Is that right?
