### ISSUE TITLE
Endpoint to list silo users

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#1235]
The existing [`/users`](https://github.com/oxidecomputer/omicron/blob/846dbfd7867619a1c2a29a5527040d4595946890/nexus/src/external_api/http_entrypoints.rs#L3111-L3117) endpoint lists built-in system users. I've been using it to test my work on role assignment in the console, but I will need IdP users for it to really work.

Because we know the silo from the authenticated user, I don't think we need the silo in the path. That makes me wonder if we should use `/users` for silo users and rename the system users endpoint (`/system_users` etc).

**Comment by davepacheco** [comment]
Yeah, I do think it makes sense to have `/users` be for Silo users and something else for the built-in users.
