### ISSUE TITLE
Return a real display name in the user response

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#1308]
`external_id` is a temporary solution for display names. It is not expected to always be human-readable — it can be whatever the IdP wants it to be. See https://github.com/oxidecomputer/omicron/pull/1297.

https://github.com/oxidecomputer/omicron/blob/df3133f03071b88cae0cab6be8a370d6a4d5350b/nexus/src/external_api/views.rs#L428-L436

**Comment by zephraph** [comment]
I noticed this doesn't flow through to `/session/me`. Should it?

**Comment by davepacheco** [comment]
Yeah, agreed on dropping `SessionUser` as a separate type.  We should have fetched the user when they authenticated so we should just keep that information in the Actor.
