### ISSUE TITLE
Implement Floating IPs

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#1334]
See https://github.com/oxidecomputer/omicron/issues/1333 for some general background on external IPs for instances. Floating IPs are the second form of IP addresses that allow inbound connectivity to guests. In contrast to Ephemeral IPs, which only live as long as instances, Floating IPs are API resources in their own right. They can be moved between objects, and are not deleted when the instance they're attached to is stopped. Similar to Ephemeral IPs, they allow inbound and outbound connectivity, and reserve the whole port range for the guest. Also, to Ephemeral IPs, Floating IPs can reference a specific IP Pool at creation time.

This work tracks adding the database representation and HTTP API for Floating IPs, and assigning them to guests for instance NAT when requested.

NOTE: None of this takes into account the current workaround in OPTE to allow inbound connections via the external IPs meant for source NAT. That will go away, hopefully very soon, once boundary services can be stood up to perform the decapsulation of guest traffic from OPTE.

**Comment by bnaecker** [comment]
Closed by #1458

**Comment by bnaecker** [comment]
Woops, closed the wrong issue.

**Comment by FelixMcFelix** [comment]
I'm currently working on the bits to handle this in [opte#420](https://github.com/oxidecomputer/opte/pull/420), after which I'm happy to tackle the API/DB side.
