### ISSUE TITLE
Automate docker image dependencies

### ISSUE THREAD

**Issue by plotnick** [oxidecomputer/omicron#1387]
As originally discussed in #1211 and worked around in #1384, the current docker image build process requires manually adding new dependencies. It should get them from running `tools/install_prerequisites.sh` or some other mechanism (maybe a text file containing the names of dependencies?) so that we don't end up with silently broken images in the future.

**Comment by david-crespo** [comment]
We do run the prereqs script — the PR description on #1211 saying we don't do that was true when I initially posted it, then I fixed it in the PR and forgot to update the description.

https://github.com/oxidecomputer/omicron/blob/d1a99af3e3dca1b42a39e2f7b5f5904b0565b574/Dockerfile#L23

But it sounds like it still wasn't working. Maybe we just need to add more things to the script.

**Comment by plotnick** [comment]
Hmmmmm, very interesting. I will do some further investigation, but it's no longer blocking CLI work since #1384 landed.
