### ISSUE TITLE
Github action failure: Deployment failed due to changing log size

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1416]
From https://github.com/oxidecomputer/omicron/pull/1406 , I noticed a failure in the "deploy" github action.

The PR, I suspect, is unrelated to the failure.

```
control: job dependencies complete; ready to run (waiting for 28 m 10 s)
control: job assigned to worker 01G7VZXZ98NF1GWMTNY2BRPWND (queued for 30 m 42 s)
...
worker: downloading input: /input/package/work/package.tar.gz
worker: downloaded input: /input/package/work/package.tar.gz
...
task: starting task 0: "setup"
task: process exited: duration 4060 ms, exit code 0
...
task: starting task 1: "authentication"
task: process exited: duration 10 ms, exit code 0
...
task: starting task 2: "build"
...
| <html lang="en">
|   <head>
|     <meta charset="utf-8" />
|     <title>Oxide Console</title>
| 
|     <meta name="viewport" content="width=device-width, initial-scale=1" />
| 
|     <link rel="icon" type="image/svg+xml" href="/assets/favicon.f85aa1d6.svg" />
|     <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCA [...]
|     <script type="module" crossorigin src="/assets/index.daa95ebe.js"></script>
|     <link rel="modulepreload" href="/assets/vendor.26cbd01d.js">
|     <link rel="stylesheet" href="/assets/index.92cf2cbf.css">
|   </head>
|   <body>
|     <div id="root"></div>
| 
|   </body>
| </html>
| ok; nexus became available!
task: process exited: duration 75422 ms, exit code 0
worker: found 2 output files
worker: uploading: /var/svc/log/system-illumos-sled-agent:default.log (96172 bytes)
worker: uploaded: /var/svc/log/system-illumos-sled-agent:default.log
worker: uploading: /zone/oxz_nexus/root/var/svc/log/system-illumos-nexus:default.log (55299 bytes)
worker: upload error: "file \"/zone/oxz_nexus/root/var/svc/log/system-illumos-nexus:default.log\" changed size mid upload: 55299 -> 56419"
```

This implies that Nexus continues emitting log messages after initial setup - this seems like expected behavior; I think we would want the worker to be capable of uploading a log file that may continue having entries appended.

**Comment by iliana** [comment]
I noticed that in another task and retried it. I'm not sure if Buildomat has a flag to ignore this for some files?

Or we can run `omicron-package uninstall` before ending the task.

**Comment by jclulow** [comment]
This is a buildomat bug.  There should be a facility to request files that might still be modified while we're uploading, like log files for things.  Regrettably TOML is not very ergonomic once you get beyond "array of strings", which is why `output_rules` is the way it is today -- but I've been looking at moving to KDL in the near future, which will make it easier to add properties to the rule.

In the meantime I will add an `output_log_rules` or something, which will be the same as `output_rules` but it will be relaxed about concurrent modification, and get back to you here.

**Comment by jclulow** [comment]
I have put #1433 back, so this should hopefully stop happening and I'm going to close this one.  Please reopen, or file a new issue, if you see it or something similar again!
