### ISSUE TITLE
CI filesystem failure generating rustdocs

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#1481]
I had a [PR fail](https://github.com/oxidecomputer/omicron/runs/7471094535?check_suite_focus=true) with a filesystem error I haven't seen before:

```
error: couldn't generate documentation: No such file or directory (os error 2)
  |
  = note: failed to create or modify "/home/runner/work/omicron/omicron/target/doc/omicron_common/api/external/struct.L4PortRange.html"
warning: `omicron-common` (lib doc) generated 1 warning
error: could not document `omicron-common`
```

Retrying succeeded. This doesn't seem like a "disk full" issue (a la #1380), so I figured I'd note it in a new issue.

**Comment by davepacheco** [comment]
The above link is dead and there's very little information in the output to go on.  Closing because it seems forever unactionable, but feel free to reopen if we see it again or if somebody has suggestions for proceeding given what information we have.
