### ISSUE TITLE
[sled agent] Extract a Service Bundle from zones which are being destroyed

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1598]
When `RunningZone` objects are dropped, for whatever reason, the underlying zone is halted and removed:

https://github.com/oxidecomputer/omicron/blob/50c6ce1529a0fe075402efba813ee785259d32a2/sled-agent/src/illumos/running_zone.rs#L310-L321

This if often the case when:
- We attempt to boot a zone, but it fails to start
- A zone instance is destroyed

This helps prevent leakage of resources, but limits inspection of "why the zone died, and what it was up to".

It would be useful to extract log information from zones into a "service bundle" before we destroy the underlying zone.

**Comment by davepacheco** [comment]
This would be great.  Things I'd consider including:

- ptree output for the whole zone
- pfiles, pstack, and core files for any of the key processes (e.g., in a CockroachDB zone, this would be just "cockroach" itself)
- SMF logs, other system logs, and any application-level logs
- uptime
- "last" output, "who" output
- `svcs -p` output for the whole zone (includes service states and timestamp of most recent state transitions)

Another tool that might be useful would be to preserve a limited number of such zones for interactive investigation by support.

**Comment by leftwo** [comment]
As part of this, or maybe this can be another issue, gather the versions of software for the parts involved also.  Like Omicron, Sled-agent, propolis, crucible-agent/downstairs, Helios... maybe others too that I can't think of.
