### ISSUE TITLE
thing-flinger deploy install causes ddm routing to stop working with falcon-omicron topology

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#1613]
When `thing-flinger deploy install` is run twice, prefixes stop getting delivered: 

```
[2022-08-17T07:06:46.352101097Z]  INFO: SledAgent/RSS/3459 on om1: Received prefixes from ddmd (prefixes={})
[2022-08-17T07:06:46.352378081Z]  INFO: SledAgent/RSS/3459 on om1: Waiting for 2 peers (currently have 1) (will retry after 261.961667ms)
```

Prefixes are properly transferred on first launch. It would be nice to be able to re-install omicron without having to re-launch VMs and install pre-requisites. This was the prior behavior before we actually had useful network functionality in Omicron like prefix routing via DDM :)

**Comment by andrewjstone** [comment]
cc @rcgoodfellow

**Comment by rcgoodfellow** [comment]
Can you describe a bit more about the lifetime of the `ddmd` instances? Does `thing-flinger deploy install` tear down and restart the `ddmd` instances or do they remain running? I have [fixed a bug](https://github.com/oxidecomputer/maghemite/commit/e110b151aa314a6f93a65e408f2a03681871ba4c) recently that can prevent expected peering from taking place - but I'm no totally sure if that's in play here.

**Comment by andrewjstone** [comment]
> Can you describe a bit more about the lifetime of the `ddmd` instances? Does `thing-flinger deploy install` tear down and restart the `ddmd` instances or do they remain running? I have [fixed a bug](https://github.com/oxidecomputer/maghemite/commit/e110b151aa314a6f93a65e408f2a03681871ba4c) recently that can prevent expected peering from taking place - but I'm no totally sure if that's in play here.

`deploy install` doesn't deal with ddmd explicitly. It does [restart the sled-agent service](https://github.com/oxidecomputer/omicron/blob/main/deploy/src/bin/thing-flinger.rs#L704-L706). Should it also restart ddmd?

**Comment by rcgoodfellow** [comment]
Ok. So is it accurate to say the following

- `t0`: The topology starts up.
- `t1`: `deploy install` runs.
- `t2`: you see 2 ddm peers
- `t3`: `deploy install` runs again (which does what exactly? does it clobber the underlying network `ddmd` is peering over?)
- `t4`: you only see 1 of 2 ddm peers

**Comment by andrewjstone** [comment]
> Ok. So is it accurate to say the following
> 
> * `t0`: The topology starts up.
> * `t1`: `deploy install` runs.
> * `t2`: you see 2 ddm peers
> * `t3`: `deploy install` runs again (which does what exactly? does it clobber the underlying network `ddmd` is peering over?)
> * `t4`: you only see 1 of 2 ddm peers

Yes, that is accurate. All that `deploy install` does that's relevant is do an `omicron package install` which just puts files in the right place and then restarts `sled-agent`. https://github.com/oxidecomputer/omicron/blob/main/deploy/src/bin/thing-flinger.rs#L528-L581

I only see the following relevant lines in the log:

```
{"msg":"Starting mg-ddm service","v":0,"name":"SledAgent","level":30,"time":"2022-08-17T19:35:36.408677066Z","hostname":"om1","pid":16356}
{"msg":"Importing mg-ddm service","v":0,"name":"SledAgent","level":30,"time":"2022-08-17T19:35:36.409845025Z","hostname":"om1","pid":16356,"path":"/opt/oxide/mg-ddm/pkg/ddm/manifest.xml"}
{"msg":"Setting mg-ddm interface","v":0,"name":"SledAgent","level":30,"time":"2022-08-17T19:35:36.560431565Z","hostname":"om1","pid":16356,"interface":"net0/linklocal"}
{"msg":"Enabling mg-ddm service","v":0,"name":"SledAgent","level":30,"time":"2022-08-17T19:35:36.566545161Z","hostname":"om1","pid":16356}
```

**Comment by andrewjstone** [comment]
Ha, it turns out that doing a `deploy uninstall` before `deploy install` actually fixes the issue. Thanks to @jgallagher for the tip!

**Comment by andrewjstone** [comment]
Going to just close this, given the fact that deploy uninstall solves it and it's not a general problem.
