### ISSUE TITLE
Snapshot creation should fail if there isn't room in the dataset

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/omicron#1642]
Currently, we do not block snapshots from taking place, and therefore the amount of zpool space that can be consumed by a crucible dataset is unbounded.

During the snapshot creation saga, Nexus should query if there's enough room in the dataset for another copy of the virtual disk, and fail to create the snapshot if there isn't.

**Comment by davepacheco** [comment]
Should it also allocate (or reserve) the space to avoid a time-of-check-to-time-of-use race?

**Comment by jmpesp** [comment]
Definitely :)
