### ISSUE TITLE
Gather and send instance information on migration

### ISSUE THREAD

**Issue by plotnick** [oxidecomputer/omicron#1783]
PR #1636 sends applicable firewall rules to a sled-agent on instance creation (see also issue #1017) and rule modifications, but not on instance migration. There are several other important pieces of information not currently migrated with instances; see the `TODO`s in `instance_migrate::sim_instance_migrate`. We should maybe have separate issues for each of them, but we'll list them here for now so they're all tracked:
- [ ] NICs
- [ ] Firewall rules
- [ ] Disks
- [ ] Cloud-init bytes

**Comment by gjcolombo** [comment]
The live migration saga rework in #2892 (and its sibling PRs) addressed this: instance start and instance migrate now use a common Nexus function (`instance_ensure_registered`) to send configuration to sleds (in this case the migration destination sled).
