### ISSUE TITLE
sled-agent should support multi-service zones

### ISSUE THREAD

**Issue by Nieuwejaar** [oxidecomputer/omicron#1807]
When running on a real scrimlet, we will need the ability to run `dendrite`, `tfportd`, and `mgs` in a single zone.

`tfportd` provides connectivity from the scrimlet to ports on the sidecar switch via `dladm`-added links, which carry traffic via the `/dev/tfport` multiplexer.  `dendrite` and `mgs` need access to a shared link corresponding to the aux/cpu/SP port.

**Comment by smklein** [comment]
This can be closed, right?

**Comment by Nieuwejaar** [comment]
Yes.  Will do.
