### ISSUE TITLE
Firewall rules need some IPv6 love

### ISSUE THREAD

**Issue by plotnick** [oxidecomputer/omicron#1829]
Firewall rules can currently accept IPv6 addresses as targets and host filters, but until [OPTE#282](https://github.com/oxidecomputer/opte/issues/282) is resolved, they won't have any effect. When OPTE is ready for them, we will need tests and to fix [the remaining IPv6 firewall rule `todo!`](https://github.com/oxidecomputer/omicron/blob/5c79f74846e02df1ef9c45fa7693c5d3db9a6375/sled-agent/src/opte/illumos/firewall_rules.rs#L73).

**Comment by bnaecker** [comment]
This has been completed, as of https://github.com/oxidecomputer/omicron/commit/a76ece401ac07c7aaeca06cf9de3e0194f949d76.
