### ISSUE TITLE
Wicket: Create an omicron-package pkg (and automatically launch it with switch zone)

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#1871]
This should be an intermediate package to be consumed along with mgs and dendrite.

**Comment by smklein** [comment]
Related to https://github.com/oxidecomputer/minimum-upgradable-product/issues/32

**Comment by jclulow** [comment]
As part of this we may need to sort out user account handling in the brand and figure out how we're going to configure SSH?

**Comment by andrewjstone** [comment]
Done. Leaving Josh's questions as part of ssh related issues.

**Comment by jclulow** [comment]
> Done. Leaving Josh's questions as part of ssh related issues.

I think I put more detailed followup stuff in another issue later anyway.  Thanks!

**Comment by andrewjstone** [comment]
> > Done. Leaving Josh's questions as part of ssh related issues.
> 
> I think I put more detailed followup stuff in another issue later anyway. Thanks!

You did. I just couldn't remember the issue and was lazy. Cheers!
