### ISSUE TITLE
Use `integration` branch of illumos instead of `xde`

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#1894]
Move the `install_opte.sh` script to use the [`integration` branch](https://github.com/oxidecomputer/illumos-gate/tree/integration) of illumos.

**Comment by jclulow** [comment]
Have you confirmed that it builds and boots and works on PC systems?

**Comment by bnaecker** [comment]
I have not. I think the real thrust was to bring in the changes required for Dendrite to run correctly.

**Comment by jclulow** [comment]
Alright.  I've rigged up some basic automation for building OS packages from the `integration` branch, such that they will get pushed up into the repository at https://pkg.oxide.computer/helios-netdev.  This should kick off for each new commit and get packages up there within an hour or so.

I also rigged up some other basic automation that should pull new latest builds of the `/driver/network/opte` package from the CI builds for `oxidecomputer/opte.git` and put them in that repository as well.

Both the OS packages and OPTE will be under the `helios-netdev` publisher there.

You should be able to do something like:

```
# pkg set-publisher --search-first -O https://pkg.oxide.computer/helios-netdev helios-netdev
# pkg set-publisher --non-sticky helios-dev
# pkg install -v /driver/network/opte
# pkg update -v
```

... to configure a system to prefer that publisher.  When new `opte` packages or `integration` OS bits become available folks should just be able to `pkg update -v` etc to get them.

Right now that repository has packages from the `xde` branch, but `integration` bits should show up in the next hour.  I'll mention when they're there.

**Comment by jclulow** [comment]
Alright `integration` bits are up there now:

```
           Name: consolidation/osnet/osnet-incorporation
        Summary: OS/Net consolidation incorporation
      Publisher: helios-netdev
        Version: 0.5.11
  Build Release: 5.11
         Branch: 1.0.999999
 Packaging Date: Mon Oct 31 23:51:07 2022
           Size: 0.00 B
Compressed Size: 0.00 B
           FMRI: pkg://helios-netdev/consolidation/osnet/osnet-incorporation@0.5.11,5.11-1.0.999999:20221031T235107Z
```

https://pkg.oxide.computer/helios-netdev/info/0/consolidation%2Fosnet%2Fosnet-incorporation%400.5.11%2C5.11-1.0.999999%3A20221031T235107Z

We should be able to modify `install_opte.sh` to configure this alternative publisher rather than need to download and use the p5p archives.

**Comment by bnaecker** [comment]
That's great, thanks for taking care of that Josh. I'll update the scripts / tools today.

**Comment by bnaecker** [comment]
See #1907

**Comment by bnaecker** [comment]
This is outdated, we've been using helios-netdev successfully and mainline helios for a while now.
