### ISSUE TITLE
wicketd/wicket integration for inventory

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#1899]
`wicketd` is serving basic inventory including power states and Rot/Sp/Phase1-host versions for use by wicket. This will replace the fake information currently present in wicket.

**Comment by andrewjstone** [comment]
The first PR is out: https://github.com/oxidecomputer/omicron/pull/1935

**Comment by candidobrau** [comment]
This is the thing waiting on `progenitor`

**Comment by andrewjstone** [comment]
More of this is done in https://github.com/oxidecomputer/omicron/pull/1953

**Comment by andrewjstone** [comment]
Once https://github.com/oxidecomputer/omicron/pull/1953 is merged in we can close this. There are a few other issues I will open individually.

**Comment by andrewjstone** [comment]
Done.
