### ISSUE TITLE
Unpaginate MGS's sp_list endpoint

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#1913]
As @andrewjstone has started integration of MGS and wicket, the pagination of this endpoint seems like overkill. We should change it in the following ways:

1. Remove the pagination parameters and the client-provided timeout
2. Remove the background task that does bulk SP state request collection (probably remove `bulk_sp_state_requests` and its associated machinery entirely)
3. Send state requests to all SPs in parallel
4. Give up on an SP after N UDP retries (probably N=2 or 3?)
5. Return a full-length vec of status every time, indicating which SPs did not respond in step 3-4

@ahl if this sounds horrible please chime in

**Comment by andrewjstone** [comment]
Implemented in #1921
