### ISSUE TITLE
sled agent must ensure a dataset for zpools (currently `rpool/zone`) exists

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1934]
This issue has been broadened in scope a bit.

OLD:

Currently, [sled agent] assumes the `rpool/zone` dataset exists - it should *ensure* it exists. This won't necessarily be present on all machines.

NEW:

Sled Agent must be responsible for management of U.2s, M.2s, and the partitions, zpools, and datasets within.

This issue tracks Sled Agent performing the following tasks:
- [x] Identify new U.2 / M.2 devices from `libdevinfo`
- [x] Query the devices to understand if they have already been formatted with a zpool
  - [x] If "no", `zpool create` a new zpool on the device
- [x] Compare the list of "imported zpools" with "the list of devices from `libdevinfo`. Import any new devices
- [x] Ensure (at least one) dataset for zones exists (Completed by https://github.com/oxidecomputer/omicron/commit/789fac409ab5de0c75e64b71ba82eb47c75a5808)

**Comment by smklein** [comment]
Related to this: `omicron-package` uses the utility `get_all_omicron_datasets` to delete all pre-installed zones when doing an install. If `rpool/zone` does not exist, this iteration currently fails - we should handle this case more gracefully (It's probably fair to assume these datasets do not exist if `ZONE_ZFS_DATASET` does not exist).

**Comment by leftwo** [comment]
The actual error I see on an install of a "fresh" system (meaning omicron was not installed yet, a fresh boot on a ramdisk).

```
Running install
Nov 16 23:20:58.008 DEBG target: Target({"switch_variant": "stub"})
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/internal_dns.tar.gz, src: out/internal-dns.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/propolis-server.tar.gz, src: out/propolis-server.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/mg-ddm.tar, src: out/maghemite.tar
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/crucible.tar.gz, src: out/crucible.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/switch.tar.gz, src: out/switch-stub.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/cockroachdb.tar.gz, src: out/cockroachdb.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/clickhouse.tar.gz, src: out/clickhouse.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/nexus.tar.gz, src: out/omicron-nexus.tar.gz
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/sled-agent.tar, src: out/omicron-sled-agent.tar
Nov 16 23:20:58.014 INFO Installing service, dst: /opt/oxide/oximeter.tar.gz, src: out/oximeter-collector.tar.gz
Nov 16 23:20:59.372 INFO Removing all Omicron zones
Nov 16 23:20:59.390 INFO Uninstalling all packages
Nov 16 23:20:59.483 INFO Removing networking resources
Nov 16 23:20:59.531 WARN Deleting Omicron underlay VNIC, vnic_name: underlay0
Nov 16 23:20:59.560 WARN Deleting Omicron etherstub, stub_name: stub0
Nov 16 23:20:59.575 INFO Uninstalling Omicron configuration
Nov 16 23:20:59.575 INFO Removing datasets
Error: Could not list datasets within zpool rpool/zone: Command [list -d 1 -rHpo name rpool/zone] executed and failed with status: exit status: 1  stdout:   stderr: cannot open 'rpool/zone': dataset does not exist


Caused by:
    Command [list -d 1 -rHpo name rpool/zone] executed and failed with status: exit status: 1  stdout:   stderr: cannot open 'rpool/zone': dataset does not exist
```

So, I believe the problem is when the new install tries to look for and delete old datasets, it's not handling the case where there are none.

**Comment by leftwo** [comment]
A workaround:
manually create the dataset:
```
zfs create rpool/zone
```
Re-run the install, it will install but fail to start sled agent.
When it has started and is failing, then destroy the dataset:
```
zfs destroy rpool/zone
```
sled-agent should be retrying and will pickup where it left off and the install will work.

**Comment by smklein** [comment]
Marking this as done, we *are* auto-formatting these dataset on boot. We should *use* the ones on the U.2s more than the `rpool/zone` one in the ramdisk, but that'st racked by other bugs.

**Comment by bnaecker** [comment]
@smklein I noticed this issue is still marked as the TODO for [this block of code](https://github.com/oxidecomputer/omicron/blob/6642158b5786e39ded08fb01c0cd748ebd128409/sled-agent/src/bootstrap/agent.rs#L347-L361). Since this is now closed, is https://github.com/oxidecomputer/omicron/issues/2888 a better issue to link there?

**Comment by smklein** [comment]
Yeah, we can update the reference. Regarding that block of code specifically:

- You can look where `ZONE_ZFS_RAMDISK_DATASET_MOUNTPOINT` is used in the codebase -- it's used as the root of zones ("zonepath"), which *should* be disposable across reboots.
- This is "easy to manage", because they're always in RAM, and they disappear between reboots, as they should. This mechanism also unfortunately uses more RAM than it should.

- Fixing this is related to the "Sled agent should allocate zonepaths from U.2s" point under #2888.
- Fixing this not only requires provisioning zonepaths from U.2s, but also *picking* a U.2 and accounting for the space used.

**Comment by bnaecker** [comment]
Thanks that all makes sense. I'm not tackling those latter points right now, but I'll update the issue while I'm touching nearby code. Thanks!
