### ISSUE TITLE
SQL query logging

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#194]
This may be more of a "how do I do this?" than a request for work to be done, but when I'm running the tests and debugging queries, I have to do a lot of manual intervention with `println!`s to see the actual SQL being executed. Cockroach has a [cluster-wide logging](https://www.cockroachlabs.com/docs/v20.2/query-behavior-troubleshooting#cluster-wide-execution-logs) setting, but I couldn't get it to work. (I did try turning of [stdio redirection](https://github.com/oxidecomputer/omicron/blob/7ef30a8e27b4def4e279d97f90c53612fd03d180/omicron-common/src/dev/db.rs#L201) too.) This will also be useful while we're [feeling out](https://github.com/oxidecomputer/omicron/pull/192) the SQL that Diesel generates.

**Comment by bnaecker** [comment]
I happened to be going through some older issues, and think this can be closed. All the queries executed by a running Nexus can be see with `./tools/dtrace/trace-db-queries.d -p $(pgrep nexus)`. This was added in #488.
