### ISSUE TITLE
Flaky issue with helios deploy CI job during "ensuring datasets are ready"

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#1991]
I ran into this issue yesterday with the helios deploy job on CI:

https://buildomat.eng.oxide.computer/wg/0/details/01GJZX8864CXJBMQWWE2WYQMGS/rAHG6cmThT21CWqMwk99DpsKv74Vjb9oH9IGloNf3iZoqUb2/01GJZX8KJ04C0Y89G2AQ10YV3E#S349

The most pertinent lines are:

```
349 | 2022-11-28T20:29:12.948Z | creating IP pool...
350 | 2022-11-28T20:29:12.979Z | ensuring datasets are ready...
351 | 2022-11-28T20:31:13.903Z | Error: timed out after 120.654670292s
```

Rerunning the job on buildomat succeeded, which suggests a flaky issue with setup.

**Comment by smklein** [comment]
FYI @iliana  - this line comes from https://github.com/oxidecomputer/omicron/blob/daf316d50ada51fe54a9c723074bc4d80f13104b/end-to-end-tests/src/bin/bootstrap.rs#L53 . No idea what's causing the timeout, but I'd be curious about more info from the test runner

**Comment by iliana** [comment]
Three datasets need to be in place before disks can be created; each dataset is created on a separate zpool. The [nexus log for the job](https://buildomat.eng.oxide.computer/wg/0/artefact/01GJZX8864CXJBMQWWE2WYQMGS/rAHG6cmThT21CWqMwk99DpsKv74Vjb9oH9IGloNf3iZoqUb2/01GJZX8KJ04C0Y89G2AQ10YV3E/01GJZZ3Y52R2BYZXCPCB3QK6P7/system-illumos-nexus:default.log?format=x-bunyan) (search for `/zpools/`) indicates only two zpools were created before the 120-second timeout.

Possibilities:
- [Exponential backoff for adding zpools and datasets](https://buildomat.eng.oxide.computer/wg/0/artefact/01GJZX8864CXJBMQWWE2WYQMGS/rAHG6cmThT21CWqMwk99DpsKv74Vjb9oH9IGloNf3iZoqUb2/01GJZX8KJ04C0Y89G2AQ10YV3E/01GJZZ3Y1970VBCH098SWMA3BG/system-illumos-sled-agent:default.log?format=x-bunyan#L359) should be changed to something less exponential.
- There's been a regression in how long it takes Nexus to come up.
- [Clulow's Lament](https://twitter.com/jmclulow/status/879362528911872000).

**Comment by jclulow** [comment]
I suspect it would be good if we did not use exponential backoff by default in almost any case -- it feels like some relatively tightly bounded linear growth would be better for most things?

**Comment by davepacheco** [comment]
See also #1270.
