### ISSUE TITLE
disseminate virtual-to-physical IP mappings upon live migration

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/omicron#2002]
When a guest migrates from one sled to another, we need to make sure to update the Virtual-to-Physical IP mappings across the rack.

On each sled there is a global xde device/instance running that holds a global V2P mapping for each VPC. These mappings are how each OPTE Port maps a guest's Virtual IP to its Physical IP. When an instance migrates from one sled to another, its physical IP changes from that of the source sled to that of the destination sled. At this moment, the V2P mapping for that guest is rendered stale across the entire rack. Any guest currently in communication with the migrating guest now has a stale mapping, and is sending data to the source sled, instead of destination sled.

When migrating, Nexus, at some point, needs to disseminate the new V2P mapping for this guest to all sleds in the rack.

Related to #252.

**Comment by luqmana** [comment]
Some initial support in https://github.com/oxidecomputer/omicron/pull/2536

**Comment by gjcolombo** [comment]
This was fixed by #3127.
