### ISSUE TITLE
Operator View: Updates - what version am I on?

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2038]
The operator API should be API to report the version of a variety of subcomponents on the rack. Note that this should be as "honest as possible", describing different subcomponents which may even change across a more broad update.

Also note: This API should probably not be a traditional CRUD API -- we do want the ability to read, but we don't want unrestricted ability to update subcomponents to arbitrary versions.

**Comment by smklein** [comment]
Assigning this to @david-crespo who mentioned working on the API skeleton. I'm happy to help out with chunks of the backend; feel free to loop me in wherever you need help.

**Comment by smklein** [comment]
See also: https://github.com/oxidecomputer/omicron/issues/2105

**Comment by david-crespo** [comment]
Can we call this complete?

https://github.com/oxidecomputer/omicron/blob/de62418191f91263a23a62ac3eb4f33d23c55904/nexus/src/external_api/http_entrypoints.rs#L5425-L5460

**Comment by david-crespo** [comment]
Closed by #2100
