### ISSUE TITLE
`test_setup_database_bad_listen_url()` builds an invalid command and can racily fail

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#2108]
I saw this locally when using `cargo nextest run` to execute the full test suite:

```
--- STDERR:                                               omicron-test-utils dev::db::test::test_setup_database_bad_listen_url ---
will run: bash start-single-node --insecure --http-addr=:0 -c sleep 60 --store=path=/tmp/.tmphSogYR/data,ballast-size=0 --listen-addr 127.0.0.1:0 --listening-url-file /tmp/.tmphSogYR/listen-url
environment:
... snip ...
bash: start-single-node: No such file or directory
error: Exited { exit_code: 127 }
thread 'dev::db::test::test_setup_database_bad_listen_url' panicked at 'unexpected error trying to start database: cockroach exited unexpectedly with status 127 (see error output above)', test-utils/src/dev/db.rs:1196:13
```

but running the test in isolation passes. I think what's happening is:

1. `test_setup_database_bad_listen_url()` is testing our `start()` method, not cockroachdb specifically, so it actually tries to start a `bash -c sleep 60`: https://github.com/oxidecomputer/omicron/blob/main/test-utils/src/dev/db.rs#L1175-L1176
2. However, `CockroachStarterBuilder::new_with_cmd()` assumes it's always running cockroachdb, and inserts other args before the `-c sleep 60`: https://github.com/oxidecomputer/omicron/blob/main/test-utils/src/dev/db.rs#L126-L129
3. This produces the invalid `bash start-single-node ...` command I see in the failure above
4. `start()` then races: if bash exits with the error fast enough, we'll hit https://github.com/oxidecomputer/omicron/blob/main/test-utils/src/dev/db.rs#L362-L364 and fail the test (which I see when running the full test suite). If the test wins the race and checks the listen url file before bash exits (https://github.com/oxidecomputer/omicron/blob/main/test-utils/src/dev/db.rs#L374), we'll see the expected error and pass the test

**Comment by davepacheco** [comment]
Sorry about this!  Testing a fix now.
