### ISSUE TITLE
Race in instance creation saga can cause an instance to be running when it's supposed to be stopped

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#2209]
Repro steps: none yet; found this bug by inspection.

Consider the following steps:

1. Instance creation saga begins and reaches the `sic_instance_ensure` phase
2. Nexus calls sled agent to ensure the instance exists and to drive it to the Running state
3. Saga executor crashes
4. Sled agent creates and starts the instance
5. Guest OS in the instance shuts down (e.g. because a user logged into it and shut it down, or because of a problem the guest detects)
6. Propolis stops and destroys the instance, reporting this to sled agent; sled agent observes these transitions and tears down and forgets about the instance
7. Saga executor restarts from the start of the `sic_instance_ensure` step; this recreates and starts the instance when it really should be stopped

There's much more discussion in the comments on [this gist](https://gist.github.com/gjcolombo/506c2016584e96f6adb20e47b3c51894). Some important notes from that discussion that influence how we can fix this:

- Sled agent can crash/restart at any time, so we can't rely on a sled agent having any particular memory of the commands Nexus has sent it
- Once the VM is running, guest software can request a shutdown at any time and for any reason, with no user intervention required, so we can't prevent this by e.g. trying to prevent the user from accessing the instance until we know the creation saga is done

**Comment by smklein** [comment]
My proposal from the gist, as one possible fix:

Split the "instance_ensure" saga step into two steps:
1. "Instance create". Create a new, not-yet-running instance on the target sled.
2. "Instance start, with generation number". Send a request to the previously-created instance on the target sled.

- If we crash and redo (1), we can make creation idempotent. This shouldn't be a problem, as we haven't told the instance to start yet.
- If we crash and redo (2), we can safely ignore the request if the generation number is lower than the latest state-change request **OR** if the instance does not exist because it has been torn down (in this case we probably want to propagate an error back to Nexus).

It's a bit of a bummer this introduces an extra round-trip request on a hot path, so I'd be open to alternatives that can accomplish the same in a single request.

**Comment by gjcolombo** [comment]
Is the generation number the existing generation number in the `InstanceRuntimeState` or something else? I'm wondering about a case like the following:

1. Instance creation saga begins and creates the instance record
2. Executor issues the "instance create" call to sled agent
3. Executor crashes
4. Without waiting for the saga to complete, a user calls the "start instance" API; this works because the saga created the instance record already
5. The instance starts and the user shuts it down as before; sled agent forgets about the instance (?)
6. New executor restarts from the instance creation step

Is there some generation number machinery that prevents us from recreating and restarting the instance when this happens?

**Comment by gjcolombo** [comment]
One idea I've been toying with lately is the idea of separating our record of an Instance from our records of *incarnations of* that instance. This is convenient when live migrating, because it helps to reduce the complexity that arises from having two sleds that want to talk to Nexus about the same instance--they can talk about their respective incarnations instead, and we just have to deal with the problem of cutting over from one incarnation to another. I wonder if it might help here, though; in the example above, we could say in step 4 that because the instance already has an incarnation, we will ignore/reject/otherwise dispose of the request to start it again.

YMMV here, this is extremely hand-wavy, needs more formalization, etc., but I want to get that framework out there as a possible approach to this sort of problem.

**Comment by smklein** [comment]
> Is the generation number the existing generation number in the `InstanceRuntimeState` or something else? I'm wondering about a case like the following:
> 
> 1. Instance creation saga begins and creates the instance record
> 2. Executor issues the "instance create" call to sled agent
> 3. Executor crashes
> 4. Without waiting for the saga to complete, a user calls the "start instance" API; this works because the saga created the instance record already
> 5. The instance starts and the user shuts it down as before; sled agent forgets about the instance (?)
> 6. New executor restarts from the instance creation step
> 
> I need to think about it more, but is there some generation number machinery that prevents us from recreating and restarting the instance when this happens?

The generation number from `InstanceRuntimeState` is, *I think* only used by Nexus to distinguish reports of state changes from Sled Agent. I think this means that if the sled agent is sending two updates, Nexus can order them and know which one was "latest" by the generation number.

I don't think any notion of a generation number is being sent from Nexus -> Sled Agent, it's only used the other way.

Anytime that Nexus sends a request to the Sled Agent, asking it to initialize a new instance, it passes the following structure:

https://github.com/oxidecomputer/omicron/blob/b8a461754ac302dd6171b76888ad3cbb512a1037/sled-agent/src/params.rs#L111-L120

I think my proposal was basically:

- Have one endpoint to initialize the instance (e.g., passing `InstanceHardware`). This would allocate in-memory on the sled for the instance object, where it could use that generation aforementioned generation number. 
- Have another endpoint to changes the runtime state (e.g., passing `InstanceRuntimeStateRequested`, and the generation number which previously only came from Sled Agent -> Nexus). This way, if the state of the instance changed, we can tell Nexus that the picture of the world it had is out-of-date.

So, from Nexus' point-of-view, this might look like:

- Create instance (not running)
- Request: Start instance
- Response: Instance started OK
- Inference: Cool, we did start the instance! Let's insert the record in the DB, as long as we haven't heard of any even-more-recent updates from the sled itself.

OR

- Create instance (not running)
- Request: Start instance
- Response: Generation number out-of-date
- Inference: We must have previously tried this saga step, but the instance is running already. Cool, claim success, don't update anything in the DB.

Or:

- Create instance (not running)
- Request: Start instance
- Response: Instance does not exist
- Inference: Either the instance was deleted on its own, or the sled bounced. Probably fine to return an error and unwind.

**Comment by gjcolombo** [comment]
> So, from Nexus' point-of-view, this might look like:

This all makes sense to me. I think the part I'm still not following is what happens in the cases where the saga restarts from the *create* step after the instance has come and gone at least once.

> All that said, I'm not sure I see how separating the DB tables makes this race condition go away. Even if the two are decoupled, it still seems possible for a request from Nexus to a Sled Agent to "ensure an instance instantiation exists" could be re-sent after the instance shuts itself down.

That's my fault, I didn't bother to explain this at all :) I was thinking each Instance would have a column that either contains null or the ID of an ActiveInstance. We would then use that for mutual exclusion: in my example above, the saga would add an Instance record with the ActiveInstance ID it intends to use; any call to start the instance while it is still being incarnated would just succeed harmlessly/fail with some kind of "the instance is already being created" message/whatever the appropriate response is instead of being directed to a sled. (The `active_propolis_id` column actually allllmost works for this--we'd just have to make it nullable and then manipulate it appropriately. Not sure that does live migration many favors, though.)

Note that by itself, this doesn't save us from having to create the VM and start it in separate steps--we would still need that to ensure that the saga won't try to create an instance a second time after it has gotten to a point where it can destroy itself. (And agreed that we should try not to add that extra hop if we can help it.)

**Comment by davepacheco** [comment]
> Is the generation number the existing generation number in the `InstanceRuntimeState` or something else? I'm wondering about a case like the following:
> 
>     1. Instance creation saga begins and creates the instance record
> 
>     2. Executor issues the "instance create" call to sled agent
> 
>     3. Executor crashes
> 
>     4. Without waiting for the saga to complete, a user calls the "start instance" API; this works because the saga created the instance record already

I don't think this should be legal.  The record exists, but that doesn't mean it has to be visible to the public API or that this operation should be legal (and I don't think it should be).

**Comment by gjcolombo** [comment]
> I don't think this should be legal. The record exists, but that doesn't mean it has to be visible to the public API or that this operation should be legal (and I don't think it should be).

I think that makes sense. Today the code allows this (AFAICT, anyway; I don't see anything in the instance start path that tries to avoid this), so we'll need to patch up that path in addition to whatever we end up doing with the creation saga itself.

**Comment by gjcolombo** [comment]
I wrote a TLA+ spec that tries to model these interactions and was able to get it to fail in the manner I described in the OP. (I'm pretty inexperienced with both modeling *and* Omicron, so it's possible that the problem is that the code's fine and the model just doesn't represent it properly. But I think I got all the behaviors correct.)

Now that I have a bunch of the necessary primitives in place, I'll try modeling a saga where the "create" and "run" steps are separate and see how that changes things.

**Comment by gjcolombo** [comment]
I'm still worried that the model is massively oversimplifying things, but naively splitting the create step into separate create and run steps (both of which can be retried) passes model checking with 4 actors (who can run instance create sagas or shut down running VMs), 3 instances, and 2 sleds. The TLC console at least shows that the new actions were both encountered plenty of times, so I didn't obviously make a state unreachable when it should have been reachable.

I'm not modeling anything to do with generation numbers at this point. I think we *might* get away without them, but only because of some Propolis and sled agent implementation details that we might not want to rely on going forward. (Specifically, once Propolis notices that an instance has stopped, it irrevocably drives the instance to the Destroyed state, ignoring any subsequent requests to launch the instance. And once sled agent sees the Destroyed transition, it will end up destroying the zone and unregistering the instance no matter what else Nexus requests. So a request to run the instance again once the user has shut it down will be silently dropped. Or so I think.)

There is still a *bunch* of stuff I'm not modeling here but this seems like a good direction to explore further.
