### ISSUE TITLE
"omicron-rpaths: expected "DEP_PQ_LIBDIRS" to be set in the environment"

### ISSUE THREAD

**Issue by steveklabnik** [oxidecomputer/omicron#2210]
Hey folks!

I am attempting to build omicron on WSL2. I have a fresh wsl2 install. I am currently getting:

```text
error: failed to run custom build command for `nexus-db-model v0.1.0 (/home/steveklabnik/oxide/omicron/nexus/db-model)`

Caused by:
  process didn't exit successfully: `/home/steveklabnik/oxide/omicron/target/debug/build/nexus-db-model-e2519edd4e9d9100/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'omicron-rpaths: expected "DEP_PQ_LIBDIRS" to be set in the environment, but found it unset.  (Is the current crate missing a dependency on a *-sys crate?)', rpaths/src/lib.rs:163:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I ran `/tools/install_builder_prerequisites.sh` and it reports everything is installed successfully and my PATH looks correct.

Any ideas about what I'm missing here would be helpful, thank you!

**Comment by jgallagher** [comment]
Others can fill in more detail here, but I think the issue is centered around https://github.com/oxidecomputer/omicron/blob/main/rpaths/src/lib.rs. `nexus-db-model`'s build script calls [`omicron_rpaths::configure_default_omicron_rpaths()`](https://github.com/oxidecomputer/omicron/blob/main/rpaths/src/lib.rs#L105-L109), which is a no-op on "non-illumos, non-linux". I assume WSL should do something here rather than nothing.

**Comment by steveklabnik** [comment]
> which is a no-op on "non-illumos, non-linux"

Not *quite*, the block that's running is defined as 

```rust
#[cfg(any(target_os = "illumos", target_os = "linux"))]
```

which means if it's either, it works, and wsl's `target_os` is `linux`. This patch (after adding the dependency) panics with the message:

```rust
#[cfg(any(target_os = "illumos", target_os = "linux"))]
mod internal {
    use std::ffi::OsStr;

    pub fn configure_default_omicron_rpaths() {
        if wsl::is_wsl() {
            panic!("is wsl");
        }
```

so it's probably a behavioral issue in here rather than a cfg issue, I'd guess.

**Comment by smklein** [comment]
Since I noticed this was *specifically* while building `nexus-db-model`, I checked, and that crate *does* have a dependency on `pq-sys`:

https://github.com/oxidecomputer/omicron/blob/a72104bf051b815524a76b860ac4fe98acf3c69c/nexus/Cargo.toml#L48-L49

I wonder if we're diverging because of https://github.com/oxidecomputer/pq-sys/commit/b1194c190f4d4a103c2280908cd1e97628c5c1cb ?

**Comment by davepacheco** [comment]
According to [the comment on this panic message](https://github.com/oxidecomputer/omicron/blob/a72104bf051b815524a76b860ac4fe98acf3c69c/rpaths/src/lib.rs#L154-L160), you could also see this panic message if the build script for pq-sys failed to emit the expected metadata.  Do you have the stdout/stderr from that?  I wonder if you either don't have libpq or the autodiscovery mechanisms built into pq-sys are not finding it correctly.  `install_builder_prerequisites.sh` is supposed to take care of this but I'm not sure it's been tested on WSL2.

**Comment by steveklabnik** [comment]
pq_sys's `output` file

```text
cargo:rerun-if-env-changed=PQ_LIB_DIR
cargo:rerun-if-env-changed=PQ_LIB_STATIC
cargo:rerun-if-env-changed=TARGET
cargo:rerun-if-env-changed=PG_CONFIG_X86_64_UNKNOWN_LINUX_GNU
cargo:rerun-if-env-changed=PQ_LIB_STATIC_X86_64_UNKNOWN_LINUX_GNU
cargo:rustc-link-lib=pq
```

`stderr` is empty.

**Comment by steveklabnik** [comment]
Given the line of code @smklein points out above, this would not seem to include `cargo:libdirs`, so that feels like it's on the right track?

```console
steveklabnik@DESKTOP-FID8M5M:~/oxide/omicron$ pkg-config --exists libpq
steveklabnik@DESKTOP-FID8M5M:~/oxide/omicron$ echo $?
0
```

I'm not sure why it wouldn't find that library. However, looking at how it sets up `link_paths`: https://github.com/rust-lang/pkg-config-rs/blob/master/src/lib.rs#L675-L679

```console
$ pkg-config --cflags libpq
-I/usr/include/postgresql
```

it appears that pkg-config suggests none of them, and therefore the array is empty, therefore we don't print out that message.

**Comment by davepacheco** [comment]
Yeah, so that's consistent with pq-sys not emitting the metadata that we expect (which is [`cargo:libdirs=...`](https://github.com/oxidecomputer/pq-sys/blob/b1194c190f4d4a103c2280908cd1e97628c5c1cb/build.rs#L140)).  Looking at the [logic for finding libpq](https://github.com/oxidecomputer/pq-sys/blob/b1194c190f4d4a103c2280908cd1e97628c5c1cb/build.rs#L85-L96), it looks like we'll use whatever's in the `PQ_LIB_DIR` env var, if specified; otherwise try pkg-config, then vcpkg, and then the result of `pg_config --libdir`.  I believe on most development systems we wind up using either pkg-config or `pg_config --libdir`.  I'm not sure what's appropriate for this system, but based on that output, it looks like all of these failed to find libpq.

**Comment by steveklabnik** [comment]
for completeness:

```console
steveklabnik@DESKTOP-FID8M5M:~/oxide/omicron$ echo $PQ_LIB_DIR

steveklabnik@DESKTOP-FID8M5M:~/oxide/omicron$ pg_config --libdir
/usr/lib/x86_64-linux-gnu
```

**Comment by steveklabnik** [comment]
The above does mean that if i set `PQ_LIB_DIR` to the value of `pg_config --libdir`, I do get a build.

I'm not sure what the right "fix" is here, exactly. I'd *probably* say that the logic shouldn't be "find that one of these exists and then build the directories list for it" but instead be "build the directories list out of these things and then use it", if that makes any sense. Happy to write/test a patch if that sounds good, or do something else you'd prefer.

**Comment by steveklabnik** [comment]
The above does mean that if i set `PQ_LIB_DIR` to the value of `pg_config --libdir`, I do get a build.

I'm not sure what the right "fix" is here, exactly. I'd *probably* say that the logic shouldn't be "find that one of these exists and then build the directories list for it" but instead be "build the directories list out of these things and then use it", if that makes any sense. Happy to write/test a patch if that sounds good, or do something else you'd prefer.

**Comment by davepacheco** [comment]
> The above does mean that if i set `PQ_LIB_DIR` to the value of `pg_config --libdir`, I do get a build.

That's interesting.  Was `pg_config` on your PATH when you tried to build omicron and got the failure you mentioned in the description?  If so, I'm not sure why that value wasn't found and used by the pq-sys build script.  That may be worth debugging further (maybe adding more instrumentation to that script?).

> I'm not sure what the right "fix" is here, exactly. I'd _probably_ say that the logic shouldn't be "find that one of these exists and then build the directories list for it" but instead be "build the directories list out of these things and then use it", if that makes any sense. Happy to write/test a patch if that sounds good, or do something else you'd prefer.

Can you elaborate?  I'm not sure what you mean.

I'm not sure if this changes things, but most of this behavior comes from upstream pq-sys.  I think it matches common expectations of things that probe around to find dependencies on the build system and encode whatever they find into the final binary.  There are considerable downsides to this pattern (like hard-to-debug problems finding deps, or getting the wrong deps; and the fact that the production machine might not match the build system).  We weren't trying to fix any of that here.  Our only diff is to emit metadata once it's found.  (Nor is that to say we _shouldn't_ change something here if it's not working for us!)

**Comment by steveklabnik** [comment]
Sorry for the late response here, I now have an account on the big old shared illumos build machine, so this is not as critical for me, and so maybe is a WONTFIX.

>  Was pg_config on your PATH when you tried to build omicron and got the failure you mentioned in the description?

Absolutely, yes.

>  If so, I'm not sure why that value wasn't found and used by the pq-sys build script. That may be worth debugging further (maybe adding more instrumentation to that script?).

It's because of what I said (in admittedly a probably confusing way) above: [this logic](https://github.com/oxidecomputer/pq-sys/blob/oxide/main/build.rs#L84-L93) does not try every option and then use what it found, it uses whichever one returns true first. Because I have pkg-config installed, [we never get to the "try pg_config" option in the first place](https://github.com/oxidecomputer/pq-sys/blob/oxide/main/build.rs#L87). 

> I'm not sure if this changes things, but most of this behavior comes from upstream pq-sys.

They also aren't trying to engage with this logic to do anything specific.

>  I think it matches common expectations of things that probe around to find dependencies on the build system and encode whatever they find into the final binary.

Sure, the issue here is the order of things being probed, and that it stops probing even if it gets an empty result from the probe. If you probed `pg_config` before `pkg-config`, this would have worked!

**Comment by davepacheco** [comment]
> > If so, I'm not sure why that value wasn't found and used by the pq-sys build script. That may be worth debugging further (maybe adding more instrumentation to that script?).
> 
> It's because of what I said (in admittedly a probably confusing way) above: [this logic](https://github.com/oxidecomputer/pq-sys/blob/oxide/main/build.rs#L84-L93) does not try every option and then use what it found, it uses whichever one returns true first. Because I have pkg-config installed, [we never get to the "try pg_config" option in the first place](https://github.com/oxidecomputer/pq-sys/blob/oxide/main/build.rs#L87).

Ah, I see what you meant above.  But as I read the code, these functions are not supposed to return true unless they _successfully_ find libpq.  It seems like the pkg-config module is surprising us by reporting that it successfully found it, but didn't emit a link path entry.  That seems likely incorrect, right?

> > I'm not sure if this changes things, but most of this behavior comes from upstream pq-sys.
> 
> They also aren't trying to engage with this logic to do anything specific with these paths, and so don't even really go looking for them.

I'm not sure what you mean.

> > I think it matches common expectations of things that probe around to find dependencies on the build system and encode whatever they find into the final binary.
> 
> Sure, the issue here is the order of things being probed, and that it stops probing even if it gets an empty result from the probe. If you probed `pg_config` before `pkg-config`, this would have worked!

Totally.  Thanks for clarifying that.  I think the question I don't know how to answer yet is: should we ignore a "successful" pkg-config probe that produced no link paths, or is the bug that the pkg-config succeeded despite reporting no link paths?  (If the latter, we could produce a fatal error in this case, but there'd still be another issue to fix.)

**Comment by steveklabnik** [comment]
>  It seems like the pkg-config module is surprising us by reporting that it successfully found it, but didn't emit a link path entry. That seems likely incorrect, right?

I can't speak to its correctness, as I'm not sure what the norm is *supposed* to be here. `pkg-config` does know about this library, so it should return correct in that sense, but I don't know if the absence of an explicit `-L` is expected. Given that normal usage is like

    $ cc `pkg-config --cflags --libs libpq` foo.c

I would expect that the lack of an explicit `-L` is very normal; in fact if I run that sub-command here I get `-I/usr/include/postgresql -lpq`. This works because `/etc/ld.so.conf` ends up including a file that contains `/usr/lib/x86_64-linux-gnu`, which has `libpq.so` inside of it, so the linker finds it and there's no issues.

BUT! Regardless of all of that:

1. This is no longer an actual issue for me, in the sense that I plan on doing my work on illumos directly now. 
2. I actually can no longer reproduce the issue; it seems that it's building for me now, somehow. Maybe I modified the environment, but I can't remember doing so and none of the obvious places I'd do so (I figured maybe I'd set `PQ_LIB_DIR` in my `.bashrc` but I have not, and in fact, it is empty and I still get a build, so I dunno!)

So, I'm going to close this issue, as I don't think it's worth either of our time to try and track this down. If someone else runs across it in the future, then it's probably worth digging into with their reproduction.

**Comment by jclulow** [comment]
> I would expect that the lack of an explicit `-L` is very normal; in fact if I run that sub-command here I get `-I/usr/include/postgresql -lpq`. This works because `/etc/ld.so.conf` ends up including a file that contains `/usr/lib/x86_64-linux-gnu`, which has `libpq.so` inside of it, so the linker finds it and there's no issues.

I agree with this assessment, FWIW.  It's very system- (and even site-) dependent, and often there will be no explicit path required.

**Comment by davepacheco** [comment]
> > I would expect that the lack of an explicit `-L` is very normal; in fact if I run that sub-command here I get `-I/usr/include/postgresql -lpq`. This works because `/etc/ld.so.conf` ends up including a file that contains `/usr/lib/x86_64-linux-gnu`, which has `libpq.so` inside of it, so the linker finds it and there's no issues.
> 
> I agree with this assessment, FWIW. It's very system- (and even site-) dependent, and often there will be no explicit path required.

Okay, that makes sense.  It may be that our metadata script ought to be less picky about this case (i.e., just go ahead and build the binary without any extra rpaths).  But given how easy it is to _accidentally_ do this, and how bad the failure mode is (don't find out until runtime, sometimes while the program is running) and how hard it is to debug, and given that nobody's experiencing a problem with this any more, I'm inclined to leave this as-is.  I guess if we decide to do something, we could have the pq-sys build script set some other metadata key that indicates "we probed for the library and found it with no specific path for it".  Then omicron-rpaths could decide what to do with that.  We could have it fail like we do now, or we could have it succeed but print a warning if some BUILD_DEBUG env var is set, or we could always print a warning -- whatever.  But at least then, in omicron-rpaths, we'll be in a position to know both what library was found, if it needs an rpath, and (potentially) whether that's what the user expected.  Again, I won't plan to do anything here for now.

Thanks @steveklabnik for the help!
