### ISSUE TITLE
sleds should propagate serial number during "self-reporting" API to nexus

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2211]
```
BRM42220004 # prtconf -v /devices | grep -A1 baseboard-identifier
        name='baseboard-identifier' type=string items=1
            value='BRM42220004'
```

Nabbing this info and plumbing it up to Nexus means that Nexus can correlate "self-reported" information about sleds with "MGS-reported" information about sleds.

**Comment by jclulow** [comment]
NB: The baseboard identifier is not technically sufficient, you also want the model and revision, I believe.  I am not sure that the BRM* portion of the serial number is unique on its own.

**Comment by smklein** [comment]
Will be completed by https://github.com/oxidecomputer/omicron/pull/2258
