### ISSUE TITLE
Wicket: (First time setup)  Capture IP, SSL, DNS, NTP and BGP information from technician port

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2217]
This information must be transferred over the TUI to proceed with subsequent onboarding information.

See also: https://github.com/oxidecomputer/omicron/issues/2218 - this information must not only be collected from the technician port, but transferred to RSS.

**Comment by sunshowers** [comment]
Done in #3326 and other related PRs.

**Comment by sunshowers** [comment]
Done, and tested end to end in the dogfood rack.
