### ISSUE TITLE
NTP: Choose an NTP daemon (maybe chrony?)

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2220]
Part of https://github.com/oxidecomputer/omicron/issues/2219

More discussion on RFD 34

**Comment by davepacheco** [comment]
I don't have a ton of experience here but as a data point: while doing the work for RFD 110 I found that the ntpd available out-of-the-box (at the time) was not sufficient for keeping in sync, but that chrony was easy to package, configure, and monitor, and kept the clocks very closely in sync.  (I don't know about other choices and that's about the limit of my experience, but it was such an improvement I wanted to mention it.)

**Comment by citrus-it** [comment]
chrony is what has been implemented for the MVP.
