### ISSUE TITLE
NTP: Package daemon as a zone

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2221]
See:

- `package-manifest.toml` for how to bundle this up
- Mechanically, this will be launched be either bootstrap or sled agent service: https://github.com/oxidecomputer/omicron/issues/2223

**Comment by smklein** [comment]
Blocked on https://github.com/oxidecomputer/omicron/issues/2220, presumably, unless we're just rolling with chrony for the time being.

**Comment by citrus-it** [comment]
Integrated as https://github.com/oxidecomputer/omicron/commit/3511c5f75df0fb8242c9c457c3e8a2169c3f39f4
