### ISSUE TITLE
NTP: Every Gimlet: Spin up zone running NTP daemon

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2223]
Depends on https://github.com/oxidecomputer/omicron/issues/2221

**Comment by smklein** [comment]
Blocked on https://github.com/oxidecomputer/omicron/issues/2221

**Comment by citrus-it** [comment]
Integrated in https://github.com/oxidecomputer/omicron/commit/3511c5f75df0fb8242c9c457c3e8a2169c3f39f4
