### ISSUE TITLE
Networking: Track what needs to happen for live migrations

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#2377]
In addition to propolis-contained state, we also need to track the following for instance migration.

- [ ] Update switch NAT tables.

The rack switches contain ingress NAT tables that map an external address and a port to a sled underlay address, VNI, and VM MAC address.

```
(external addr, port) -> (sled underlay address, geneve vni, instance mac)
```

When an instance is migrated to another sled, these tables need to be updated with the new underlay address target. There is one NAT table for external IPv4 addresses and one for IPv6.

- [ ] Update OPTE v2p mappings across the rack.

OPTE contains a virtual-to-physical mapping that tells it what underlay destination address is associated with an instance-assigned IP address. If an instance migrates to a new sled, this mapping needs to be updated.

**Comment by bnaecker** [comment]
These are already tracked, in the following issues:

- https://github.com/oxidecomputer/omicron/issues/1464
- https://github.com/oxidecomputer/omicron/issues/2002
