### ISSUE TITLE
Installinator tests are quite verbose

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#2389]
When running `cargo test` at the top-level in Omicron, I've noticed that the installinator tests are quite noisy, spitting out many thousands of log lines. This can make finding failures a bit tricky. Most tests seem to use `omicron_test_utils::dev::test_setup_log()` as a useful way to get all data on failures, but avoid printing on success. I think [`slog_term::TestStdoutWriter`](https://docs.rs/slog-term/latest/slog_term/struct.TestStdoutWriter.html) is another useful tool here, ensuring the test harness captures log output like a normal `println!()`.

**Comment by sunshowers** [comment]
Thanks for catching this! I didn't realize this because I use nextest, but it's definitely something that should be fixed for cargo test.
