### ISSUE TITLE
decide if we want to apply constraints to disk size, memory size

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#2415]
RFD 4 says that memory can only be requested in multiples of 256 MiB.  I'm not sure if that's the right value, but it's worth deciding if we need any constraints like this on disk or memory sizes because this will be a breaking change to introduce post-MVP.

**Comment by zephraph** [comment]
This work was completed through a few initiatives

https://github.com/oxidecomputer/omicron/issues/3212#issuecomment-1634497344 outlines the limits, but to recap here

- 32 vCPUs - https://github.com/oxidecomputer/omicron/pull/3574
- 64 GiB memory - https://github.com/oxidecomputer/omicron/pull/3574
- 1 TiB disk - https://github.com/oxidecomputer/omicron/pull/3624

These limits were also added to validation in console via https://github.com/oxidecomputer/console/pull/1656
