### ISSUE TITLE
Silo-scoped images

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#2521]
#2471 adds project-scoped images. Initially it also included the concept of promoting an image to "global", i.e., visible to all users in the silo. It did this by setting an `is_global` flag on the image. Any request to list images for any project would include the ones for that project _plus_ all global images. We ran into two related problems, first discussed in https://github.com/oxidecomputer/omicron/pull/2471#pullrequestreview-1331190504.

## Silo-scoped filtering problem

Truly global is not the same as silo-scoped, and what we want is the latter. The problem is that we generally rely on the parent to determine whether you have access to a resource: if you can see a project, you can see its children. Whether you can see a project may rely on following the chain up to _its_ parent. But a global image is disconnected from its parent project by design. We cannot use the parent project to figure out whether a given image is in scope, i.e., in silo. If User A has access to `project-1` only, and an image is in `project-2` and it is marked global, User A is supposed to be able to see that image even if they cannot see `project-2`, but only if `project-2` is in the user's silo.

If we want to filter images by something other than their parent project, we need to explicitly associate images with their silo so we can filter by that instead of parent project. We could add a nullable `silo_id` column to images, but it seems cleaner to add a `silo_images` table containing `(silo_id, image_id)`, and what it ultimately means for an image to be promoted to "global" is for it to have an entry in that table. Then, when we want to list images for a project, we get the current silo, look at `images left outer join silo_images on images.id = silo_images.image_id`, and filter for images either in the current project _or_ in the current silo.

## Authz problem

Just as we use the parent for filtering in the DB query, we also use the parent for authz, and just as we can't do that here for filtering, we also can't do it for authz. So we need a way to express that silo-scoped images are accessible to anyone in that silo even if they can't see the project that image ultimately belongs to. Likely this would mean making a new authz resource that impls `oso::PolarClass` and `AuthorizedResource` manually instead of using the `authz_resource!` guardrails, and then giving it some special logic in `omicron.polar`.

## More drastic alternatives abound

Another option would be to have a whole separate resource called a `SiloImage` that's a child of the `Silo`. In this case promoting a project-level `Image` to "global" would mean copying it into a `SiloImage`. `SiloImage` could then have its own normal authz behavior, requiring read perm on the parent collection (the silo). It might be nice to be able to use the standard auth helpers here, but this version would be more complicated in other ways. We need to make sure we understand the experience we want to provide to users around images, and see if there's anything there that would be a lot easier to provide with one setup or the other.

**Comment by zephraph** [comment]
This is related to (and should be captured in) RFD-362.

**Comment by askfongjojo** [comment]
Is this considered done?

**Comment by zephraph** [comment]
Yes, this is done.
