### ISSUE TITLE
Set of Dendrite SMF service properties is out of date

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#2537]
The sled agent sets configuration and parameters for a bunch of SMF services it launches by setting service properties. It [currently sets the Dendrite `transceiver_interface` property to `"tfportCPU0"`](https://github.com/oxidecomputer/omicron/blob/4be8799dd8343db62121f7168391a7dc230d80fe/sled-agent/src/services.rs#L835). That's out of date as of [this commit](https://github.com/oxidecomputer/dendrite/commit/3987ed692d7e24bc976cb0d3157930c9e298f624), which merged code that automatically setup a new VLAN interface named `"sidecar0"` for that instead. The SMF property on L835 should be changed to `"sidecar0"` to match that.

**Comment by jclulow** [comment]
I don't think this property should be set by sled agent at all, should it?  The VLAN interfaces are under the control of stuff inside the zone, so probably sled agent should just leave it up to the zone provided manifest to be correct?

**Comment by bnaecker** [comment]
I think that's reasonable, I was going to ask about the cross-repo dependency here.

**Comment by bnaecker** [comment]
See https://github.com/oxidecomputer/dendrite/pull/118 for the Dendrite side of this. That will set the transceiver interface to what we expect to use in the production zone. I'll follow up in a bit with a PR on Omicron that pulls this change and removes any setting of it by the sled agent.

**Comment by bnaecker** [comment]
Omicron side: https://github.com/oxidecomputer/omicron/pull/2546

**Comment by bnaecker** [comment]
Closed by https://github.com/oxidecomputer/dendrite/pull/118 and https://github.com/oxidecomputer/omicron/pull/2546
