### ISSUE TITLE
Create tests to verify query performance constraints

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/omicron#254]
As spawned from https://github.com/oxidecomputer/omicron/pull/243#issuecomment-921916122, we want to create a test or suite of tests to validate our generated queries avoid full table scans or unnecessary sorts. This will generally be achieved by running `EXPLAIN` on the individual queries. By default, Cockroach will do a full table scan even with indexes if the table is small which is deceptive given that's one of the properties we want to avoid at a larger scale. We may either need to set [`disallow_full_table_scans=on`](https://www.cockroachlabs.com/docs/v21.1/explain.html#query-optimization) or have a db populated with a large set of seeded data to ensure we bypass Cockroach's optimizations for out `EXPLAIN` operations. 

This may necessitate that we break queries out of the helper functions in `datastore.rs` so that we can build `EXPLAIN` queries against them. The raw query text should be retrievable by using [`debug_query`](https://docs.diesel.rs/diesel/fn.debug_query.html).

**Comment by davepacheco** [comment]
Related: you can [limit the number of rows read or written by a query](https://www.cockroachlabs.com/docs/v21.2/transactions#limit-the-number-of-rows-written-or-read-in-a-transaction).  This might be a good backstop in production.  And similar to the above idea, if we had comprehensive coverage testing and could create a database with counts larger than some fixed value (say, 500 of everything), then we could run the test suite with a limit applied and have some confidence we weren't accidentally doing something pathological.

**Comment by davepacheco** [comment]
Now see #999.
