### ISSUE TITLE
mgs & wicketd -  Expose versions from Caboose for SP and RoT

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#2558]
We currently utilize the u32 integer version from the `RotBootState` plumbed through the MGS `state` endpoint for the RoT. We use a similar u32 version in the Hubris `ImageHeader` for the RoT. Version information for the new stage0 and hubris images is going to come in the form of the `caboose`, which is appended to hubris images and contains TLVC data. This data is already in MGS messages but not exposed via MGS to wicketd. It also isn't exposed from wicketd.

We want to determine whether we expose the whole caboose or only parts of it so we can use it in wicket.

**Comment by andrewjstone** [comment]
cc @mkeeter @cbiffle @lzrd

**Comment by mkeeter** [comment]
See also https://github.com/oxidecomputer/management-gateway-service/pull/66 , which adds APIs to request the SP caboose.  We'll need to add a new API to read from the RoT caboose once that's ready.

**Comment by jgallagher** [comment]
#2594 is the first part of this (expose the caboose from MGS).

**Comment by jgallagher** [comment]
#3239 Finishes plumbing this up through wicket
