### ISSUE TITLE
Want Operator API to power off, reboot, power up sled to support sled maintenance

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#2754]
Currently there is no API for operator to act on a sled. Operator should be able to make power-cycle requests to facilitate sled hardware and software maintenance.

Rebooting and powering off a sled may result in disruptions on control plane services. We may need to consider including certain mitigations to achieve graceful shutdown (e.g. detecting which internal services run on the sled and proactively take the nodes out of DNS).

**Comment by jclulow** [comment]
I think we want to be pretty careful when providing that kind of direct imperative control over lower level details of sled state.  For example framing the API as "power off this sled" is going to immediately conflict with our control of the rack, but you could envisage higher level APIs like "drain sled of services for removal" that would then influence what we're doing with things.

**Comment by askfongjojo** [comment]
Sled reboot after software update is currently intended to be done programmatically. In the case of HW maintenance, it is likely that customer will need to contact Support initially. Moved this for consideration to MVP+1 to evaluate the need for operator control of sleds.

**Comment by askfongjojo** [comment]
Some additional Q&A from the Figma Inventory UI mockup discussion thread:

**Angela Fong:** Will there be operator APIs for powering on/off and reboot sleds from the control plane? (Maybe a question for @Sean Klein)

**Sean Klein:** Although I expect Nexus will internally be able to control the power state of sleds (talking to MGS), we aren't currently exposing this from the operator API of Nexus.
We could though

**Ben Leonard:** Wouldn't we need this if rebooting was a prerequisite to applying an update?

**Sean Klein:** So we functionally have two ways to ask the sled to reboot:

1. Ask it directly to reboot (sled agent API)
2. Ask MGS to reboot the whole sled (request to scrimlet)

Either one can work, and we'll definitely need one of the two. However, we may not want to expose either as an external API without some careful consideration.

**Comment by jgallagher** [comment]
> **Sean Klein:** So we functionally have two ways to ask the sled to reboot:
> 
> 1. Ask it directly to reboot (sled agent API)
> 2. Ask MGS to reboot the whole sled (request to scrimlet)

To expand on 2 (without commenting on whether any of this should be exposed to an operator): A gimlet's SP can control the power state of the sled, and can force a reboot by transitioning the sled from A0 to A2 and then back to A0. This can be done via (two) requests to MGS that target the sled in question; these would send commands directly to the target sled's SP. Separately, MGS exposes ignition control that allow "power reset", "power off", and "power on". These also target a sled, but the request is handled by the local sidecar SP.

**Comment by askfongjojo** [comment]
Given the latest design of automated update system and the recent discussions about sled replacement, this feature request should no longer be considered. Once we have the building blocks for evacuating all zones in a sled, we can re-consider the operator experience, e.g. provide user with a "prepare sled for removal" action which drains all services, live/dead-migrates all propolis zones, migrate/backfill all crucible downstairs. (Note: The action should not depend on the liveness of the sled- and crucible-agents as the sled might be totally unresponsive or offline.)
