### ISSUE TITLE
Tracking Issue for Service Redundancy

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2763]
It's the responsibility of Nexus to ensure that we have a sufficient number of internal services up-and-running to meet our redundancy goals. This includes the following:

- [x] Cockroachdb https://github.com/oxidecomputer/omicron/issues/727
- [x] Nexus 
- [ ] Clickhouse https://github.com/oxidecomputer/omicron/issues/2158
- [x] #3570
- [x] #3609

**Comment by askfongjojo** [comment]
The assignment was based on the FCS readiness discussion - the last mission-critical service that needs HA is crucible-pantry. I've assigned to @jmpesp the child ticket #3609 as well.

**Comment by smklein** [comment]
For reference https://github.com/oxidecomputer/omicron/pull/3610 appears to pass CI but needs more testing. Also needs validation that the **clients** of the Crucible Pantry are accessing them correctly.

For most of our redundant services, we intentionally built them such that "you can contact any one of them to get the same data" -- see, Nexus, CRDB, Clickhouse etc. This typically means we can create a DNS resolver pointing to "any of the returned SRV records for the service", and we can arbitrarily contact whoever is registered in DNS.

I'm **not** sure that's the same case for the pantry, which would make the client interaction more complicated. If the Crucible Pantry backends are not interchangeable, this will require more design work to ensure we can coordinate handoff when one of them fails (and avoid swapping between distinct pantries while they're alive, for multi-stage operations).

**Comment by jmpesp** [comment]
> I'm not sure that's the same case for the pantry, which would make the client interaction more complicated. If the Crucible Pantry backends are not interchangeable, this will require more design work to ensure we can coordinate handoff when one of them fails (and avoid swapping between distinct pantries while they're alive, for multi-stage operations).

They're not interchangeable, they have to be individually addressed.

**Comment by jmpesp** [comment]
They're not interchangeable, but I think we might be ok with the linked PR that bumps `PANTRY_COUNT`.

When importing bytes to a disk, the disk create saga will pick a pantry using the resolver and write it into the disk's db record. This selection is used for the duration of the import step: for each bulk write, and for the finalize (with the optional snapshot). It is then cleared during finalizing.

When creating a snapshot of an unattached disk, the snapshot create saga will do one of two things when told to use a pantry for the snapshot operation:

1) if the disk is already attached to a pantry, it will use that for the duration of the saga, and will not detach the disk from that pantry when done (or unwinding).
2) if the disk is not attached to a pantry, it will pick a pantry using the resolver and use that for the duration of the saga

Either way the selected pantry will be serialized into the `ssc_get_pantry_address` saga node output and does not change.

It seems like the existing code will handle multiple pantries as is. If there's a call to `get_pantry_address` where a random pantry is selected, it looks like this is used for the duration of the operation where a pantry is needed.

Unfortunately I can't test this until I get back to my house and power cycle my test machines...

**Comment by davepacheco** [comment]
In that case, it sounds like multiple instances of crucible-pantry are logically like shards, which allow us to scale it out.  In RFD 248 terminology, I think these are separate services, not multiple backends of the same service.  I think they should have separate DNS names, not one "crucible-pantry" one that resolves to non-interchangeable backends.

Is there a way to make one of the pantries highly available?

**Comment by jmpesp** [comment]
>  In RFD 248 terminology, I think these are separate services, not multiple backends of the same service. I think they should have separate DNS names, not one "crucible-pantry" one that resolves to non-interchangeable backends.

This is correct, but I disagree with the second part. As long as any code that uses a pantry understands they are separate services and therefore must pick and use only one for the duration of an operation, it is convenient to get any random address from the "crucible-pantry" list via a DNS query.

> Is there a way to make one of the pantries highly available (or does that not make sense for some reason)?

It would boil down to making the Crucible Upstairs HA, and I think that's more trouble than it's worth. We should instead lean on the unconditional takeover that an Upstairs can do based on higher generation numbers, and migrate volumes away from pantries that are unhealthy.

**Comment by davepacheco** [comment]
> > In RFD 248 terminology, I think these are separate services, not multiple backends of the same service. I think they should have separate DNS names, not one "crucible-pantry" one that resolves to non-interchangeable backends.
> 
> This is correct, but I disagree with the second part. As long as any code that uses a pantry understands they are separate services and therefore must pick and use only one for the duration of an operation, it is convenient to get any random address from the "crucible-pantry" list via a DNS query.

Yeah, I hear the desire to be able to list shards (for lack of a better term here).  I am not sure how to do that idiomatically in DNS.  I think you want to list a type of record that itself resolves to SRV records?  The main thing I'm worried about is that if we present all these as SRV/A/AAAA records under one name, people _will_ assume they're interchangeable because that's the pattern we've adopted everywhere else (and I think that pattern exists outside of Oxide, which is why we did it).  I feel like this confusion has already happened in the discussions we've had in the last week about whether it was safe and correct to deploy more instances of crucible-pantry to achieve higher availability.  A secondary issue with this is that it seems like it'll make it harder to build tooling around internal DNS because all of it will have to know about this special case.  But I don't have a better idea either.

Thinking out loud: I wonder how this is different from sled agent.  The Sled Agents together make up a fleet of related but non-interchangeable instances.  How do clients figure out which one they need to talk to?  If you've got an instance already, there's exactly one sled agent that's correct and you have to look it up and use that one.  If you're provisioning a new instance, you can pick from a bunch of different sled agents.  But the choice is much more complicated than "pick one of the N that might exist in DNS".  Really only Nexus has to make this choice, and the choice could be fairly sophisticated (based on the up-state of each one, how much space is on it, some bin packing policies, etc.).  I guess that's not really true of the pantry?

**Comment by jclulow** [comment]
Could you publish the record with a name like `pantry-discovery` that makes it clear it's something separate from the actual service name you'd usually use to talk once you've picked one?

**Comment by davepacheco** [comment]
> Could you publish the record with a name like `pantry-discovery` that makes it clear it's something separate from the actual service name you'd usually use to talk once you've picked one?

I like that idea.  But what would you put under it?  SRV records with dummy port/priority/etc. but whose target is the actual name whose SRV you're supposed to look up?  Or would it be the union of SRV records under all the more specific names?

**Comment by jclulow** [comment]
Conceptually I think what you want is basically like a (potentially multivalued) CNAME that points to all the candidate SRVs yeah.  Effectively a name for the _class_ of thing, which you use to select one concrete instance of that thing and then stick with the instance-specific name thereafter for that session.

**Comment by askfongjojo** [comment]
Removed milestone and unassigned it as the remaining task (Clickhouse) is already assigned and tagged to 1.0.2.

**Comment by davepacheco** [comment]
It looks like this ticket covers work that's all been done.  Is it time to close it?

**Comment by smklein** [comment]
I don't think the Clickhouse pieces have finished yet -- there's some difficulty in transitioning from single node to multi-node clickhouse -- but otherwise, we are done.

That said, the clickhouse issues are more narrow, so we can probably discuss them outside this issue.
