### ISSUE TITLE
omicron-dev should run simulated sled agent with `SimMode::Auto`

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#2810]
The `omicron-dev` tool runs an in-process simulated sled agent that shares a configuration with the integration tests' configuration: https://github.com/oxidecomputer/omicron/blob/5d39727039cca86a7fef48d35f3675187386c333/nexus/test-utils/src/lib.rs#L220-L249

This configuration specifies that the simulation should run in Explicit mode. In this mode, simulated objects like instances need to be poked explicitly (by calling the right simulated agent endpoint) to transition between states. For local development purposes, where there's a user playing around with the simulation instead of a test that's poking objects to generate state transitions, it would be nice if the simulation ran in Auto mode to match `sled-agent-sim`'s default behavior.

**Comment by davepacheco** [comment]
Nice catch.  Sorry for missing this and thanks for the report.
