### ISSUE TITLE
Instance Deletion saga looks destructive, even if instance should not be deleted

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2842]
Let's suppose we have an instance in a state where it *should not* be deleted. Specifically, a case where `sid_delete_instance_record` , calling `project_delete_instance`, observes that the instance cannot be running.

This should be reproducible in a scenario where the instance is "running" - it's not an `ok_to_delete_instance_state`:

https://github.com/oxidecomputer/omicron/blob/e4a5dd0029946c0f7f56f4858475c2935e0eb9a9/nexus/db-queries/src/db/datastore/instance.rs#L228

If we execute the instance delete saga on this instance, we'll execute the following actions:

https://github.com/oxidecomputer/omicron/blob/e4a5dd0029946c0f7f56f4858475c2935e0eb9a9/nexus/src/app/sagas/instance_delete.rs#L69-L82

Here's what will happen:

- The V2P mappings will be deleted
- The ASIC configuration will be deleted
- The instance record *cannot* be deleted, because we aren't in a valid state. The saga will start unwinding from `instance_delete_record_action`.
- On the unwind path, the V2P mappings will *try* to be re-created via `sid_v2p_ensure_undo`

This is problematic for a couple reasons:

1. The (temporary) destruction of the V2P mappings are an observable side-effect of the failed instance deletion
2. As far as I can tell, the `sid_delete_network_config` function will delete all NAT mappings, and this destructive action will not be "undone"

This seems like it'll degrade the network functionality of the instance, even though it remains running.

It seems like we should delete the instance record **first**, before proceeding with the de-allocation of resources. This will validate the state of the instance before we actually perform destructive operations.

FYI @jmpesp , @internet-diglett .

**Comment by internet-diglett** [comment]
> As far as I can tell, the sid_delete_network_config function will delete all NAT mappings, and this destructive action will not be "undone"

Yes, this is the case. I'll try reordering the saga nodes and see if it's a trivial fix.

**Comment by internet-diglett** [comment]
```
{"msg":"saga log event","v":0,"name":"test_actions_succeed_idempotently","level":20,"time":"2023-04-14T18:51:21.39154300
7Z","hostname":"workstation-1","pid":21150,"sec_id":"99aa6991-51a2-4eba-a812-ade594ade2bf","component":"SEC","component"
:"nexus","component":"ServerContext","name":"99aa6991-51a2-4eba-a812-ade594ade2bf","new_state":"N002 failed"}
{"msg":"recording saga event","v":0,"name":"test_actions_succeed_idempotently","level":20,"time":"2023-04-14T18:51:21.39
1578685Z","hostname":"workstation-1","pid":21150,"component":"SecStore","component":"nexus","component":"ServerContext",
"name":"99aa6991-51a2-4eba-a812-ade594ade2bf","event_type":"Failed(ActionFailed { source_error: Object {\"ObjectNotFound
\": Object {\"lookup_type\": Object {\"ById\": String(\"818d8bec-ec26-461d-be6f-fb93dd5658cc\")}, \"type_name\": String(
\"instance\")}} })","node_id":"2","saga_id":"c1bacde0-249d-43c9-a470-341b9a216bbf"}
```

Looks like there are some record lookups that get broken if we perform `instance_delete_record_action()` first. 

It looks like deleting the v2p mappings depends on the record being present?

https://github.com/oxidecomputer/omicron/blob/e4a5dd0029946c0f7f56f4858475c2935e0eb9a9/nexus/src/app/sled.rs#L388-L407

Admittedly I could be misunderstanding this, as I'm still not 100% sure on how some of our queries work.

**Comment by jmpesp** [comment]
> It looks like deleting the v2p mappings depends on the instance record being present?

Yeah, this is definitely true - for the reason you posted, and for calling `derive_guest_network_interface_info`.

For this to work, we'd have to cache the existing V2P entries (probably as the output of a saga node) before deleting the existing record. Problem with that is stale information (and this problem probably exists today) - nothing's locking the instance record so it would be possible to add or remove a network interface, and render that cached information stale.

**Comment by smklein** [comment]
Ah, I was potentially going to suggest the generation number here, but that sounds like a bad fit. Network interfaces can be added to stopped instances, right?
