### ISSUE TITLE
Image promote does not check for duplicate names

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#2895]
I was able to promote an image with the same name as another image that exists at the silo-level. It should probably complain about name duplication.

**Comment by zephraph** [comment]
I'm surprised about this given the [unique index constraint on silo_id, project_id, and name](https://github.com/oxidecomputer/omicron/blob/81deb439466e42c9da9e003fdcea5435f9d01324/common/src/sql/dbinit.sql#L1035-L1040). @davepacheco shouldn't an update fail if it results in a duplicate in that index?

**Comment by davepacheco** [comment]
I suspect what's going on is that you've got two items in the index both having `(silo_id, NULL project_id, name)`, but the two NULL values act as though they're distinct.  Check this out:
https://www.cockroachlabs.com/docs/stable/null-handling.html#nulls-and-unique-constraints

It may be clearer to have two different partial indexes, one for project-level uniqueness and one for silo-level uniqueness.  I'm not sure but I think it's a good idea to leave NULL values out of indexes.
