### ISSUE TITLE
Be more resilient during service provisioning.

### ISSUE THREAD

**Issue by luqmana** [oxidecomputer/omicron#2933]
Follow up to #2857.

To give services external access, we make calls to dendrite to configure the switch. But those are stateful meaning a failure part-way through leads to leaking those entries. Ideally we'd use a saga to handle rollbacking on failures.

**Comment by davepacheco** [comment]
@internet-diglett is this issue affected by your recent RPW work?

**Comment by internet-diglett** [comment]
@davepacheco sorry for the delay in responding to this. The NAT entries in #2857 are all service zone nat entries, so the RPW work performed in #4857 will cover proper reconciliation of these entries (deleting them when they are no longer required and ensuring that they are re-added across crashes, restarts, etc).

**Comment by davepacheco** [comment]
Based on that last comment I think this is resolved by #4857.
