### ISSUE TITLE
Nexus should pass request for "all services on a sled" as a single endpoint with a generation number

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2977]
https://github.com/oxidecomputer/omicron/pull/2972#issuecomment-1530453752 for some context, but it basically would let the "local ledger of services" on a sled be more cleanly a cache of data from CRDB.

**Comment by davepacheco** [comment]
@smklein This was done already, right?

**Comment by smklein** [comment]
Same as https://github.com/oxidecomputer/omicron/issues/2978#issuecomment-1711016927

**Comment by davepacheco** [comment]
This behavior was folded into #4466.
