### ISSUE TITLE
Nexus should pass request for "all datasets on a sled" as a single endpoint with a generation number

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2978]
https://github.com/oxidecomputer/omicron/pull/2972#issuecomment-1530453752 for some context, but it basically would let the "local ledger of services" on a sled be more cleanly a cache of data from CRDB.

**Comment by davepacheco** [comment]
I think this is obviated now that datasets and services are the same API and we already have #2977.  Is that right @smklein?

**Comment by smklein** [comment]
Unfortunately still missing a generation number

**Comment by davepacheco** [comment]
But is it now covered by #2977 since datasets and services are the same endpoint now?

**Comment by davepacheco** [comment]
I think this is obviated by #4466.
