### ISSUE TITLE
`Image` should have a field that lets you know if an image has been promoted or not

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#3084]
The current `Image` struct does not let you know if an image is promoted or not:

```rust
    /// Client view of images
    #[derive(Clone, Debug, Deserialize, Serialize, schemars :: JsonSchema)]
    pub struct Image {
        /// size of blocks in bytes
        pub block_size: ByteCount,
        /// human-readable free-form text about a resource
        pub description: String,
        /// Hash of the image contents, if applicable
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub digest: Option<Digest>,
        /// unique, immutable, system-controlled identifier for each resource
        pub id: uuid::Uuid,
        /// unique, mutable, user-controlled identifier for each resource
        pub name: Name,
        /// The family of the operating system like Debian, Ubuntu, etc.
        pub os: String,
        /// ID of the parent project if the image is a project image
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub project_id: Option<uuid::Uuid>,
        /// total size in bytes
        pub size: ByteCount,
        /// timestamp when this resource was created
        pub time_created: chrono::DateTime<chrono::offset::Utc>,
        /// timestamp when this resource was last modified
        pub time_modified: chrono::DateTime<chrono::offset::Utc>,
        /// URL source of this image, if any
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub url: Option<String>,
        /// Version of the operating system
        pub version: String,
    }
```

Would be good to add a field like the following to the `Image` struct:

```rust
/// whether an image is visible to all projects within a silo
pub silo_visibility: bool,
```

**Comment by david-crespo** [comment]
The absence of the project ID indicates that it is promoted. However, I concede that is very indirect. We could add a boolean field like you suggest.

**Comment by karencfv** [comment]
https://github.com/oxidecomputer/omicron/pull/3080 threw me a lifeline for the Terraform provider, I don't need this feature anymore. I'll close as we have way too many things to do. If anyone thinks this would be a nice to have please feel free to open it again!

**Comment by zephraph** [comment]
Sorry I missed this! "Promotion" is just the term we've used to describe moving an image from a project to silo. An image can be created directly in a silo as well. As @david-crespo mentioned, the presence of `project_id` is the key here. I did try other alternatives for representing the state of the image, but there's not a whole lot of good options. We have to reuse the same type given that there's only a single endpoint. 

It sounds like we need to do some better documentation here. I can take that on.

**Comment by karencfv** [comment]
Aaaahhhh gotcha, I previously believed you __had__ to create the image in a project first. I'll update the TF provider schema with this new information

**Comment by david-crespo** [comment]
You do have to create it in the project, it’s just that once you promote it, it loses its project association. I could certainly imagine adding the ability to make a silo image directly, but we designed around a workflow where operators would want to test an image before making ot visible to everyone.

**Comment by karencfv** [comment]
> An image can be created directly in a silo as well.

I'm confused now

**Comment by david-crespo** [comment]
Oh sorry, Justin would def know better than I do, he wrote it. I guess if you leave off the project ID it will create it in the silo.

**Comment by zephraph** [comment]
Yes, sorry for the confusion here. Originally the plan was to _only_ allow image creation in the project and the promotion flow would be how to move it globally. It's still an option for us to enforce that workflow, but given how the API came out it seemed reasonable to me just to allow either case. If we decide we _don't_ want to support direct creation of the image in the silo, that's easy enough to do as well. Right now though, as implemented, both are supported while the promotion process is probably more recommended.

**Comment by karencfv** [comment]
> If we decide we don't want to support direct creation of the image in the silo, that's easy enough to do as well

I 100% vote to keep direct creation of the image in the silo. The previous restriction made for a wacky TF provider that had to have warning bells 😄
