### ISSUE TITLE
wicket logs / EventReports after running multiple mupdates are enormous

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3102]
Today when trying to update 6 gimlets in the dogfood rack simultaneously, I noticed a few oddities:

* After it had been running for a while, `wicket` became sluggish
* Within the switch zone, `/tmp/wicket.log` was several gigabytes, and growing quickly (~ 1GiB/minute, eyeballing it)
* From skimming the logs, the vast majority was debug prints of `EventReports`, many of which were extremely large (75,000+ lines), repeated very frequently

I think there are at least two things to address here:

1. Stop debug logging the full event reports
2. Why are the event reports so large?

For 2, the issue might be [where we generate the report](https://github.com/oxidecomputer/omicron/blob/857a9b95a83e7c833822fc29e3b89c4d1be41386/installinator/src/reporter.rs#L92); should that be `generate_report_since(self.last_reported)`?

**Comment by davepacheco** [comment]
Should we log these to disk rather than an in-memory filesystem?  I'm not sure how the cap on /tmp works but if it lets you use all of the system's physical memory, that would explain the sluggishness (but that would reflect a pretty serious issue, I think).  And/or maybe we don't have a swap cap on this zone?

**Comment by jgallagher** [comment]
I suspect the sluggishness was just in all the debug formatting? It was debug-formatting several hundred thousand lines of stuff every second; even if there was no real I/O that can't be free.
