### ISSUE TITLE
Failing to boot Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/omicron#3111]
On dogfood, tried to create a Ubuntu instance from the web console and it fails to boot — but says `Running`.

Tried a couple of images, both [Ubuntu 20.04.6 LTS (Focal Fossa)](https://releases.ubuntu.com/focal), one regular and one mini.

```
BdsDxe: failed to load Boot0001 "UEFI " from PciRoot(0x0)/Pci(0x10,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00): Not Found
BdsDxe: failed to load Boot0002 "UEFI Non-Block Boot Device" from PciRoot(0x0)/Pci(0x18,0x0): Not Found

>>Start PXE over IPv4.
```

```
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):F1:;BLK1:
          PciRoot(0x0)/Pci(0x18,0x0)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x10,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
Press ESC in 5 seconds to skip startup.nsh or any other key to continue.
Shell> 
```

@citrus-it  had a poke around in the serial console. The `cloud-init` disk seemed to work ok but not BLK0.

**Comment by leftwo** [comment]
We should be sure to document this procedure somewhere though, so other users don't encounter the same issue.
