### ISSUE TITLE
Fetch propolis image from boot disk or install it to /opt/oxide on ramdisk

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#3166]
After mupdating and installinating a rack, we wound up with sled agents attempting to run propolis instance zones from a zone image in `/opt/oxide`.

https://github.com/oxidecomputer/omicron/blob/86676b9dafc67596f1ccd50f921f2288fcb14684/sled-agent/src/instance.rs#L791-L813

However from the install, the propolis zone image was on the M.2 boot disk and not in `/opt/oxide`. This resulted in all instances failing to launch. So we either need to update the code above to handle the propolis zone image being on the boot disk (similar to service zones), or update the ramdisk to contain the propolis zone in `/opt/oxide`.

**Comment by jgallagher** [comment]
> So we either need to update the code above to handle the propolis zone image being on the boot disk (similar to service zones), or update the ramdisk to contain the propolis zone in /opt/oxide.

I believe the right answer is the latter. For the mupdate we did this week, I built the ramdisk by hand and overlaid the contents of the switch zone into the ramdisk via `helios-build -P ...`. Before we do the next mupdate, we should fix CI to include the switch zone and propolis. (I'll assign this to myself and take care of it on Monday unless someone beats me to it.)
