### ISSUE TITLE
Commands sled-agent runs through zlogin are subject to shell expansion

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3216]
While investigating why dendrite didn't see a SIGUSR1 when it should've in #3199, @bnaecker noticed this oddity in sled-agent's logs:

```
02:15:10.006Z WARN SledAgent: Failed to activate switch: Failed to issue SMF command: Failed to do 'del config/address smf property value' by running command in zone: Error running command in zone 'oxz_switch': Command [/usr/sbin/zlogin oxz_switch /usr/sbin/svccfg -s svc:/system/illumos/dendrite delpropvalue config/address *] executed and failed with status: exit status: 1  stdout:   stderr: svccfg: Syntax error.
    sled_id = 96c409e3-a150-46de-9915-25b839ba2508
```

On its surface this doesn't make any sense:

```
/usr/sbin/svccfg -s svc:/system/illumos/dendrite delpropvalue config/address *
```

is perfectly valid syntax, and we use the exact same wrapper to delete properties when configuring MGS. [Our SMF wrapper uses std::process::Command](https://github.com/oxidecomputer/omicron/blob/ea9f70a3bd9300bc1adfecac6db1e159613039a9/illumos-utils/src/running_zone.rs#L162-L170), so we should not (ominous sounds) be subject to shell expansion.

However, we _are_ getting shell expansion by virtue of the `zlogin`. Reproducing is trivial outside of sled-agent:

```
BRM44220001 # /usr/sbin/zlogin oxz_switch ls -l
total 2
-rw-r--r--   1 root     root           0 Dec 27 18:00 bar
-rw-r--r--   1 root     root           0 Dec 27 18:00 foo
BRM44220001 # echo '*'
*
BRM44220001 # /usr/sbin/zlogin oxz_switch echo '*'
bar foo
```

This also explains the syntax error we see from svccfg, if there are any files in root's home directory:

```
BRM44220001 # /usr/sbin/zlogin oxz_switch /usr/sbin/svccfg -s svc:/system/illumos/dendrite delpropvalue config/address '*'
svccfg: Syntax error.
```

**Comment by jgallagher** [comment]
FWIW these work as expected, but yuck:

```
BRM44220001 # /usr/sbin/zlogin oxz_switch echo "'*'"
*
BRM44220001 # /usr/sbin/zlogin oxz_switch echo '\*'
*
```

**Comment by bnaecker** [comment]
@citrus-it recommended fetching all values and then deleting them in turn. Definitely safer to disallow globs, though more work.

**Comment by jclulow** [comment]
I suspect another thing we could do is arrange for `zone_enter()` to be called in the forked child using the pre-exec hook for `Command` so that the child process we then exec would actually be run in the context of the zone.  This is basically what `zlogin` is doing for us anyway, and would mean there was no shell interposition.

**Comment by bnaecker** [comment]
Thanks @jclulow that's a great place to start.

**Comment by citrus-it** [comment]
Robert mentioned that there is an environment variable to control the path to the door that we could already use to work around this quickly:

```
BRM42220014 # LIBSCF_DOORPATH=/zone/oxz_switch/root/etc/svc/volatile/repository_door \
    svccfg -s dendrite listprop config/address
config/address  astring  "[fd00:1122:3344:103::2]:12224" "[::1]:12224"
```

**Comment by jclulow** [comment]
Does the code for using an alternative door path correctly avoid following a potentially malicious symlink inside the zone?

**Comment by citrus-it** [comment]
> Does the code for using an alternative door path correctly avoid following a potentially malicious symlink inside the zone?

Nope, and that is https://www.illumos.org/issues/15727
