### ISSUE TITLE
Handle database records on re-assignment of a metric producer to an oximeter collector

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#323]
The method `omicron_nexus::db::Datastore::producer_endpoint_create` inserts a record into the `omicron.MetricProducer` table, with information about the producer's HTTP endpoint for collecting data, and also the `oximeter` instance to which the producer is assigned. It's possible that this method is called when a record for that producer already exists. For example, if a producer restarts, it'll re-register with Nexus. This method currently updates the endpoint information, but does not handle re-assignment of the producer to a collector.

At this point, there's just a single `oximeter` instance, so there is no case in which a re-registered producer is assigned to a new `oximeter`. But there _will be_ more than on `oximeter` collector in the real system. In this case, the `producer_endpoint_create` method and surrounding code needs to be improved.

There are a few things required for this to work:

- [] The endpoint-create function should be updated to check if the collector ID for the new assignment is the same (yay) as the original. If it's not the same, it should update it.
- [] If the collector ID is different, Nexus then needs to:
    - [] Return the previous ID
    - [] Notify the previous collector to stop collecting from that producer. This interface does not yet exist in `oximeter`. We'd need to add something like a `DELETE /producers/{producer_id}` endpoint, and implement that. Note that the implementation should be pretty easy -- `oximeter` [starts a `tokio::task`](https://github.com/oxidecomputer/omicron/blob/79caf6e15b22e3cfb11e093fe37d03fa55e1a614/oximeter/collector/src/lib.rs#L323) for each producer to collect from, and has a channel for sending messages to that task. There's [already an variant](https://github.com/oxidecomputer/omicron/blob/79caf6e15b22e3cfb11e093fe37d03fa55e1a614/oximeter/collector/src/lib.rs#L49) of the message enum to notify the task to exit, that just needs to be hooked up to the API endpoint.
    - [] Notify the new collector as usual

It's not clear how to handle the case where the old collector either can't be reached or there's a period of time where they're both collecting data. The latter situation isn't the worst thing in the world, since it means that we'll "just" have more metric data than was intended for some time.

Note that resolving this will be required for any kind of load-balancing that Nexus may decide to do, redistributing producers to collectors.

**Comment by askfongjojo** [comment]
@jgallagher - Can this be considered complete with the work you've done?

**Comment by jgallagher** [comment]
No, not really. The reconfigurator oximeter work hasn't fully landed, but even once it has, we're still only going to be handling expungement of oximeter -> a new oximeter takes its place; there are still issues (described above) that will need to be addressed to support multiple oximeter instances.

**Comment by jgallagher** [comment]
Spoke to soon! We can consider this done with #6759, which came out of feedback from Ben reviewing the reconfigurator/oximeter work.
