### ISSUE TITLE
sled agent and Nexus frequently flatten errors into 500 Internal Server Error

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#3238]
Sled agent has a relatively rich set of internal error types, but at the Dropshot HTTP error boundary, it converts almost all of them to 500 errors:

https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/sled-agent/src/sled_agent.rs#L102-L137

This makes it hard for callers to reason about the cause or permanence of any of these errors. This was a pebble in the shoe of PR #2892 and is coming up again in #3230 (sled agent is making a call to Nexus whose response depends in part on calls back down into sled agent, and there's no way to be sure about the permanence of any errors returned from Nexus in that path because all errors are getting flattened into a single error code).

There are similar paths through Nexus that flatten errors this way that the fix for #3230 will have to take into account:

- Updating instance state can update the instance's Dendrite configuration: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/nexus/src/app/instance.rs#L1138-L1144
- `instance_ensure_dpd_config` calls `dpd_client.ensure_nat_entry` and maps all errors to 500s: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/nexus/src/app/instance.rs#L1243-L1259
- `ensure_nat_entry` calls Dendrite daemon routines that can (I presume) produce transient failures (e.g. transient communication failures), e.g.: https://github.com/oxidecomputer/omicron/blob/cab09253e6e6e27761d1ef99f8087f86ccad2e8b/dpd-client/src/lib.rs#L111-L127

Revisiting absolutely every single error conversion in sled agent and Nexus all at once is probably a non-starter, but we can likely start by improving sled agent's internal-error-to-Dropshot-error conversion and look for opportunities to remove other error-flattening cases as they arise.

**Comment by gjcolombo** [comment]
#3334 is a first step toward addressing this issue.

**Comment by hawkw** [comment]
Looking closer at this, it looks like a lot of the work here has been addressed in #3334 and #4682. It's not particularly clear what else is left to do in _this_ issue on the `nexus/`sled-agent` side. Perhaps @gjcolombo will have more input into this when he's back from leave.

We do need to get propolis#649 merged, though, which is _sort of_ related...

**Comment by hawkw** [comment]
It looks like sled-agent is still not _quite_ doing the right thing, here. If a sled-agent operation on behalf of Nexus encounters a client error from Propolis, it will now correctly forward that error code to Nexus...but, _Nexus_ only moves instances to `Failed` in the face of sled-agent's `410 NO_SUCH_INSTANCE`, and _not_  [if it sees the `NoInstance` error code from Propolis](https://github.com/oxidecomputer/propolis/blob/516dabe473cecdc3baea1db98a80441968c144cf/crates/propolis-api-types/src/lib.rs#L434-L441), which means we're not really handling the "propolis restarted" case correctly in Nexus, and restarted propoli still won't be moved to `Failed`. Agh.

Furthermore, a complete solution to this would require more than just having Nexus know about the Propolis `NoInstance` error (or sled-agent eat it and return its equivalent `410 NO_SUCH_INSTANCE`). Instead, sled-agent needs to also know that that error means the VMM is way gone and take steps to take a zone bundle and then destroy the zone. So there's some more stuff we kinda forgot to do here... :sweat-smile:
