### ISSUE TITLE
do a daily sync of maghemite and dendrite in an automated PR

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/omicron#3259]
It would be useful to have automatic updates of dendrite and maghemite along the lines of this sort of PR:

- https://github.com/oxidecomputer/omicron/pull/2941
- https://github.com/oxidecomputer/omicron/pull/2197

I'd suggest we...
1. do this daily
2. do it at a time when CI use is relatively light (3am PT?)

cc @augustuswm who built some similar-ish logic in the https://github.com/oxidecomputer/oxide.rs repo
cc @rcgoodfellow, @Nieuwejaar 

Note would probably be useful for propolis and crucible as well, but perhaps we can start here and figure out the other dependencies.

**Comment by rcgoodfellow** [comment]
Latest commit from main is what we're doing currently.
