### ISSUE TITLE
Dynamically assign boundary services address

### ISSUE THREAD

**Issue by internet-diglett** [oxidecomputer/omicron#3278]
Currently the boundary services address is hard-coded to be assigned to the first switch. Once we enable multi-switch capability, we will need to be able to determine which switch should get the address based off of the configuration.

**Comment by internet-diglett** [comment]
Ref: https://github.com/oxidecomputer/omicron/pull/3262#discussion_r1245598673

Currently the strategy being implemented in #3262 is to create NAT entries on switches that have external networking configured.

**Comment by rcgoodfellow** [comment]
As of #3859 boundary services underlay addresses are no longer managed by Omicron. They are transient dynamic addresses that are managed by `mgd` with a lifetime that is tied to the switch zone lifetime they are assigned to. More details are in [RFD 404 Section 2.1](https://rfd.shared.oxide.computer/rfd/0404#_ipv6_unique_local_addressing).
