### ISSUE TITLE
Mupdate: Ability to deploy the "pilot" tool 

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3322]
As of this writing, the tool is intended to remain on the rack as a customer support tool. While it can be installed manually at manufacturing time, it needs to be installable/updatable by the update programs like other software in the switch zone.

Dependency: The tool needs to be productized first and the work required is tracked here: https://github.com/oxidecomputer/compliance-pilot/issues/17.

**Comment by jgallagher** [comment]
>  it needs to be installable/updatable by the update programs like other software in the switch zone.

Just to clarify - the switch zone is built as part of the OS ramdisk. Until that changes (maybe never?), updating anything in the switch zone means updating the OS, and anything we need added to the switch zone needs to be included in the switch zone tarball that CI includes in the OS ramdisk.

**Comment by jclulow** [comment]
I think probably we'd just include `pilot` in the base ramdisk in `/usr/bin` and it will then also be accessible from inside the switch zone as required.

**Comment by askfongjojo** [comment]
@smklein - You mentioned that you saw `pilot` already being included in the host OS image. Please confirm and we can perhaps mark this ticket (and https://github.com/oxidecomputer/pilot/issues/17) closed. Thanks!
