### ISSUE TITLE
want mechanism to preserve Propolis logs before destroying Propolis zones

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#3347]
I couldn't find anything on point searching for open issues with "propolis" in them; hopefully I didn't overlook anything (though likely as not I did).

Sled agent tears down Propolis zones whenever a Propolis reports that its VMM has been destroyed or has failed. It (sled agent) also destroys them when rolling back an instance creation or migration saga that created such a zone. This is annoying when trying to analyze Propolis issues postmortem. It would be nice for sled agent to have a mechanism to preserve these logs (space and retention policies permitting) before tearing down these zones.

**Comment by bnaecker** [comment]
Related :) https://github.com/oxidecomputer/omicron/issues/1598

**Comment by gjcolombo** [comment]
Duplicate of #1598.
