### ISSUE TITLE
proxy_instance_serial_ws() uses `select!` with non-cancel-safe future(s)

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3356]
In `proxy_instance_serial_ws()`, we [construct four futures](https://github.com/oxidecomputer/omicron/blob/73545a9e601c33f347c80c1c4aaa2a107599660d/nexus/src/app/instance.rs#L1423-L1458) over which we will `tokio::select!`. In any given loop iteration, at least two of the futures are instances of `Fuse::terminated()` (and therefore ignored by `select!`). The possible combinations of non-`Fuse::terminated()` futures are:

1. `nexus_read` (a [`StreamExt::next()`](https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.next) future) and `nexus_write`(a [`SinkExt::send()`](https://docs.rs/futures-util/latest/futures_util/sink/trait.SinkExt.html#method.send) future)
2. `nexus_read` and `propolis_read` (a future from [`InstanceSerialConsoleHelper::recv()`](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/lib/propolis-client/src/lib.rs#L124) in propolis)
3. `propolis_write` (a future from [`support::send`](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/lib/propolis-client/src/lib.rs#L112-L114) in propolis which is a wrapper around `SinkExt::send()`) alone
4. `propolis_write` and `nexus_write`

Case 3 is fine because there is only one possible future for `select!` to choose, so there is no possibility for cancellation. But in the other three cases, `select!` will cancel one of the two futures once it chooses one. In terms of cancel safety, none of these futures is explicitly documented; however:

* I believe (hope?) that `StreamExt::next()` is cancel safe, because the equivalent method in [tokio-stream's StreamExt](https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#cancel-safety) is explicitly documented as cancel safe.
* I believe `SinkExt::send()` is _not_ cancel safe: if `select!`ing over a `SinkExt::send()` future and a different arm is chosen, the item being sent to the sink will be lost. ([A reproducer](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2608a62c8695fbcfbb22d1856bfe930a); I'll also file an issue on `futures-util` to confirm / try to get it documented. EDIT: filed https://github.com/rust-lang/futures-rs/issues/2754)
* I'm not sure whether `InstanceSerialConsoleHelper::recv()` is cancel safe, but based on it containing multiple `.await` points I suspect it is not: if an item is [pulled out of `self.ws_stream`](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/lib/propolis-client/src/lib.rs#L129) and the future is dropped at a later await point, I believe the item will be lost.

I'm not sure at the moment how to address this; I'm just skimming through omicron's `select!`s looking for suspicious cancel safety issues. CC @lifning

**Comment by sunshowers** [comment]
> I'm not sure whether InstanceSerialConsoleHelper::recv() is cancel safe, but based on it containing multiple .await points I suspect it is not: if an item is [pulled out of self.ws_stream](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/lib/propolis-client/src/lib.rs#L129) and the future is dropped at a later await point, I believe the item will be lost.

Indeed `InstanceSerialConsoleHelper::recv` wasn't cancel-safe. https://github.com/oxidecomputer/propolis/pull/435 addresses that, and once it is ported over it should be cancel-safe.

**Comment by sunshowers** [comment]
> I believe SinkExt::send() is not cancel safe: if select!ing over a SinkExt::send() future and a different arm is chosen, the item being sent to the sink will be lost. ([A reproducer](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2608a62c8695fbcfbb22d1856bfe930a); I'll also file an issue on futures-util to confirm / try to get it documented. EDIT: filed https://github.com/rust-lang/futures-rs/issues/2754)

I think the best solution here is to define a version of `SinkExt::send` that's cancel-safe. I've outlined a proposal here: https://github.com/rust-lang/futures-rs/issues/2754#issuecomment-1594049495

**Comment by sunshowers** [comment]
Current status:

* [ ] `propolis_conn.recv()` will become cancel-safe once #3391 lands.
* [ ] I'm actively working on making the `send` branches cancel-safe via https://github.com/oxidecomputer/cancel-safe-futures/

**Comment by sunshowers** [comment]
The remaining uses have been tackled in #3411. We should be good with respect to cancel safety now.
