### ISSUE TITLE
Tracking Issue | OpenSSL update to 3.0 as 1.x is EOS 9/11

### ISSUE THREAD

**Issue by morlandi7** [oxidecomputer/omicron#3358]
Putting this in omicron for now as it's repo is part of the milestone collector and not excluded on the MVP board. Open to a better place.

OpenSSL is [ending support for 1.x on Sept 11 2023](https://www.openssl.org/source/). We should upgrade to the current 3.0 LTS version.

- [x] https://github.com/oxidecomputer/helios/issues/90
- [x] Control Plane

**Comment by citrus-it** [comment]
> We should upgrade to the current 3.1 version.

We should probably upgrade to 3.0 as that is a long-term-support (LTS) version which will outlive 3.1

**Comment by askfongjojo** [comment]
There is a separate version used for CLI. (not updated automatically by dependabot because it's a transitive dependency). Other than the CLI,  there doesn't appear to be anything else in CP that uses its own openssl.
