### ISSUE TITLE
Firewall rule validation and default rules should treat protocol and host filter as required fields

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3373]
I created a new VPC in my project and some instances with external IP on the `default` subnet that came with it. After that, I did the following:
- disabled the default inbound icmp rule that came with the vpc -> couldn't ping the instance external IP any more from my workstation (this is as expected)
- enabled the inbound icmp rule -> still couldn't ping my instances (this is incorrect)
- updated the priority to 1 -> still couldn't ping
- disabled the default inbound ssh rule -> couldn't ssh the instance any more
- enabled the inbound ssh rule -> similar to the icmp rule, re-enabling the rule still didn't allow ssh (this is incorrect)

I checked the sled-agent log for the sled that hosts the instance. It is getting the fw rule update:
```
    rules = [VpcFirewallRule { status: Enabled, direction: Inbound, targets: [NetworkInterface { id: bcf01d5c-20da-4cf0-8ae0-a3a2932d4fdd, kind: Instance { id: 9f956578-d8ad-4144-a957-2af23d10e9f6 }, name: Name("secure0"), ip: 172.30.0.198, mac: MacAddr(MacAddr6([168, 64, 37, 247, 104, 130])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }, NetworkInterface { id: c79e4923-a752-4e2e-afd8-7c43ca01bc72, kind: Instance { id: a8448e6e-06a5-4fb0-a76b-1225b5a3b8ea }, name: Name("secure0"), ip: 172.30.0.199, mac: MacAddr(MacAddr6([168, 64, 37, 243, 25, 55])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }], filter_hosts: Some([]), filter_ports: Some([]), filter_protocols: Some([Icmp]), action: Allow, priority: VpcFirewallRulePriority(1) }, VpcFirewallRule { status: Enabled, direction: Inbound, targets: [NetworkInterface { id: bcf01d5c-20da-4cf0-8ae0-a3a2932d4fdd, kind: Instance { id: 9f956578-d8ad-4144-a957-2af23d10e9f6 }, name: Name("secure0"), ip: 172.30.0.198, mac: MacAddr(MacAddr6([168, 64, 37, 247, 104, 130])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }, NetworkInterface { id: c79e4923-a752-4e2e-afd8-7c43ca01bc72, kind: Instance { id: a8448e6e-06a5-4fb0-a76b-1225b5a3b8ea }, name: Name("secure0"), ip: 172.30.0.199, mac: MacAddr(MacAddr6([168, 64, 37, 243, 25, 55])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }], filter_hosts: Some([Vpc(Vni(11346697)), Vpc(Vni(11346697))]), filter_ports: Some([]), filter_protocols: Some([]), action: Allow, priority: VpcFirewallRulePriority(65534) }, VpcFirewallRule { status: Enabled, direction: Inbound, targets: [NetworkInterface { id: bcf01d5c-20da-4cf0-8ae0-a3a2932d4fdd, kind: Instance { id: 9f956578-d8ad-4144-a957-2af23d10e9f6 }, name: Name("secure0"), ip: 172.30.0.198, mac: MacAddr(MacAddr6([168, 64, 37, 247, 104, 130])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }, NetworkInterface { id: c79e4923-a752-4e2e-afd8-7c43ca01bc72, kind: Instance { id: a8448e6e-06a5-4fb0-a76b-1225b5a3b8ea }, name: Name("secure0"), ip: 172.30.0.199, mac: MacAddr(MacAddr6([168, 64, 37, 243, 25, 55])), subnet: V4(Ipv4Net(Ipv4Network { addr: 172.30.0.0, prefix: 22 })), vni: Vni(11346697), primary: true, slot: 0 }], filter_hosts: Some([]), filter_ports: Some([L4PortRange { first: L4Port(22), last: L4Port(22) }]), filter_protocols: Some([Tcp]), action: Allow, priority: VpcFirewallRulePriority(65534) }]
    vni = Vni(11346697)
22:18:19.599Z INFO SledAgent (PortManager): Setting OPTE firewall rules
    port = "opte2"
    rules = []
22:18:19.600Z INFO SledAgent (dropshot (SledAgent)): request completed
    local_addr = [fd00:1122:3344:104::1]:12345
    method = PUT
    remote_addr = [fd00:1122:3344:102::4]:62794
    req_id = 52affe85-1841-492c-96bd-9f01a2f3d1e8
    response_code = 204
    uri = /vpc/1c747db6-d180-43ad-b5f7-3901a458f8c3/firewall/rules
``` 
(this is BRM42220017, gc17 on rack2)

To confirm that it's not an issue specific to the external IP or existing instances, I created a new instance on the same VPC that has a custom user with password login enabled. I still couldn't ssh into it but I could access it through the serial console. It also couldn't ping the other instances on the same subnet on their private IP (note: it could ping the subnet gateway so the issue still has to do with firewall rules).

<img width="945" alt="image" src="https://github.com/oxidecomputer/opte/assets/10874909/b3e8689c-09a4-497d-b26c-61a1879465e5">

Here are the nic details of the two instances that couldn't be pinged from/to:
```
pisces-2:tests angela$ oxide instance nic list --project try --instance newvpc-2c-8m
InstanceNetworkInterface {
    description: "intf0",
    id: 544b1adc-f667-45e9-9054-7d6ab19cdea5,
    instance_id: 00bb42f3-0dbd-4746-85d2-736927ab1c4e,
    ip: 172.30.0.5,
    mac: MacAddr(
        "A8:40:25:F9:F7:80",
    ),
    name: Name(
        "intf0",
    ),
    primary: true,
    subnet_id: 2cecef6e-50c7-4d71-a670-5b884a2cf8cf,
    time_created: 2023-06-15T23:21:20.359874Z,
    time_modified: 2023-06-15T23:21:20.359874Z,
    vpc_id: 1c747db6-d180-43ad-b5f7-3901a458f8c3,
}
pisces-2:tests angela$ oxide instance nic list --project try --instance secure-inst2
InstanceNetworkInterface {
    description: "",
    id: bcf01d5c-20da-4cf0-8ae0-a3a2932d4fdd,
    instance_id: 9f956578-d8ad-4144-a957-2af23d10e9f6,
    ip: 172.30.0.198,
    mac: MacAddr(
        "A8:40:25:F7:68:82",
    ),
    name: Name(
        "secure0",
    ),
    primary: true,
    subnet_id: 2cecef6e-50c7-4d71-a670-5b884a2cf8cf,
    time_created: 2023-06-15T21:30:37.323126Z,
    time_modified: 2023-06-15T21:30:37.323126Z,
    vpc_id: 1c747db6-d180-43ad-b5f7-3901a458f8c3,
}
```

**Comment by askfongjojo** [comment]
On second thought, perhaps the fixes should be at the API level for user to explicitly choose all ("anywhere" as a target, "all" as an option for protocol). In other words, these become required fields so user cannot leave host filter or protocol blank/unselected.

(also, moved this issue to omicron since it's not an opte bug)

**Comment by david-crespo** [comment]
So the fix would be to take the `Option` off of `hosts` and `protocols` and also validate that they are non-empty lists. What about `ports`? I don't know whether the same change has happened to ports — that no ports used to mean all ports but now means none — but for symmetry, we should probably make them all work the same way.

https://github.com/oxidecomputer/omicron/blob/9eac70a362b951aa333244e37caa110983b67528/common/src/api/external/mod.rs#L1625-L1639

**Comment by david-crespo** [comment]
I found that the logic that falls back to "Any" for empty ports, hosts, and protocols is still present and has not changed in 6 months. However, I think the logic might be wrong in that only for `ports` do we fall back to `Any` in the case of either `None` or an empty list. For `hosts` and `protocols`, we pass through an empty list without falling back to `Any`. I'm going to draft a PR fixing that logic for hosts and protocols and see if maybe that's the simplest short-term fix. Though I do think it may be counterintuitive for it to work that way, and requiring things is usually better than making the user wonder what will happen if they're left out.

https://github.com/oxidecomputer/omicron/blob/3ffbcf136a9effbd24083bc305e874e2f2ad6f39/illumos-utils/src/opte/firewall_rules.rs#L63-L137

**Comment by askfongjojo** [comment]
I don't expect any further work is required on this so I'm closing the ticket.
