### ISSUE TITLE
MUPdate failure: Trampoline Image needs `/usr/sbin/fstyp`

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3413]
On 6/23, I attempted to MUPdate the dogfood rack.

Sled 24 showed "Running installinator", with the following expanded message:

![image](https://github.com/oxidecomputer/omicron/assets/3258857/086c4522-32c5-4592-a846-a812c5e996a8)

It kinda looks like this is stuck waiting for M.2 disks?

**Comment by smklein** [comment]
Connecting to the console on this machine (via `pilot sp console BRM42220081`) shows that the M.2 pools exist, and have their datasets mounted at the expected locations. 

I can also see the M.2s through `prtconf -v`

**Comment by smklein** [comment]
Notably, in the installinator log, I'm seeing the following:

```
Dec 28 01:22:55.857 INFO found gimlet hardware, num_disks: 12, is_scrimlet: false, baseboard: Gimlet { identifier: "BRM42220081", model: "913-0000019", revision: 6 }
Dec 28 01:22:55.857 INFO ignoring U.2 disk, path: /devices/pci@ab,0/pci1de,fff9@1,1/pci1b96,0@0/blkdev@w0014EE81000BC74F,0
Dec 28 01:22:55.857 INFO ignoring U.2 disk, path: /devices/pci@38,0/pci1de,fff9@1,1/pci1b96,0@0/blkdev@w0014EE81000BC664,0
Dec 28 01:22:55.858 INFO Disk at /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0 already has a GPT
Dec 28 01:22:56.026 INFO GPT exists without Zpool: formatting zpool at /devices/pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013274955F,0:f
Dec 28 01:22:56.693 INFO Creating HardwareManager, component: HardwareManager
... (unrelated messages about "Received prefixes from ddmd")
```

So I *suspect* we're entering this branch and exiting -- though I don't know why the error isn't being shown at a higher-level? It might be getting swallowed somewhere.

https://github.com/oxidecomputer/omicron/blob/6c07a0c03f1fdfa41216941963a360828d780abb/installinator/src/hardware.rs#L49-L52

This means we're also likely invoking the code here:

https://github.com/oxidecomputer/omicron/blob/6c07a0c03f1fdfa41216941963a360828d780abb/sled-hardware/src/disk.rs#L320-L342

My guess:
- installinator calling `Disk::new`: https://github.com/oxidecomputer/omicron/blob/6c07a0c03f1fdfa41216941963a360828d780abb/installinator/src/hardware.rs#L50
- `Disk::new` calling `Self::ensure_zpool_exists`: https://github.com/oxidecomputer/omicron/blob/6c07a0c03f1fdfa41216941963a360828d780abb/sled-hardware/src/disk.rs#L274
- **Something** goes wrong, I don't know where the error ends up. But we can't get the zpool name through `fstyp`, at least.

**Comment by smklein** [comment]
Oh, interesting. The `fstyp` tool doesn't appear to exist on the trampoline image, which kinda breaks `ensure_zpool_exists`.

**Comment by smklein** [comment]
Two follow-ups from here:

1. Within Omicron, we should distinguish "fstyp could not find the zpool" from "any other error from fstyp execution". That would have made this more obvious.
2. Within the trampoline image build, we should add `/usr/sbin/fstyp`

**Comment by smklein** [comment]
Confirmed that deleting the zpools cause this sled to make progress. This confirms my theory about `fstyp`.

**Comment by jgallagher** [comment]
Fixed by https://github.com/oxidecomputer/helios/pull/95
