### ISSUE TITLE
the CI-generated TUF repo should have consistent version stamping

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#3430]
What I am presently working on is to make the artifact version as stored in a TUF repo's `artifacts.json` match the version that is stamped in that artifact.

For things that have an oxide.json at the root of a tarball (zone images and OS images), this means making sure the artifact version (and ideally commit hash) is stamped in oxide.json.

For Hubris SP/ROT images, this means extracting the `VERS` field out of the caboose and using that in artifacts.json.

I am tentatively putting this on the MVP milestone because I don't think "TUF and the artifacts agree on version numbers" stops us from doing MUPdate?

cc @smklein @jgallagher

**Comment by jgallagher** [comment]
> I am tentatively putting this on the MVP milestone because I don't think "TUF and the artifacts agree on version numbers" stops us from doing MUPdate?

Correct! Today, wicket displays version numbers for all the things, but only _uses_ them for the RoT and SP: if the RoT/SP reports to MGS that it's current version is `x.y.z-blah` and the TUF repo version is exactly `x.y.z-blah`, by default the update will not be applied to that component, but there's a toggle in the UI to force-apply even if the versions match.
