### ISSUE TITLE
Wicket U/I tweak: Sled overview page does not accurately represent what is populated

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3481]
All sleds show up as "green" on the visual overview page, regardless of which cubbies are populated.

We should consider updating the colors based on whether or not the cubby is populated? That might be a useful short visual indicator on "what the rack looks like", to guide Oxide support at install time.

**Comment by andrewjstone** [comment]
There's an old styling issue that contains this but I think it's good to have a separate issue for this in particular.

https://github.com/oxidecomputer/omicron/issues/2560
