### ISSUE TITLE
following how-to-run, Omicron does not sync clocks when using non-gimlet config

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#3501]
Debugging #3498 I was surprised that Omicron did not use NTP to sync the clocks across the two sleds.  I see that this is deliberately configured:
https://github.com/oxidecomputer/omicron/blob/c3048a1b43b046c284432eba34d0bc1933de4d56/smf/sled-agent/non-gimlet/config.toml#L17-L19

If that's unavoidable, then we should update how-to-run.adoc to include a step that is to configure NTP on all sleds and make sure they're synchronized.  (Would it be possible to just do the same thing we do on real systems here? CC @citrus-it

**Comment by citrus-it** [comment]
There are at least two reasons:

1. when NTP was first integrated, the mechanism to get an OPTE service port for external communication was not there yet, so it required manual shenanigans with VNICs to hook the NTP zone up to the outside world (which is what I did for testing).
2. (related) - to keep the CI tests passing.

buildomat tests use `-i standard -m non-gimlet -s softnpu` for creating the packages.

It is probably time to change the default value in that config.toml and fix up CI if necessary.

**Comment by citrus-it** [comment]
Based on the feedback on #3508, it seems that we can't easily have working timesync in CI. While that might be useful to wire up at some point, immediate options include:
- update developer documentation, pointing at the `timesync` setting;
- make a new profile `non-gimlet-ci` or similar, which retains the current timesync setting, then change the existing profile to enable timesync.

**Comment by luqmana** [comment]
Running with timesync not being skipped in CI would've helped catch https://github.com/oxidecomputer/omicron/pull/3589 earlier.
