### ISSUE TITLE
API: Field label and doc issues with setting password in `local_idp_user_create` and `local_idp_user_set_password` requests

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3516]
Currently the password value in the request payload is presented as follows in the API docs:
<img width="550" alt="image" src="https://github.com/oxidecomputer/omicron/assets/10874909/a9a13b16-9ac1-41ba-9cb2-d01bce4d2d70">
The top-level comment "password used to log in" should perhaps be changed to: "set or invalidate user password".

The `user_password_value` field is actually the operation: set password vs invalidate password, not the password value.

The `details` field is where the password value should be set. Apparently this and the field above had their labels swapped during implementation (?).

Finally, it's unclear if the "Passwords may be subject to additional constraints" remark is helpful at all because we don't provide a way to set/apply password policies.

**Comment by askfongjojo** [comment]
This sets the password to "thisisit":
```
$ oxide api /v1/system/identity-providers/local/users?silo=ops -X POST --input - <<EOF
>  {"external_id": "user3", "password": {"details": "thisisit", "user_password_value": "password"}}
> EOF
```
This returns an error:
```
$ oxide api /v1/system/identity-providers/local/users?silo=ops -X POST --input - <<EOF
>  {"external_id": "user4", "password": {"details": "something", "user_password_value": "secret"}}
> EOF
error; status code: 400 Bad Request
{
  "message": "unable to parse JSON body: password.user_password_value: unknown variant `secret`, expected `password` or `invalid_password` at line 1 column 94",
  "request_id": "041f92ee-26d1-4c36-8e27-0e71117bc268"
}
error: error
```

**Comment by davepacheco** [comment]
This is generated from these type definitions:
https://github.com/oxidecomputer/omicron/blob/c2de4805acfd0c20bef9d87afacac9f8e821ad87/nexus/types/src/external_api/params.rs#L274-L281
https://github.com/oxidecomputer/omicron/blob/c2de4805acfd0c20bef9d87afacac9f8e821ad87/nexus/types/src/external_api/params.rs#L406-L415

I think the Rust types mostly make sense.  I assumed the API spec and docs were auto-generated from the Rust types, but there's this override:
https://github.com/oxidecomputer/omicron/blob/c2de4805acfd0c20bef9d87afacac9f8e821ad87/nexus/types/src/external_api/params.rs#L409

which apparently I added but it makes no sense to me either.
