### ISSUE TITLE
zone logs should not be in rpool

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/omicron#3533]
Currently, our zones are created from the RAM disk zpool (`rpool`).  A challenge with that in particular is that zone logs are now both volatile (a challenge for debugging if a sled is bounced) and -- more pressingly -- very tightly capped.  In particular we had an instance where a pantry log was 21.6G (a feat only made possible by the ~10X compression factor we were getting there).  Once things right out of space, the world gets grim in a hurry.  We want to trim logs and log less loquaciously and so on -- but we also want/need a bit more breathing room by getting zones either onto one of the `oxi_` (M.2) pools or one of the `oxp_` (U.2) pools.  Because we saw this in dogfood, marking this MVP.

**Comment by davepacheco** [comment]
Related: #2478
