### ISSUE TITLE
external-networking: when adding addresses to ASIC, also add them to corresponding tfport

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#3588]
When we set up an external address, through RSS or otherwise, there is machinery to land the address on the ASIC. But we also need to land the address in the corresponding tfport. Here is why.

When nodes from within the rack try to communicate outbound, boundary services will decap the packet. Then in P4 we try to resolve the MAC for the destination IP. When it we can't, because there is no entry yet, the P4 code will kick a "needs resolving" packet up to the host. If the host does not have an address on the subnet of the address being resolved, the resolution will fail. Therefore we need addresses assigned to the ASIC to also be assigned to the corresponding switch zone tfport.

CC: @internet-diglett

**Comment by rcgoodfellow** [comment]
Maybe we should just do this as a general sync in tfportd like we are doing in this PR

- https://github.com/oxidecomputer/dendrite/pull/497

**Comment by luqmana** [comment]
(Out of curiousity, took a quick look at the illumos side of where the ARP request was failing: [This is where the `ip2mac` request eventually bails out](https://github.com/oxidecomputer/illumos-gate/blob/3b24312d6398cc8e8e513562a52571c416322378/usr/src/uts/common/inet/ip/ip_ndp.c#L4904-L4910).)

**Comment by jgallagher** [comment]
Fixed by #3765
