### ISSUE TITLE
wicket: could not start rack init via Ctrl-Alt-K from Mac

### ISSUE THREAD

**Issue by citrus-it** [oxidecomputer/omicron#3614]
I rebuilt dogfood earlier today and when I got to the RSS stage, I could not start the update via any key combination that I tried.
I'm using a Mac client and was testing with both iterm2 and the built in terminal program.
I tried on two keyboards - the built in laptop one, and a USB PC-like one which has an ALT key.
I also tried `ESC ^K` which should be the same sequence (but I don't know if that's going to work with wicket)
I tried putting `\x1b\x0b` onto the clipboard and pasting.

In the end I asked artemis to connect and she was able to start the update (Linux client, "foot" terminal).

**Comment by jgallagher** [comment]
I was able to reproduce this, and was able to fix it by turning on "option as meta" in Terminal.app, iterm2, and alacritty:

* Terminal.app: checkbox at the bottom of Profiles > Keyboard
* iTerm2: Profile > Keys > "Left Option Key" set to "Esc+" (Meta probably also works)
* alacritty: add `option_as_alt: Both` to `~/.alacritty.yml`

I _think_ there's nothing for wicket can do here; we need the terminal to actually send the modifier.

**Comment by jgallagher** [comment]
#3685 removed all the key commands that use Ctrl-Alt; we only use Ctrl now.
