### ISSUE TITLE
Test hang: test integration_tests::projects::test_project_deletion_with_snapshot

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3618]
Noticed from this run: https://buildomat.eng.oxide.computer/wg/0/details/01H591THQN287NB244WG06PF3B/soqHO6KnHIklBwriishrR9yq5pTA0Stpl5gMkfzWRk3LZS37/01H591TYDJ7TG6DX8QDT5V2JY7

It gave the `has been running for over 60 seconds` warning, then never identified itself as passing or failing.

**Comment by smklein** [comment]
Completed 50 iterations of this locally without failure. I worry there be some other issue at play, other than this test being flaky in isolation.

**Comment by leftwo** [comment]
That test claims its running on ubuntu-20.04

There is no snapshot support on non illimos systems, so I don't know what that test thinks it is doing..

**Comment by smklein** [comment]
The simulated sled agent provides a pantry interface: https://github.com/oxidecomputer/omicron/blob/fca839ccfcfba9efad015e79e707f1efaf8258af/sled-agent/src/sim/http_entrypoints_pantry.rs

This is runnable on Linux

**Comment by davepacheco** [comment]
There's no reason to believe this is different from #3580.  Closing as a dup for now.  We can reopen if we keep seeing it after that issue is resolved.
