### ISSUE TITLE
Improve omicron-brand-zone boot speed

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3682]
Improving this performance will improve:

- Rack setup time
- Sled boot time
- Instance creation time

Which would be, across the board, a great win.

https://github.com/oxidecomputer/omicron/pull/3676 is related to launch services in parallel, but launching zones individually noticeably takes on the order of ~10+ seconds, depending on the machine.

This issue should maybe have a related tracking issue in https://github.com/oxidecomputer/helios-omicron-brand/tree/main ?

**Comment by smklein** [comment]
At baseline:

```bash
$ pfexec zonecfg -z testzone
testzone: No such zone configured
Use 'create' to begin configuring a new zone.
zonecfg:testzone> create
zonecfg:testzone> set brand=omicron1
zonecfg:testzone> set zonepath=/zones/testzone
zonecfg:testzone> set autoboot=false
zonecfg:testzone> set ip-type=exclusive
zonecfg:testzone> end
The end command only makes sense in the resource scope.
zonecfg:testzone> commit
zonecfg:testzone> exit

$ time pfexec zoneadm -z testzone install /opt/oxide/nexus.tar.gz 
INFO: omicron: installing zone testzone @ "/zones/testzone"...
INFO: omicron: replicating /usr tree...
INFO: omicron: replicating /lib tree...
INFO: omicron: replicating /sbin tree...
INFO: omicron: pruning SMF manifests...
INFO: omicron: pruning global-only files...
INFO: omicron: unpacking baseline archive...
INFO: omicron: unpacking image "/opt/oxide/nexus.tar.gz"...
INFO: omicron: copying /etc/default/init...
INFO: omicron: install complete, probably!

real	0m10.528s
user	0m1.195s
sys	0m5.616s
```

**Comment by jclulow** [comment]
On which machine and OS image are you running that test?  I can take a look at improving things in the brand.

**Comment by smklein** [comment]
I used a 24 core, 64 GiB RAM helios 2 machine (not a gimlet, it's a workstation locally in my house). I suspect it's probably on-par with what we'd see on lab machines -- the 10 second ballpark feels about the same.

**Comment by jclulow** [comment]
Alright, good to know.  There are likely then at least a few differences:

- the Gimlet rpool is backed by ramdisk, and the replication target datasets are presumably now on the U.2-backed pools
- the Gimlet rpool is I believe still using gzip-9 compression, which is somewhat expensive to unpack; I assume your rpool is not
- was the target dataset encrypted on this test system?

**Comment by smklein** [comment]
In my test example, I was unpacking into the ramdisk of my machine, yeah. I was using a zone filesystem (at `zonepath=/zones/testzone` with no other mounted dataset). This is not an encrypted filesystem, and it's backed by RAM, so I figured it would be "at least as fast if not faster" than a disk-backed system.

**Comment by smklein** [comment]
```bash
$ pwd && df .
/zones
/                  (rpool/ROOT/heliosv2):1500845016 blocks 1500845016 files
```

**Comment by jclulow** [comment]
If it's not a Gimlet it seems more likely that rpool would _not_ be ramdisk backed right?  What does `zpool list -v rpool` say?

**Comment by smklein** [comment]
yup, you're right, I misinterpreted this. It is in fact not a ramdisk:

```
 $ zpool list -v rpool
NAME                      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
rpool                     928G   183G   745G        -         -    36%    19%  1.00x    ONLINE  -
 c1t002538B411501E52d0    928G   183G   745G        -         -    36%  19.8%      -    ONLINE
```

**Comment by jclulow** [comment]
I took a swing at improving this in oxidecomputer/helios-omicron-brand#12

**Comment by citrus-it** [comment]
This has been vastly improved by https://github.com/oxidecomputer/helios/issues/141, down from 15s to 1.6s.
https://github.com/oxidecomputer/helios-omicron-brand/pull/12 will get this further down, to < 1s.

**Comment by citrus-it** [comment]
I've added this to milestone 7 as it will be part of that release, and is probably release-notes-worthy.

**Comment by jclulow** [comment]
Both of the changes mentioned here have now integrated, so new images built after this moment should end up with **system/zones/brand/omicron1@1.0.22** which parallelises install speed, and the updated **primarycache** setting to enable ARC caching for the compressed ramdisk files.
