### ISSUE TITLE
Allocate Crucible Datasets On Separate Sleds

### ISSUE THREAD

**Issue by faithanalog** [oxidecomputer/omicron#3702]
As of https://github.com/oxidecomputer/omicron/pull/3650 we allocate datasets randomly across the rack. We generate an error if two datasets on the same zpool are selected (not currently possible, may be in future if another crucible dataset is added for some purpose). We do not factor the sled into account at all. We should. This will ensure resiliency against sled-level failures.

After speaking with sean on the matter (see some conversation in 3650), we both think it should be possible to do this in SQL with a few query steps in the CTE. This looks like the following code, approximately, but im probably getting something slightly wrong.

First, select one random zpool from each sled:

```
let our_random_ordering = /* dont feel like including it here, see existing code */;

zpool_dsl
  .inner_join(
    /* the query we have for making sure the zpools have enough space */
  )
  .order_by((zpool_dsl::sled_id, our_random_ordering))
  .distinct_on(zpool_dsl::sled_id)
  .select((zpool_dsl::id,));
```

Then, select one random dataset from each zpool. Note that this step should resolve the problem we have currently with potentially picking 2 datasets from a single pool during the selection, eliminating the need for the special error for that case. We could break that out into its own PR if we wanted.

```
dataset_dsl
  .inner_join(
    sled_selection.query_source()
      .on(sled_selection_dsl::zpool_id.eq(dataset_dsl::zpool_id))
  )
  .order_by((dataset_dsl::zpool_id, our_random_ordering))
  .distinct_on(dataset_dsl::zpool_id)
  .select((dataset_dsl::id,))
```

This gives us our list of possible datasets. Each dataset is from a distinct sled and zpool, and is on a zpool with enough space. Now we select 3 random candidates

```
dataset_selection /* or whatever name */
  .query_source()
  .order(our_random_ordering)
  .limit(REGION_REDUNDANCY_THRESHOLD)
  .select((dataset_selection_dsl::id,))
```

and then we should finally have the datasets we want.

The change is not quite that simple though. We may have tests that currently rely on being able to select 3 pool on a single sled. Additionally, being able to select 3 pools on one sled is a very nice feature to have for development. So we also will need to

- Modify tests accordingly, which tests remains to be seen
- Add a way for devs to configure nexus to use a 1-sled allocation strategy instead of a 3-sled allocation strategy.

3650 introduced the concept of an allocation strategy at lowest levels of the region allocation code, but did not run it through the rest of the codebase, so there's currently no way to configure it. This is a good time to add a way to do that. I do not know where that configuration should go (RSS config file?), or how I should get that configuration from wherever we set it to the place region allocation happens.

**Comment by faithanalog** [comment]
I'm assigning myself to this since I've just been working with this code and have familiarity with it now. But I will need some help as mentioned in the final paragraph:

> I do not know where that configuration should go (RSS config file?), or how I should get that configuration from wherever we set it to the place region allocation happens.

**Comment by smklein** [comment]
This all makes sense to me, thanks for writing it up. I'm hopeful the strategy as written will work.

Regarding the configurations: This is a decision made in Nexus, so it's ultimately a thing that needs to get plumbed into Nexus somehow. There are a lot of options here:

1. RSS config, as you say. This means plumbing this configuration option into Sled Agent API, which means it gets selected by Wicket, passed through Sled Agent, and handed off to Nexus while Nexus is already up-and-running.

Pros: It's dynamic?
Cons: It crosses across a ton of layers of the stack, and we've generally tried to reserve this config for early-boot, bootstrapping configuration.

2. Nexus config. Nexus currently loads its configuration from this struct: https://github.com/oxidecomputer/omicron/blob/fe9d1c2bd18c1a5ed97af8eb83b44ecb47806318/common/src/nexus_config.rs#L361-L369

... which is basically a concatenation of "known at build-time" (`PackageConfig)` and "known at run-time" (`DeploymentConfig`) parameters.

This configuration file is created by the Sled Agent when launching Nexus -- it basically concatenates the package-time `PackageConfig` with the parameters to construct the `DeploymentConfig`.

Pros: It's a configuration option in Nexus, so it lives in the config. Simple. Easy to work for tests.
Cons: It would require re-provisioning the service to change, though I don't think this is a downside.

3. Make it a toggle-able option in Nexus' API. 

**I would recommend we go with option 2: Add it to the Nexus config, and probably part of the `PackageConfig`.**
This makes the allocation strategy workable for test, dev, and production.

**Comment by faithanalog** [comment]
option 2 sounds great to me.

**Comment by leftwo** [comment]
Yeah, Option 2!

**Comment by faithanalog** [comment]
alright i have a query that picks 3 distinct sleds and I switched the default allocation over to that to see what would break. Only the tests I'd expect to fail are failing (basically things that call the create disk endpoint) so that's good. I'm hoping they're all using some common codepath to create the integration test environment for them, so I can change that to allocate the zpools across multiple sled IDs. I don't know much about omicron's integration tests.

```

     Summary [ 214.291s] 795 tests run: 723 passed (1 slow, 1 leaky), 72 failed, 2 skipped
        FAIL [   8.451s] omicron-nexus app::sagas::disk_create::test::test_actions_succeed_idempotently
        FAIL [   8.674s] omicron-nexus app::sagas::disk_create::test::test_saga_basic_usage_succeeds
        FAIL [   8.622s] omicron-nexus app::sagas::disk_delete::test::test_actions_succeed_idempotently
        FAIL [   8.568s] omicron-nexus app::sagas::disk_delete::test::test_saga_basic_usage_succeeds
        FAIL [   8.509s] omicron-nexus app::sagas::instance_create::test::test_action_failure_can_unwind
        FAIL [   8.374s] omicron-nexus app::sagas::instance_create::test::test_action_failure_can_unwind_idempotently
        FAIL [   8.553s] omicron-nexus app::sagas::instance_create::test::test_actions_succeed_idempotently
        FAIL [   8.667s] omicron-nexus app::sagas::instance_create::test::test_saga_basic_usage_succeeds
        FAIL [   8.674s] omicron-nexus app::sagas::instance_delete::test::test_actions_succeed_idempotently
        FAIL [   8.487s] omicron-nexus app::sagas::instance_delete::test::test_saga_basic_usage_succeeds
        FAIL [   8.640s] omicron-nexus app::sagas::snapshot_create::test::test_action_failure_can_unwind_no_pantry
        FAIL [   8.657s] omicron-nexus app::sagas::snapshot_create::test::test_action_failure_can_unwind_pantry
        FAIL [   8.578s] omicron-nexus app::sagas::snapshot_create::test::test_saga_basic_usage_succeeds
        FAIL [   8.502s] omicron-nexus app::sagas::snapshot_create::test::test_saga_use_the_pantry_wrongly_set
        FAIL [   8.492s] omicron-nexus app::sagas::snapshot_create::test::test_saga_use_the_pantry_wrongly_unset
        FAIL [   8.296s] omicron-nexus::test_all integration_tests::disks::test_disk_create_attach_detach_delete
        FAIL [   8.442s] omicron-nexus::test_all integration_tests::disks::test_disk_create_disk_that_already_exists_fails
        FAIL [  13.643s] omicron-nexus::test_all integration_tests::disks::test_disk_create_for_importing
        FAIL [   8.128s] omicron-nexus::test_all integration_tests::disks::test_disk_creation_region_requested_then_started
        FAIL [   8.438s] omicron-nexus::test_all integration_tests::disks::test_disk_metrics
        FAIL [   8.664s] omicron-nexus::test_all integration_tests::disks::test_disk_metrics_paginated
        FAIL [   8.325s] omicron-nexus::test_all integration_tests::disks::test_disk_move_between_instances
        FAIL [  13.602s] omicron-nexus::test_all integration_tests::disks::test_disk_region_creation_failure
        FAIL [  13.362s] omicron-nexus::test_all integration_tests::disks::test_disk_size_accounting
        FAIL [   8.302s] omicron-nexus::test_all integration_tests::disks::test_disk_slot_assignment
        FAIL [  13.806s] omicron-nexus::test_all integration_tests::disks::test_disk_virtual_provisioning_collection
        FAIL [  13.544s] omicron-nexus::test_all integration_tests::disks::test_multiple_disks_multiple_zpools
        FAIL [  12.975s] omicron-nexus::test_all integration_tests::images::test_image_from_other_project_snapshot_fails
        FAIL [  13.040s] omicron-nexus::test_all integration_tests::images::test_make_disk_from_image
        FAIL [   7.898s] omicron-nexus::test_all integration_tests::instances::test_attach_eight_disks_to_instance
        FAIL [   7.929s] omicron-nexus::test_all integration_tests::instances::test_attach_one_disk_to_instance
        FAIL [   7.834s] omicron-nexus::test_all integration_tests::instances::test_cannot_attach_faulted_disks
        FAIL [   8.080s] omicron-nexus::test_all integration_tests::instances::test_cannot_attach_nine_disks_to_instance
        FAIL [   8.158s] omicron-nexus::test_all integration_tests::instances::test_disks_detached_when_instance_destroyed
        FAIL [   8.213s] omicron-nexus::test_all integration_tests::instances::test_instance_create_attach_disks
        FAIL [   8.253s] omicron-nexus::test_all integration_tests::instances::test_instance_create_attach_disks_undo
        FAIL [  15.001s] omicron-nexus::test_all integration_tests::metrics::test_metrics
        FAIL [   8.350s] omicron-nexus::test_all integration_tests::pantry::test_can_stop_start_import_from_bulk_write
        FAIL [   8.560s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_attached_disk
        FAIL [   8.456s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_data_non_base64
        FAIL [   8.496s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_data_not_block_size_multiple
        FAIL [   8.312s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_data_past_end_of_disk
        FAIL [   8.329s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_start_attached_disk
        FAIL [   8.378s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_stop_attached_disk
        FAIL [   8.526s] omicron-nexus::test_all integration_tests::pantry::test_cannot_bulk_write_to_unaligned_offset
        FAIL [   8.410s] omicron-nexus::test_all integration_tests::pantry::test_cannot_finalize_attached_disk
        FAIL [   8.390s] omicron-nexus::test_all integration_tests::pantry::test_cannot_finalize_without_stopping_bulk_writes
        FAIL [   8.429s] omicron-nexus::test_all integration_tests::pantry::test_cannot_mount_import_from_bulk_writes_disk
        FAIL [   8.469s] omicron-nexus::test_all integration_tests::pantry::test_cannot_mount_import_ready_disk
        FAIL [  13.802s] omicron-nexus::test_all integration_tests::pantry::test_disk_create_for_importing
        FAIL [   8.456s] omicron-nexus::test_all integration_tests::pantry::test_import_blocks_from_url
        FAIL [   8.646s] omicron-nexus::test_all integration_tests::pantry::test_import_blocks_with_bulk_write
        FAIL [   8.472s] omicron-nexus::test_all integration_tests::pantry::test_import_blocks_with_bulk_write_with_snapshot
        FAIL [   8.553s] omicron-nexus::test_all integration_tests::projects::test_project_deletion_with_disk
        FAIL [   8.660s] omicron-nexus::test_all integration_tests::projects::test_project_deletion_with_snapshot
        FAIL [  13.887s] omicron-nexus::test_all integration_tests::snapshots::test_cannot_snapshot_if_no_space
        FAIL [  13.737s] omicron-nexus::test_all integration_tests::snapshots::test_delete_snapshot
        FAIL [  13.825s] omicron-nexus::test_all integration_tests::snapshots::test_snapshot_basic
        FAIL [  13.911s] omicron-nexus::test_all integration_tests::snapshots::test_snapshot_unwind
        FAIL [  13.821s] omicron-nexus::test_all integration_tests::snapshots::test_snapshot_without_instance
        FAIL [   9.311s] omicron-nexus::test_all integration_tests::unauthorized::test_unauthorized
        FAIL [  13.766s] omicron-nexus::test_all integration_tests::volume_management::test_create_image_from_snapshot
        FAIL [  13.721s] omicron-nexus::test_all integration_tests::volume_management::test_create_image_from_snapshot_delete
        FAIL [  13.574s] omicron-nexus::test_all integration_tests::volume_management::test_delete_snapshot_then_disk
        FAIL [  13.490s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_1
        FAIL [  13.341s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2
        FAIL [  13.340s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_layers_of_snapshots_delete_all_disks_first
        FAIL [  13.412s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_layers_of_snapshots_delete_all_snapshots_first
        FAIL [  13.164s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_layers_of_snapshots_random_delete_order
        FAIL [  13.617s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_snapshots
        FAIL [  13.411s] omicron-nexus::test_all integration_tests::volume_management::test_snapshot_prevents_other_disk
        FAIL [  13.598s] omicron-nexus::test_all integration_tests::volume_management::test_snapshot_then_delete_disk
error: test run failed
v
```

**Comment by smklein** [comment]
I suspect all of those are spinning up a "single-sled, multi-disk" environment, which would explain the issues.

**Comment by faithanalog** [comment]
oh yeah without a doubt

**Comment by faithanalog** [comment]
Updating the tests is proving difficult. I would prefer that the integration tests to run in a multi-sled multi-disk environment to match prod, rather than configuring them to use a single sled allocation mode. To that end I've been trying to figure out how to actually achieve this.

Currently we have `DiskTest::new()` which creates 3 zpools on a sled. All the tests which use disk call this. That's good.

I tried changing `DiskTest::new()` to spin up two additional sleds to allocate zpools on. This introduced a few problems.

First, because the DiskTest owns the tempdir handles, the DiskTest needs to be kept alive for the duration of the test and only dropped at the end. That's fine, I updated all the existing uses of DiskTest to bind it so it'll get dropped at the end of the test function.

Second though, there seems to be something deeper afoot. I don't have a good place to shut down the extra sleds (unless I add a `DiskTest.shutdown()`, maybe, that everything needs to call). And currently, perhaps because I'm not explicitly shutting down the extra sleds I'm not really sure, my change seems to cause the tests that use DiskTest to just hang indefinitely. (excluding the other ones that are erroring for reasons I'm unsure about).

I sort of get the feeling that this is just the wrong place to introduce this change and maybe I should adjust the test environment to *always* create 3 sleds right from the start. Then DiskTest wont need to do anything special and will have 3 sleds available to pull from in the context. going to try that out

**Comment by faithanalog** [comment]
Always creating 3 sleds higher up the stack does fix a number of the tests, but causes a number of other ones to break (notably, many of them seem to relate pantry, but not all of them...).

It's incredibly unclear to me as to what is actually breaking since the logs are mostly just "500 internal server error something went wrong :)". I'll look into it more.

**Comment by faithanalog** [comment]
we're pivoting to making the integraiton tests use the allocation strategy that does not care about distinct sleds. dogfood can test the 3 distinct sleds config. we can maybe fix this later but a LOT of the sim sled agent/pantry only works in one-sled mode
