### ISSUE TITLE
update non-gimlet sled agent configs to provision a reservoir

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/omicron#3743]
Now that oxidecomputer/propolis#410 has landed, before changing the propolis-server dep to pull in this change, we'll need to update the sled agent non-gimlet and gimlet-standalone configs to configure a VMM reservoir size.

Currently, that value is configured as a percentage of DRAM, rounded down to the nearest 2MiB. For dev machines, we may want to consider providing a bit more flexibility: a sensible option might be a different (mutually exclusive) option that allows one to configure a specific size instead of a percentage.

**Comment by gjcolombo** [comment]
Do our past experiences with safely enabling the reservoir (https://github.com/oxidecomputer/omicron/issues/2650#issuecomment-1563210376, #2858) imply that someone (sled agent? one of the setup utilities?) should also check for the existence of a swap device if the underlying platform is non-gimlet/gimlet-standalone?

**Comment by jordanhendricks** [comment]
Stock helios images that I imagine most people are using for dev should have swap setup by default in rpool/swap. But we could make sled-agent check for a swap device unconditionally, regardless of whether it's configured to make one.

**Comment by gjcolombo** [comment]
An additional small paper cut we may want to address here: `omicron-package uninstall` and `destroy_virtual_hardware.sh` don't reset the reservoir size to 0, so if you're (say) running an Omicron devcluster and then want to use the machine for something else, you need to know to reclaim that memory by hand (e.g. via the `rsrvrctl` utility in the Propolis repo). This is certainly a solvable problem, but I haven't yet thought about the best way to solve it.

**Comment by jordanhendricks** [comment]
It seems we added a percentage-based reservoir configuration in #3798.

**Comment by jordanhendricks** [comment]
As of #3830, all the current sled-agent config.tomls (gimlet, non-gimlet, gimlet-standalone) are configured to provision a reservoir (and also a swap device, if needed), so I am closing this.

I filed some follow up issues for other issues raised here:
- for more flexible reservoir configuration, #3874
- for better UX related to cleaning up the reservoir, #3875
