### ISSUE TITLE
Ability to add a new sled to the lrtq cluster

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#3757]
A sled that is plugged into an existing initialized rack needs to be told it is a `learner` node so that it can learn its key share. The bootstrap agent has access to a `NodeHandle` that [can be used for this purpose](https://github.com/oxidecomputer/omicron/blob/main/bootstore/src/schemes/v0/peer.rs#L138).

Once the learner has learned its share it can ask for other peers' shares so that it can recompute the rack secret. This initialization happens in [`request_sled_agent`](https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/bootstrap/agent.rs#L690), which is triggered via RSS or having an already ledger persisted `SledAgentRequest` on cold boot. However, new sleds will not have this, and it is likely we need to plumb a sled addition request all the way from the UI to perform this initialization.

**Comment by jmpesp** [comment]
Related to https://github.com/oxidecomputer/omicron/issues/2545?

**Comment by andrewjstone** [comment]
> Related to #2545?

Indeed! LRTQ is *very* unsophisticated in that if a new sled learns a share, you can't really revert that without wiping its cluster directories on the M.2s, which I suppose could be the `undo` part of that saga action. You also have the relatively minor issue that the sled's baseboard will be permanently marked as using a share that was handed out by a sled. There's no way to revoke that. This is all temporary though, until a trust quorum protocol supporting reconfigurations and rekeying is implemented.

**Comment by andrewjstone** [comment]
This was completed in https://github.com/oxidecomputer/omicron/pull/4545
