### ISSUE TITLE
[oximeter] Some routes for HTTP metrics have an extra leading `/`

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#3780]
I'm experimenting with a SQL-like interface on top of the timeseries data in ClickHouse that `oximeter` collects. I copied the data from the dogfood rack to have a sample set to work from. Among the existing metrics are the request latencies to Nexus:

```
shale :) select * from timeseries_schema where timeseries_name = 'http_service:request_latency_histogram';

SELECT *
FROM timeseries_schema
WHERE timeseries_name = 'http_service:request_latency_histogram'

Query id: 79624f1a-3108-429a-b0c0-f83fc91ddb29

┌─timeseries_name────────────────────────┬─fields.name──────────────────────────────────┬─fields.type───────────────────────────────┬─fields.source──────────────────────────────────┬─datum_type───┬───────────────────────created─┐
│ http_service:request_latency_histogram │ ['name','id','route','method','status_code'] │ ['String','Uuid','String','String','I64'] │ ['Target','Target','Metric','Metric','Metric'] │ HistogramF64 │ 2023-07-27 01:59:49.058625349 │
└────────────────────────────────────────┴──────────────────────────────────────────────┴───────────────────────────────────────────┴────────────────────────────────────────────────┴──────────────┴───────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec.

shale :)
```

One of the fields is the API route in the request. While playing around, I noticed that for some of the routes, there appear to be near-duplicate entries, where one has an extra leading slash (`/`):

```
shale :) select distinct timeseries_name, timeseries_key, field_value as route from fields_string where field_name = 'route' and field_value like '%v1/instances';

SELECT DISTINCT
    timeseries_name,
    timeseries_key,
    field_value AS route
FROM fields_string
WHERE (field_name = 'route') AND (field_value LIKE '%v1/instances')

Query id: 86594a03-6fef-46db-8302-12b990f0a06f

┌─timeseries_name────────────────────────┬───────timeseries_key─┬─route──────────┐
│ http_service:request_latency_histogram │  2433262963170828482 │ //v1/instances │
│ http_service:request_latency_histogram │  7122005840022189297 │ //v1/instances │
│ http_service:request_latency_histogram │ 17426811165009540366 │ //v1/instances │
│ http_service:request_latency_histogram │  7030863076971950895 │ /v1/instances  │
│ http_service:request_latency_histogram │ 11057398227386155688 │ /v1/instances  │
│ http_service:request_latency_histogram │ 14662578466297132538 │ /v1/instances  │
│ http_service:request_latency_histogram │ 18146047067220545467 │ /v1/instances  │
└────────────────────────────────────────┴──────────────────────┴────────────────┘

7 rows in set. Elapsed: 0.003 sec. Processed 9.76 thousand rows, 858.93 KB (3.52 million rows/s., 310.01 MB/s.)

shale :)
```

Note that the keys are different by construction, since it's a hash of the field values, which are different. Other than that, it's really not clear where this is coming from. All the API routes themselves in Nexus's external entrypoints file have a single leading slash. It seems like there are different clients in use, some of which add a leading slash. I don't have details on which clients those are yet, since we don't include that information in this timeseries.

The only other datapoint I have now is that the timeseries do appear to _start_ at different times:

```
shale :) select min(timestamp), max(timestamp) from measurements_histogramf64 where timeseries_key in (select distinct timeseries_key from fields_string where field_name = 'route' and field_value like '/v1/disks/%/finalize');

SELECT
    min(timestamp),
    max(timestamp)
FROM measurements_histogramf64
WHERE timeseries_key IN (
    SELECT DISTINCT timeseries_key
    FROM fields_string
    WHERE (field_name = 'route') AND (field_value LIKE '/v1/disks/%/finalize')
)

Query id: 9c80f678-12fe-4bff-9822-806d6546382f

┌────────────────min(timestamp)─┬────────────────max(timestamp)─┐
│ 2023-07-27 05:01:07.131757228 │ 2023-07-27 16:30:29.164411152 │
└───────────────────────────────┴───────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec. Processed 81.92 thousand rows, 1.23 MB (7.42 million rows/s., 111.25 MB/s.)

shale :)
```

I'm not sure if that's true for _all_ timeseries that have a single- and  double-leading-slash version.

This also doesn't appear to be a bug in Omicron specifically, since all the endpoints are instrumented the same way. It looks like the actual Dropshot request includes an additional leading slash. I'm adding it here until I find a better place.

**Comment by bnaecker** [comment]
I found the log file for at least one instance of `nexus` that shows these endpoints. It looks like the requests are coming from external clients:

```
root@oxz_nexus_65fc8751-0523-44c1-a551-52baa30275d1:~# grep "\/\/v1" /var/svc/log/oxide-nexus\:default.log | looker | grep remote_addr | cut -d "=" -f 2 | cut -d ":" -f1 | sort | uniq
 172.20.17.42
 172.20.3.69
```

Based on the lab networking doc, those are "VPN clients" and presumably an unlisted lab server, respectively. Not sure how to narrow it down further, but it seems likely these are two `oxide` CLI clients. I took a quick look through the CLI code, which doesn't seem to be adding any leading slashes. It occurs to me that they could very well be coming from the (user-controlled) configuration file listing the Oxide hosts. E.g., if one includes a trailing slash in the host name, the actual HTTP request would go to something like `http://foo.oxide.computer//v1/projects` for example. It seems to mitigate this (if we want to), we'd trim multiple leading slashes in the `RequestLatencyTracker` type we use to actually keep track of the requests in a histogram.

**Comment by david-crespo** [comment]
I just noticed last week that in the `hosts.toml` generated by the CLI, the host has a trailing slash on it, which I thought was a bit odd.

```
["https://oxide.sys.rack2.eng.oxide.computer/"]
```

I don't see anything that stands out in oxide.rs.

https://github.com/oxidecomputer/oxide.rs/blob/26bc6190822554d9999022813bd2c3732bb57892/cli/src/cmd_auth.rs#L325-L326

**Comment by bnaecker** [comment]
Thanks @david-crespo that jives with what I'm seeing. I'll add a method to normalize the routes we record internally, stripping multiple leading and any trailing slashes. Looks like the `http::Uri` type is perfectly happy accepting those URIs, even though they don't quite follow [the relevant RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3.3). [Here's](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4bedc326f934b2029b8bf1efbb067b71) a playground link with a method to trim these bits from any URI paths we do happen to get at Nexus.

**Comment by bnaecker** [comment]
Also cc @ahl, in case we want to do something different in the CLI when generating `hosts.toml`. I don't have an opinion, just to put it on your radar.
