### ISSUE TITLE
sled-agent cold boot: rack secret timeout

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3789]
While cold boot testing `madrid`, we hit this error on the scrimlet sled-agent:

```
00:01:24.571Z WARN SledAgent (BootstrapAgent): Could not ensure partitions: KeyManager error: Failed to retreive secret: Bootstore error: Fsm error: rack secret load timeout
00:01:24.571Z WARN SledAgent (BootstrapAgent): StorageWorker encountered unexpected error: KeyManager error: Failed to retreive secret: Bootstore error: Fsm error: rack secret load timeout
```

After chatting live, @andrewjstone pointed out that we do not have any retries here, and we need them: not all sleds will boot at the same time, so the early ones will need to retry until they're able to load the rack secret.

The full logs from this are at `/net/catacomb/data/staff/core/madrid/omicron-3789`: note that these logs show _2_ sled agent bounces; I'll open separate issues for each of those.

**Comment by andrewjstone** [comment]
It should also be noted that this doesn't only affect cold boot. Hot insert of a `U.2` will require a reconstruction of the rack secret. This may shape the solution differently.
