### ISSUE TITLE
sled-agent cold boot: retry if starting services fails

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3790]
While cold-booting madrid, we hit #3789 which led to sled-agent failing to find any U.2s when it attempted to pick a random U.2 for services, which led to sled-agent exiting (and being subsequently restarted by smf):

```
sled-agent: Error managing sled agent: Could not start sled agent server: No U.2 devices found with a crypt/zone mountpoint
[ Dec 28 00:03:38 Stopping because all processes in service exited. ]
[ Dec 28 00:03:38 Executing stop method (:kill). ]
```

Even once #3789 is fixed, sled-agent should retry service start failures, as there several (expected) reasons why services might not be able to start at the time when sled-agent first attempts to.

The full log for the madrid cold boot is at `/net/catacomb/data/staff/core/madrid/omicron-3789`. This shows a second sled-agent restart with a different error message; I'll open a separate issue for it.

**Comment by smklein** [comment]
https://github.com/oxidecomputer/omicron/issues/2973 is related, but I can add a retry loop as a short-term fix.
