### ISSUE TITLE
Build a TUF repository with SP images for all relevant hardware revisions

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3893]
Now that #3394 is fixed via #3887, we should build a TUF repo in CI that includes SP images for all hardware revisions starting with the dogfood rack forward (currently: gimlet-c though gimlet-e, psc-b and psc-c, sidecar-b and sidecar-c). Once all deployed racks have been updated past #3887, we can stop producing hardware-revision-specific TUF repos.

---

- [x] Convert dogfood repo to being The Repo (requires #3887 to land on dogfood)
- [x] Stop building a separate PVT1 repo (we can do this after this installation is updated)

**Comment by iliana** [comment]
(Added a task list to the issue description to make sure we track both adding all the hardware variants to the soon-to-formerly-be-known-as-dogfood repo, and stop building the PVT1 repo.)
