### ISSUE TITLE
want generic framework for common saga tests

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#3896]
There are several common tests that we rewrite for several different sagas, e.g.:

- test that the saga runs correctly
- test that the saga unwinds correctly from each possible error injection point
- test that the saga runs correctly if an arbitrary node is repeated
- test that the saga unwinds correctly if arbitrary undo nodes are repeated

An important lesson from #3265 and #3894 is that these tests, especially the second kind, are hard to write correctly: it's easy to get the saga execution boilerplate wrong so that the test passes but not all the undo actions are properly tested. It's also easy to forget to regenerate saga parameters that may have been changed by a prior attempt to execute the saga.

Instead of rewriting these tests by hand each time we write a new saga, we should write a set of templated harnesses that let the caller specify how to produce a DAG for each execution of the saga and what (if any) actions should be taken after each execution. Then the harness does the work of executing the saga, injecting retries/undo steps, checking for the correct errors, and the like, calling the caller-supplied closures on either side to ensure the correct parameters are generated for each test run.

**Comment by jordanhendricks** [comment]
It seems like #1799 might have some overlap here.
