### ISSUE TITLE
An Oxide health check endpoint for customer monitoring system to use

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3923]
We don't currently provide an API endpoint for customer's monitoring system to use for general health checks. The API should provide:
- 200 or 50x response
- error message for failed status check
- optional configurable timeout

One thing that we may want to consider is whether the API can be used with silo-specific endpoints or Recovery silo endpoint only, or both. From a Nexus monitoring perspective, the check against any silo endpoint should suffice. There is also a chance that a particular silo endpoint doesn't work because of an external DNS issue (which is uncommon) so there may be some value for customer to check all silo endpoints.

**Comment by david-crespo** [comment]
I have a tiny draft for this, will post it soon.
