### ISSUE TITLE
`wicketd` has a big heap after driving installation

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#3943]
In yesterday's dogfood update the captain updated the cubby 16 Scrimlet, then used it to update the rest of the rack, including the cubby 14 Scrimlet. In the aftermath, `pmap(1)` says that 16's `wicketd` is holding on to about 6.75 GiB of heap-related swap charges:

```
root@oxz_switch:~# pgrep wicketd | xargs pmap -S
1628:   /opt/oxide/wicketd/bin/wicketd run /var/svc/manifest/site/wicketd/conf
         Address     Kbytes       Swap Mode Mapped File
0000000000400000      33984          - r-x--  wicketd
000000000253F000       1192       1192 rw---  wicketd
0000000002669000    4150204    4150204 rw---    [ heap ]
00000000FFB58000    2916372    2916372 rw---    [ heap ]
```

Its sibling on 14 is much smaller:

```
2068:   /opt/oxide/wicketd/bin/wicketd run /var/svc/manifest/site/wicketd/conf
         Address     Kbytes       Swap Mode Mapped File
0000000000400000      33984          - r-x--  wicketd
000000000253F000       1192       1192 rw---  wicketd
0000000002669000      59716      59716 rw---    [ heap ]
```

RFD 413 proposes that each rack service be given a swap limit and reservation that ensures it won't OOM from a lack of available swap charges (as long as the service's processes are well-behaved). Under that scheme, we'd currently need to assume that `wicketd` needs a 7-8 GiB swap reservation. That's about 10% of the available swap on a sled in RFD 413's proposed budgets. This is workable for now, but I wanted to file an issue to track two items:

1. It'd be great to give the maximum heap size figure a haircut if at all possible.
2. More importantly, we need to understand where all this usage is coming from so that we can convince ourselves this maximum won't grow if our update repositories grow.

It'd also be good hygiene to make sure all this memory is freed after being used (assuming it isn't; it's possible that it's freed from the application's perspective but that the underlying heap implementation isn't actually releasing the underlying swap; I don't know enough about the illumos heap to know how likely this is). I don't think that affects the reservations we have to create (we have to reserve enough to accommodate peak swap usage even if that usage is transient).

**Comment by jgallagher** [comment]
> 1. It'd be great to give the maximum heap size figure a haircut if at all possible.
> 2. More importantly, we need to understand where all this usage is coming from so that we can convince ourselves this maximum won't grow if our update repositories grow.

I'll take a first pass at 2 today (which will then inform how much we can do for 1, I hope.)

> It'd also be good hygiene to make sure all this memory is freed after being used (assuming it isn't; it's possible that it's freed from the application's perspective but that the underlying heap implementation isn't actually releasing the underlying swap; I don't know enough about the illumos heap to know how likely this is). 

This is a little trickier than it sounds, assuming the bulk of this heap is related to the TUF repo and/or running updates. wicketd accepts a TUF repo and then waits for the user to trigger updates on any number of sleds; it doesn't know when the user is done issuing updates. Some options, none of which seem great:

1. Some kind of sled-based heuristic on update completion (e.g., "every sled other than the one where wicket is running has been successfully updated"). This would work for full-rack updates, but would be tricky on incomplete racks (should we wait in case new sleds are being plugged in?) and wouldn't fire at all if we were only updating a subset of the rack (which is the case for basically every dogfood update).
2. A timeout (e.g., if no update has been started in X minutes/hours, purge the repo).
3. A manual command that the operator could run to purge the repo when they were done issuing updates (obvious downside is that the operator has to know and remember to do this)

**Comment by jgallagher** [comment]
#3953 gives `wicketd`'s heap a serious haircut. There are still a few more things to do (noted at the end of that PR's description) before closing this out, but we can be much more reasonable here.

That change does shift things out of `wicketd`'s heap and into `/tmp`, so we're still eating into RAM. If we need to move that to a physical disk that's easy enough from `wicketd`'s point of view if it can be told what directory to use.
