### ISSUE TITLE
wicket / the control plane cannot know which signature the ROT wants

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#3954]
I am pretty sure @jgallagher wrote this somewhere and I can no longer find it, but unfortunately at the moment we have no way of asking an ROT whether it is expecting images uploaded to it to be signed by the `prod-rel` chain or the `staging-dev` chain.

For now, this results in us building two separate zips of TUF repos. In the future online-update scenario if this is not / cannot be resolved, racks will need to be configured to use a correct TUF metadata prefix that references only the ROT images it can accept.

If we can read the current caboose on the ROT, we may be able to store some fact about the signature chain (or at least our human-friendly name for the chain) as part of signing and use that to ensure we select the correct ROT image set. We would then need to ensure all customer racks are updated to understand multiple ROT image sets in a repo.

**Comment by jclulow** [comment]
I don't think the rack level prefix is going to work, FWIW; there's nothing that prevents a mixed population of Gimlets with different ROT code policies.  We might for example have a rack that has **staging/dev** code but then add a **bart** signed Gimlet for some engineering or diagnostic purpose.  Or we might bring a **prod-rel** machine back from the field and insert it into rack2 for some reason.

**Comment by labbott** [comment]
We now have a unified TUF repo so I'm going to close this issue
