### ISSUE TITLE
oximeter could separate the actions of creating a producer registry and registering its server

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/omicron#3956]
In oxidecomputer/propolis#497, a call to propolis-server's `instance_ensure` got stuck because it could not connect to oximeter to register a producer registry endpoint. (The reason the call got stuck was that propolis-server was retrying its request to oximeter for forever, but oximeter was having an extended outage due to clickhouse being down).

It would be nice if oximeter allowed applications to create a producer registry and register its server in separate operations, such that propolis-server could set up the registry and use it during the instance setup path, but asynchronously register the metrics server, such that if oximeter comes and goes, propolis still produce metrics later if it is eventually able to connect to the oximeter consumer.

(cc @bnaecker)

**Comment by bnaecker** [comment]
Closed by #4117
