### ISSUE TITLE
[ClickHouse] Enable replicated mode once Nexus provisions services

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#4000]
ClickHouse replicated functionality has been implemented in https://github.com/oxidecomputer/omicron/pull/3494. This functionality had to be disabled for the following reasons:

- RSS, which provisions services, only runs once during rack set up.
- We already had customer racks running single node CH.
- We want as little as possible divergence between racks, and this functionality did not warrant such divergence.

Once https://github.com/oxidecomputer/omicron/issues/732 has been implemented, replicated mode should be re-enabled in the following manner:

- The `method_script.sh` for the `clickhouse` service is set to run single node mode by default, but can be switched to run on replicated mode by [swapping a variable to false](https://github.com/oxidecomputer/omicron/pull/3494/files#diff-5475f31ccc4d46ea5ed682a38970067eacc337f0c6cd52581b1609f4ecce6071R31-R49). When we migrate all racks to a replicated ClickHouse setup, all logic related to running on single node will be removed from that file.
- The number of zones defined through RSS will stay the same. Instructions on how to tweak them to launch in replicated mode have been [left in the form of comments](https://github.com/oxidecomputer/omicron/pull/3494/files#diff-9ea2b79544fdd0a21914ea354fba0b3670258746b1350d900285445d399861e1R59-R64).

Solely enabling this way can incur in data loss due to the tables using different engines (e.g. `MergeTree` vs `ReplicatedMergeTree`), and not having been set up within a cluster. If we decide that this is not acceptable, this plan should also include a way to migrate data over.

**Comment by andrewjstone** [comment]
@karencfv I think we can safely close this now that we are in a reconfigurator based world. The instructions don't seem to be valid anymore.

**Comment by karencfv** [comment]
Yup! makes sense
