### ISSUE TITLE
IP pools: change/remove default

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4002]
In #3985, IP pools gained an explicit property `is_default`, which can be set at create time. However, it cannot be changed through the IP pool update endpoint.

https://github.com/oxidecomputer/omicron/blob/01e730acf3efeb6ff2181d558cf373ded383a365/nexus/types/src/external_api/params.rs#L729-L752

Because there can be at most one default for a given scope (fleet-wide or silo-specific),

https://github.com/oxidecomputer/omicron/blob/01e730acf3efeb6ff2181d558cf373ded383a365/schema/crdb/dbinit.sql#L1497-L1505

## Proposal

I don't think it makes sense to add `is_default` to the update params. Instead, I think we should have a make default endpoint, sort of analogous to image promotion and demotion. This endpoint would

- set `is_default = false` on the current default pool (if there is one)
- set `is_default = true` on the target pool

We probably also want a make-not-default endpoint, but it should probably only work on silo-scoped pools, otherwise instance create could fail due to there being no default pool.

**Comment by karencfv** [comment]
For things like Terraform it's preferable to have the update endpoint as similar to the create one as much as possible, because you can only do a single action per create/read/update/delete per resource.

Are there any strong reasons to have a separate endpoint that only sets a single IP Pool to default?

**Comment by karencfv** [comment]
> My thinking is that because there is only one default for the fleet or a silo, making one pool default makes another pool not default, and I would find it strange for a PUT /v1/system/ip-pools/my-pool to modify my-other-pool.

Hm yeah, that makes sense.

> Another way to handle this, which honestly did not occur to me while I was hurrying to do https://github.com/oxidecomputer/omicron/pull/3895, is to have the association between pools and silos be a separate join table that's not considered a property of the pool or the silo at all. In other words, you can list your pools, and you can set a default pool for a silo, but those don't intrinsically have anything do with each other. I am definitely open to changing the model to something more flexible and less surprising.

I'm assuming this means the `is_default` field is removed altogether from the create endpoint? I think I like this option more. This means that I don't have to worry about syncing all IP pools to show which is the default one.

Another option might be to add a `default_ip_pool` to the silo update endpoint, this way with a silo read you'll know which IP Pool is the default one. This correlation makes more sense to me? What do you think?
