### ISSUE TITLE
IP Pools: include `is_default` value in the list/get ip pool response

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4005]
The `is_default` attribute is currently missing from the get response body. It'll be useful for the admin to know whether a default pool is made for a silo and which one it is, instead of relying on the name or description to provide that information.

**Comment by rmustacc** [comment]
Should this be on the IP pool or just something that's on the silo? I think a given pool's default status is going to change a bunch especially with project defaults.

**Comment by david-crespo** [comment]
See https://github.com/oxidecomputer/omicron/issues/4002#issuecomment-1701740307 — I was thinking the same @rmustacc. The association could be its own entity. That doesn’t preclude putting together a nice view of all the default pools together.

**Comment by david-crespo** [comment]
I'm going to add `is_default` to the `IpPool` view for now for consistency because it's already on the model, but be assured I still plan on reworking on the data model.
