### ISSUE TITLE
test problem: oximeter-db `client::tests::test_build_replicated`: Failed to detect ClickHouse subprocess within timeout

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#4037]
The ubuntu test job is failing starting with #3494.

https://github.com/oxidecomputer/omicron/runs/16523076672
https://github.com/oxidecomputer/omicron/runs/16524864717
https://github.com/oxidecomputer/omicron/runs/16528790532 (re-run of the above commit)

**Comment by smklein** [comment]
FYI @karencfv

**Comment by karencfv** [comment]
Will leave this issue open until the test is stable
