### ISSUE TITLE
[ClickHouse] DistributedEngine configuration

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#4043]
The ClickHouse replicated SQL makes use of `DistributedEngine` tables. While we don't have any shards in place as of now, it is a preventive measure in case we decide to add any in the future.

Currently, we write and read directly to/from the `DistributedEngine` tables which in turn write to the `ReplicatedMergeTree` tables. This works, but we should research if this is the best way forward, or if we should write to the `ReplicatedMergeTree` tables, and query the `DistributedEngine` tables.

Related ClickHouse documentation: https://clickhouse.com/docs/en/engines/table-engines/special/distributed#distributed-writing-data

cc @bnaecker

**Comment by andrewjstone** [comment]
I'm pretty sure we've settled on writing directly to the `DistributedEngine` tables, and that's what we do in all our tests. This allows fault tolerance when we do have shards so that the available nodes can be chosen.
