### ISSUE TITLE
wicketd preflight uplink: Break up A / AAAA DNS querying

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#4044]
Currently, the `preflight uplink` check provided by wicketd uses [AsyncResolver::lookup_ip()](https://docs.rs/trust-dns-resolver/0.22.0/trust_dns_resolver/struct.AsyncResolver.html#method.lookup_ip) to query DNS servers. Internally, this uses the default lookup strategy, [LookupIpStrategy::Ipv4thenIpv6](https://docs.rs/trust-dns-resolver/0.22.0/src/trust_dns_resolver/config.rs.html#749-751). If _anything_ goes wrong with the IPv4 (A) lookup, [the error is silently discarded](https://docs.rs/trust-dns-resolver/0.22.0/src/trust_dns_resolver/lookup_ip.rs.html#438) and the result of the IPv6 (AAAA) lookup is returned.

Yesterday we saw an instance of preflight uplink consistently reporting "AAAA record not found" errors when performing lookups against the _first_ DNS server in the list provided. The name being queried only had A records, and they were served by all DNS servers. If we swapped the order of the DNS server list, it was consistently the first in the list that failed; if we added a dummy non-server IP as the first entry, it would fail (as expected), but then all the remaining (real) DNS servers succeeded. A `truss` capture shows several `sendto()` calls that were not followed by `recvfrom()`s:

```
/123:   sendto(28, .., 37, 32768, 0xFFFFF5FFCF7F1450, 16) = 37
/129:   sendto(28, .., 37, 32768, 0xFFFFF5FFCDFF1450, 16) = 37
/122:   sendto(28, .., 37, 32768, 0xFFFFF5FFCFBF1450, 16) = 37
/122:   sendto(28, .., 37, 32768, 0xFFFFF5FFCFBF1450, 16) = 37
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/123:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFCF7F1330, 0xFFFFF5FFCF7F146C) = 65
/125:   sendto(28, .., 42, 32768, 0xFFFFF5FFCEFF0B30, 16) = 42
/116:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFD13F0A10, 0xFFFFF5FFD13F0B4C) = 102
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/116:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFD13F1330, 0xFFFFF5FFD13F146C) = 81
/125:   sendto(28, .., 37, 32768, 0xFFFFF5FFCEFF1450, 16) = 37
/123:   recvfrom(28, .., 2048, 0, 0xFFFFF5FFCF7F1330, 0xFFFFF5FFCF7F146C) = 81
```

Our theory is that _something_ in the networking stack is not fully set up when we start the DNS queries, so the initial A query times out. After that timeout, we issue the AAAA query, and the network is ready, but we get a "record not found" error (which is expected if we're querying for AAAA when only A exists). To confirm and improve this, we should:

1. Perform separate A and AAAA queries ourselves instead of letting `lookup_ip()` do it for us; this will allow us to report and inspect specific errors from either query
2. If the A query fails for I/O-related issues (timeout, network not reachable, etc. - we're not sure exactly what error we'd see here), we should retry up to some limit

**Comment by leftwo** [comment]
DTrace and truss output files can be found here: /net/catacomb/data/staff/core/omicron-4044
