### ISSUE TITLE
Validate CN and/or SAN in certificate matches external dns zone during RSS.

### ISSUE THREAD

**Issue by luqmana** [oxidecomputer/omicron#4045]

**Comment by augustuswm** [comment]
This would be useful as another preflight tool that could be run once a cert has been uploaded and the `external_dns_zone_name` value has been set.

**Comment by luqmana** [comment]
Yup, we already do some basic validation like making sure the cert and key match up. So good to catch this earlier as well.

**Comment by leftwo** [comment]
Yeah, there is only so much we can do but any additional verification we can do before running RSS would be great.

**Comment by jgallagher** [comment]
https://github.com/oxidecomputer/omicron/pull/3436 has a bunch of extra checks that we can do at wicketd-upload time, but it fell off my radar. I'll try to get back to it soon.

**Comment by luqmana** [comment]
Looking a lil more, we should probably do this not just during RSS but at Silo & Certificate creation in general. You can easily run into this just by creating a silo and giving it a mismatched cert.
