### ISSUE TITLE
[ClickHouse] Schema updates

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#4048]
There should be a mechanism that allows us to perform schema updates without having to wipe everything out.

CockroachDB does schema updates this via [DB schema migration](https://github.com/oxidecomputer/omicron/tree/main/schema/crdb) https://github.com/oxidecomputer/omicron/pull/3760/

https://github.com/oxidecomputer/omicron/pull/4246 introduces a destructive mechanism to update Oximeter's database, via the OXIMETER_VERSION constant.

**Comment by davepacheco** [comment]
Despite the title of #3760, I don't think we do CockroachDB schema migrations automatically (on boot).

**Comment by karencfv** [comment]
Thanks! I'll update the issue's descritpion

**Comment by bnaecker** [comment]
Closed by #4394
