### ISSUE TITLE
Want to run `oximeter` in standalone mode

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#4063]
Running `oximeter` currently requires nearly the entire control plane. In addition to `oximeter` itself, one needs `nexus` to assign metric producers to collectors; CockroachDB to record that assignment; and ClickHouse for `oximeter` to insert data. This is all pretty heavyweight, especially if one wants to test just things like the basic accuracy of the metrics collected by `oximeter`.

It would be very helpful to have an `oximeter-standalone` binary. This would run the collector more or less as usual, but without any of the other components. It could be pointed directly at a producer; collect its metrics periodically; and simply print them. The `oximeter-client` may be useful here, or we could just start up a binary with the producer's endpoint directly.

A slightly more full-featured version might tell `oximeter-standalone` how to reach ClickHouse, in which case data would be inserted into the database as well. This might be useful for developing query tools, for example.

**Comment by jordanhendricks** [comment]
This would be great! I really wanted to be able to do this when I was reproducing and testing the fix for oxidecomputer/propolis#497.

**Comment by bnaecker** [comment]
Closed by #4117
