### ISSUE TITLE
clickhouse test runner puts preprocessed configs into current directory

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#4080]
I noticed this running `omicron-dev run-all`, after which I had a local directory called `preprocessed_configs`.  It seems like this should honor the TMP/TMPDIR/etc. environment variables that say where to put temporary files, rather than putting stuff in the current working directory.  (CC @karencfv?)

**Comment by bnaecker** [comment]
I'm pretty sure ClickHouse just does this unconditionally, which is very annoying.

**Comment by davepacheco** [comment]
It seems to be checking a few lines above that if some path is empty:
https://github.com/ClickHouse/ClickHouse/blob/00fcb8aceb08f20babf6ca0a93abd944e18c980b/src/Common/Config/ConfigProcessor.cpp#L837

Might that be something we can control?  Or if not, would it be easy to run Clickhouse out of $TMPDIR?

**Comment by bnaecker** [comment]
Yeah, that's true. The code is set up to allow saving somewhere else, but it seems to [only be called with an empty string](https://github.com/ClickHouse/ClickHouse/blob/a54a7b726d3b3594a875a4c600709bccb184543e/src/Daemon/BaseDaemon.cpp#L770). That means it's always `$PWD`.

**Comment by davepacheco** [comment]
I noticed that if I run `omicron-dev run-all` and `cargo test -p omicron-nexus` concurrently, I wind up with _two_ preprocessed_configs directories: one at the root of the workspace and one inside ./nexus.  This suggests two things:

1. I assume many of the Nexus tests might be setting up Clickhouse concurrently, but they seem to be using one "preprocessed_configs" path, so it seems like they might be stomping on each other.  This might be working by accident?  Might it be a source of future test flakes?
2. It wouldn't be enough to just run it out of TMPDIR instead.  We'd want to create a temporary directory for each run and chdir to that.  (I think we already create such a directory for the database itself.)

**Comment by bnaecker** [comment]
> I assume many of the Nexus tests might be setting up Clickhouse concurrently, but they seem to be using one "preprocessed_configs" path, so it seems like they might be stomping on each other. This might be working by accident? Might it be a source of future test flakes?

I think it could, yeah. We're always using the same configuration, so the resulting files should be the same. But it's definitely possible that this creates issues, and will cause problems if those config files are not the same.

> It wouldn't be enough to just run it out of TMPDIR instead. We'd want to create a temporary directory for each run and chdir to that. (I think we already create such a directory for the database itself.)

Makes sense. Changing to the tempdir we already make for data seems like a good idea.
