### ISSUE TITLE
CRDB schema change tests not covering constraints on indices sufficiently

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#4143]
See https://github.com/oxidecomputer/omicron/pull/4141 for context -- I haven't dug into the root issue here, but the minimal repro case is:

dbinit.sql:
```sql
CREATE INDEX IF NOT EXISTS lookup_zpool_by_disk on omicron.public.zpool (        
    physical_disk_id                                                             
) WHERE physical_disk_id IS NOT NULL AND time_deleted IS NULL;
```

up1.sql:
```sql
CREATE INDEX IF NOT EXISTS lookup_zpool_by_disk ON omicron.public.zpool (physical_disk_id, id) WHERE time_deleted IS NULL; 
```

These are not the same, but appear to be passing the `dbinit_equals_sum_of_all_up` test within https://github.com/oxidecomputer/omicron/blob/9a1f6bc5da1efed13dabbe14ec5066002cfd0851/nexus/tests/integration_tests/schema.rs .

My suspicion: More tables from https://www.cockroachlabs.com/docs/stable/information-schema need to be compared.

**Comment by davepacheco** [comment]
Just to be super explicit: it's both the list of columns on the index and the `WHERE` clauses that differ in this case.

**Comment by smklein** [comment]
For the differing-columns case of:

```sql
CREATE INDEX IF NOT EXISTS lookup on omicron.public.zpool (
    physical_disk_id
) WHERE physical_disk_id IS NOT NULL AND time_deleted IS NULL;
```
vs
```sql
CREATE INDEX IF NOT EXISTS lookup2 on omicron.public.zpool (
    physical_disk_id, id
) WHERE physical_disk_id IS NOT NULL AND time_deleted IS NULL;
```

I can observe the difference - it's in the "implicit" column of [information_schema.statistics](https://www.cockroachlabs.com/docs/stable/information-schema#statistics).

```
root@pop-os:26257/defaultdb> SHOW INDEXES FROM omicron.public.zpool;
  table_name |       index_name       | non_unique | seq_in_index | column_name  | direction | storing | implicit
-------------+------------------------+------------+--------------+--------------+-----------+---------+-----------
...
  zpool      | lookup                 |    true    |            1 | phys_id      | ASC       |  false  |  false
  zpool      | lookup                 |    true    |            2 | id           | ASC       |  false  |   true
  zpool      | lookup2                |    true    |            1 | phys_id      | ASC       |  false  |  false
  zpool      | lookup2                |    true    |            2 | id           | ASC       |  false  |  false
```

I can start checking for this distinction, and add a regression test.

**Comment by smklein** [comment]
For the differing-where-clause case, however, I'm not as lucky. From the perspective of [information_schema.statistics](https://www.cockroachlabs.com/docs/stable/information-schema#statistics), the two indices look identical, even though they are not.

**Comment by smklein** [comment]
I found https://www.cockroachlabs.com/docs/stable/pg-catalog which appears to have a more exhaustive description of the schema than `information_schema`. This should work for comparing partial indexes.

**Comment by smklein** [comment]
/me Sighs a big sigh of relief that we don't appear to have broken anything in the existing schema upgrades (... at least, so far).

All existing schema changes appear to pass with the new validation in https://github.com/oxidecomputer/omicron/pull/4152 and https://github.com/oxidecomputer/omicron/pull/4153
