### ISSUE TITLE
[ClickHouse] Data migration

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#4155]
There should be a mechanism that allows us to perform data migration.

[`remote()`](https://clickhouse.com/docs/en/sql-reference/table-functions/remote) and [`ATTACH_PARTITION`](https://clickhouse.com/docs/en/sql-reference/statements/alter/partition) seem like a good start.

**Comment by andrewjstone** [comment]
@karencfv Are we actually planning on doing this now that we almost have replicated clickhouse up and running and the plan listed in RFD 468?

I think that we will want to support backup of our clusters, but we shouldn't need migration.

**Comment by karencfv** [comment]
Yeah, probably not. If we do end up doing a migration for whatever reason we can just create a new issue
