### ISSUE TITLE
[ClickHouse] Cluster configuration testing

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#4156]
We have a test that validates that our db-replicated-init.sql  works as expected on a clustered ClickHouse deployment. However, those tests are run against a deployment where all the server and keeper nodes run on the same host. This means that the configuration files are different to what the actual configuration files that we deploy on the rack are.

As of now (sept/23) it is not possible to test multinode clusters, but leaving this issue here for when we can.

**Comment by andrewjstone** [comment]
We're going to test on a4x2 and possibly madrid as part of enabling the policy via OMDB. That will close out the tracking issue in #https://github.com/oxidecomputer/omicron/issues/5999

We also have a lot of tests for the planner right now and integration tests via clickward. I'm not sure that we need to keep this open, as I'm not planning to put any notes here.

**Comment by karencfv** [comment]
Yeah, let's close this. This issue was from a year ago and things have changed significantly since then
