### ISSUE TITLE
CI `package` job fails due to transient buildomat errors

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#4165]
Here's an example job:
https://buildomat.eng.oxide.computer/wg/0/details/01HBF0GRNYXR6RMJPSX95W8XMQ/A1WlUdHz8EzlmcZaxISu2UH2EYg66WKMc4cO1GbM1Dv04dRF/01HBF0K57K97G3Q1EHYFRGERWZ

I am not positive but looking at .github/buildomat/jobs/package.sh, we're running `ptime -m cargo run --locked --release --bin omicron-package -- -t test package`, we just finished the cargo build step, and `omicron-package` is emitting this error:

```


2087 | 2023-09-28T23:43:45.735Z | Error: failed reading response from https://buildomat.eng.oxide.computer/public/file/oxidecomputer/crucible/image/aeb69dda26c7e1a8b6eada425670cd4b83f91c07/crucible-pantry.tar.gz
-- | -- | --
2088 | 2023-09-28T23:43:45.932Z |  
2089 | 2023-09-28T23:43:46.303Z | Caused by:
2090 | 2023-09-28T23:43:47.327Z | 0: request or response body error: error reading a body from connection: end of file before message length reached
2091 | 2023-09-28T23:43:47.592Z | 1: error reading a body from connection: end of file before message length reached
2092 | 2023-09-28T23:43:47.869Z | 2: end of file before message length reached
```

I gather from @jclulow that the expectation of buildomat is like that of other cloud services: it may fail transiently at any time.  It seems like `omicron-package` needs to retry downloads of prebuilt artifacts?  @smklein does that sound right?

**Comment by smklein** [comment]
Fix is up at https://github.com/oxidecomputer/omicron/pull/4168 , the retry behavior can be tweaked via the CLI.
