### ISSUE TITLE
Revisit moving instances to Failed in `handle_instance_put_result`

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#4226]
Follow-up from the refactoring in #4194.

If Nexus calls sled agent to do something that registers an instance or changes its state, sled agent will try to return a `Result<Option<SledInstanceState>, Error>`. Nexus will then get back one of the following values:

- `Ok(None)` if the call succeeded and this didn't change what sled agent thinks the instance/VMM state is
- `Ok(Some(new_state))` if the call succeeded and sled agent wants Nexus to try to write some new state back to CRDB
- `Err(e)` if the call failed, where `e: progenitor_client::Error<sled_agent_client::Error>`

The first two cases are handled by simply trying to write a state update to CRDB and aren't important here. The error case, however, walks a tightrope: https://github.com/oxidecomputer/omicron/blob/2bb0fdc6237ce6b024fb21dc1c1ebe54a4247d41/nexus/src/app/instance.rs#L891-L943

Nexus will take the Progenitor error it got back, feed it through a `From` impl to convert it to an Omicron external API error, and then see if that error is a Bad Request error or something else. In the former case, the update is dropped; in the latter case, Nexus assumes some catastrophe has happened and that the instance has to be marked as Failed.

The relevant From impl is here:

https://github.com/oxidecomputer/omicron/blob/c03029373982a528d372c68f3015506f15dd2a07/common/src/api/external/error.rs#L355-L418

Notice the following:

- Progenitor errors that didn't produce a response from sled agent--e.g. disconnections due to timeouts or network weather--all get turned into internal errors. These will cause an instance to move to Failed even if the problem was completely transient.
- Sled agent responses get flattened into either 400 Bad Request (for all 4XX errors) or 500 Internal Server Error (everything else) unless they happen to be 503 Service Unavailable, which is preserved. (See #3238.)

This creates a great many ways for an instance to be marked as Failed, even if the VM is actually perfectly healthy. The Failed state is also a pain to deal with because a Failed instance can only be deleted and not recovered in any other way (see #2825 and especially https://github.com/oxidecomputer/omicron/issues/2825#issuecomment-1650601195).

Apart from all of this, an instance can be marked as Failed because of a *Propolis* failure: for example, if Propolis hits an error while setting up a VM component, it will publish the Failed state and that will bubble back up to Nexus via sled agent.

We should consider a subtler approach to all this. One possible starting place is to distinguish Propolis failures (which really do mean "this VM is dead") from errors accessing the instance from the control plane. We could then, e.g., indicate the latter faults without necessarily changing the instance state, allow further attempts to try to change the instance's state from its last-known state, and/or try to recover connectivity to the instance from a background task.

**Comment by hawkw** [comment]
I think #6455, which implemented RFD 486's more principled rules for what sled-agent errors should move an instance to `Failed`, has closed this. @gjcolombo do you agree?

**Comment by gjcolombo** [comment]
Yeah, I think we've taken care of this one.
