### ISSUE TITLE
[oximeter] Updating the schema in Clickhouse should be non-destructive 

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#4271]
https://github.com/oxidecomputer/omicron/pull/4246 introduces a mechanism to update Oximeter's database, via the `OXIMETER_VERSION` constant.

This PR's mechanism is **destructive** -- any update wipes the database, and re-initializes it. Ideally, for ongoing changes, we'd have a mechanism that allows gracefully upgrading from one revision within the DB to another.

**Comment by karencfv** [comment]
Related: https://github.com/oxidecomputer/omicron/issues/4048

These two issues seem relatively similar. Do you mind if we keep just one? Or do you see each issue as a different stream of work?

**Comment by smklein** [comment]
Ah, I missed that one! We can combine the two issues.

**Comment by smklein** [comment]
This issue still exists, but is being tracked by #4048
