### ISSUE TITLE
investigate if non-semver system versions are fine

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#4400]
Requested by @askfongjojo in the huddle this morning.

Ideally the next system version would be named "v4". We set a system version in the package job:

https://github.com/oxidecomputer/omicron/blob/73c3571fe591af14bbe9c341f6ed4a4169446f91/.github/buildomat/jobs/package.sh#L39-L41

This is currently a semver. Need to validate whether this is treated as an opaque string or is actually parsed as semver and compared in current software.

**Comment by iliana** [comment]
There is also a larger release engineering question of how to differentiate between pre-release artifacts that are generated from some arbitrary commit, and what the actual resulting version is. Ideally this would happen during artifact signing.

If we determine it is too difficult to move to an integer version in the repo itself, we can move to e.g. `4.0.0-whatever`.

**Comment by askfongjojo** [comment]
@iliana: Thank you for filing this ticket to track the version question/investigation!

**Comment by askfongjojo** [comment]
Hey @iliana, it looks like we may be close to having a version 4 going out. It'll be great if we can bump the version string to a higher number today (`4.0.0-whatever` can work too! We just need it to be different from `1.0.3` - the one already deployed to customer racks). Thanks!

**Comment by iliana** [comment]
`system_version` is declared across wicket, tufaceous-lib, _and_ nexus as a `SemverVersion`. I think it is safe to say that we will need to keep it a semver for now; let's do `4.0.0` plus the current CI commit suffix we're using.

This does give us the opportunity to do point releases in the future if we decide we need to (as long as they comply with semver, lol).

**Comment by iliana** [comment]
Cross-referencing https://github.com/oxidecomputer/omicron/pull/4437; the investigation this issue calls for is complete.
