### ISSUE TITLE
Avoid IPv4 in the Network Underlay (IPv6 all the way!)

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#442]
At the time of writing, our SMF manifests use IPv4 addresses by default:

https://github.com/oxidecomputer/omicron/blob/8757ec542ea4ffbadd6f26094ed4ba357715d70d/smf/sled-agent/manifest.xml#L44-L46

These should transition to IPv6 addresses to align with the expected addressing on the system.

Related to: https://github.com/oxidecomputer/omicron/issues/332

**Comment by bnaecker** [comment]
This is related to #889
