### ISSUE TITLE
[wicket] "Running" count wrong in rack-update attach

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#4507]
![image](https://github.com/oxidecomputer/omicron/assets/180618/6ccb9b1d-2058-47ed-9491-98547de054d2)

Looks like an underflow?

**Comment by sunshowers** [comment]
The number shown is `2 ** 64 - 3`.

**Comment by sunshowers** [comment]
(From Matrix)

Still scratching my head regarding this -- I'm really not seeing how it's possible to underflow this in the code.

The value for `running` is `2 ** 64 - 3`. The 3 here matches the "3 completed", which seem to suggest that we never bumped `running` up for any of the running updates, and bumped it down by 3 for the 3 updates that succeeded. I'm finding it really hard to see how that could happen by looking at the code (the stats are managed by [`apply_result`](https://github.com/oxidecomputer/omicron/blob/ca9d90a79c2a7a9ffdca12a705d007d7f28ce61f/update-engine/src/display/group_display.rs#L238-L265), the inputs to which are generated by [`add_event_report`](https://github.com/oxidecomputer/omicron/blob/ca9d90a79c2a7a9ffdca12a705d007d7f28ce61f/update-engine/src/display/group_display.rs#L335).

There's a `before` and `after` there, and the only way the running count can underflow is that we (a) never returned `Running` as the `after` value before (b) returning `Running` as the `before` value in a call. I can't see a situation where that can happen.

Do you happen to have the full logs in your terminal by any chance?

**Comment by augustuswm** [comment]
We ran in to this during an update on 11/21. Notably we were updating 11 components (10 sleds, 1 switch). We say from the cli:

* Status 1/11: 18446744073709551615 running, 1 completed (after the switch had completed, but no sled had completed)
* Status 11/11: 18446744073709551605 running, 11 completed (after all sleds had completed)
