### ISSUE TITLE
Stop request for an instance with an abandoned VMM succeeds, returns state of "Running," and never stops the instance

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#4511]
Observed in dogfood with an instance that was running and not stopped before the rack was parked for update. This is very closely related to #725, but we might be able to mitigate it tactically without solving the entire "what to do when a sled reboots" problem described in that issue.

The specific problem here is that if an instance is Running, but isn't registered with its purported sled agent (e.g. because the sled rebooted and the agent lost the instance), a request to stop the instance will succeed but not change the instance's state. I originally did this intending to make stop requests idempotent:

https://github.com/oxidecomputer/omicron/blob/781ed1236489bb536506fb03ba1be39b34ed81a5/sled-agent/src/instance_manager.rs#L335-L351

But arguably this would be better to handle in Nexus instead: if sled agent can promise that a call to `ensure_state` returns a specific HTTP status code if and only if the instance is not known to that sled agent, then Nexus can reason as follows: "this sled doesn't know about this instance, so I, Nexus, own its state; and this was a request to stop, so I can try to update the state to reflect that the instance is actually stopped now."

**Comment by gjcolombo** [comment]
Discussed at the 9/26/24 hypervisor huddle. Sled agent's `InstanceManager::ensure_state` still has the problematic behavior here.

> But arguably this would be better to handle in Nexus instead: if sled agent can promise that a call to ensure_state returns a specific HTTP status code if and only if the instance is not known to that sled agent, then Nexus can reason as follows: "this sled doesn't know about this instance, so I, Nexus, own its state; and this was a request to stop, so I can try to update the state to reflect that the instance is actually stopped now."

Sled agent has such an HTTP error code now, so it just needs to return it in this particular case; Nexus can then decide whether to handle that code specially if the request was a request to stop (though I suspect it shouldn't--the relevant VMM should just be marked as Failed as with any other state change that tries to target an unexpectedly-nonexistent VMM).

**Comment by gjcolombo** [comment]
The `test_instance_failed_after_sled_agent_forgets_vmm_can_be_stopped` instance integration test actually checks this case, but it uses the simulated sled agent, which handles missing VMMs differently from the sled agent InstanceManager. If we make the instance manager's behavior match the simulated agent's I think we'll be on the right track here.

**Comment by hawkw** [comment]
Oh no...does the real life sled-agent not actually do the right thing? :grimacing:

**Comment by gjcolombo** [comment]
It appears not to: https://github.com/oxidecomputer/omicron/blob/9fb967ded78f188c2386ee5644fb1b5c799b6e11/sled-agent/src/instance_manager.rs#L644-L672
