### ISSUE TITLE
instances created on a build with issue #4512 are unstoppable

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#4558]
While debugging #4512 I created a few instances on a test rack. Now that #4512 has been fixed, I went to delete those instances. The stop call succeded from the perspective of the API client (both the console and the CLI), but the state of the instance did not move. The nexus logs for the attempt follow.

[log.txt](https://github.com/oxidecomputer/omicron/files/13453089/log.txt)

On rack 2 these instances are still running at

- darmok-and-jalad/adrel
- darmok-and-jalad/uzani

**Comment by askfongjojo** [comment]
The instances seem to be stuck in the same way as instances that aren't stopped prior to rack update (when we explicitly delete all the propolis zones) or during sled-agent restart (which would also delete all the zones). The only way to get out of the situation currently is to reboot the instance. Reboot causes the sled-agent to move the instance to failed state and the VM should become removable. I just tried rebooting the `adrel` instance (but left the second one as is).

**Comment by rcgoodfellow** [comment]
Ah ok. Confirmed that rebooting goes to failed and I can delete the instance from the failed state. It's likely this was the underlying cause, having been up across update cycles. I'm guessing we're already tracking that elsewhere and I can close this @askfongjojo?

**Comment by askfongjojo** [comment]
Yes, failed instances can be deleted by end users to reclaim the data on disk. The long-term fix for handling running instances is tracked in #3633.
