### ISSUE TITLE
Proper Rust-based CLI

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#458]
`oxapi_demo` has served us well, but we should really have a real CLI. Now that we have good client generation, it shouldn't be hard to write a CLI wrapper for the generated client that at least gets us started.

**Comment by ahl** [comment]
FWIW I've got a local branch where I've been extending progenitor to emit a CLI. This would be very much like the aws-cli which is almost 1:1 with their API. This may be what you're talking about or it may be complementary.

**Comment by david-crespo** [comment]
That would certainly be enough to replace `oxapi_demo`, which is the main thing I have mind.

**Comment by zephraph** [comment]
@jessfraz is working on this over at https://github.com/oxidecomputer/cli
