### ISSUE TITLE
Floating IP delete/attach/detach should be fully contained in transactions

### ISSUE THREAD

**Issue by FelixMcFelix** [oxidecomputer/omicron#4628]
As of #4559, the above 3 operations use a fetched `FloatingIp`/`ExternalIp` to provide user-friendly error messages based on the current state of `parent_id`, before firing an UPDATE query conditioned on the correct `parent_id` field.

While this is not incorrect, this will provide a less user-friendly error message in the event of concurrent modification. We should move these datastore methods into a `transaction` and/or `transaction_retry_wrapper` to clean this up.

**Comment by bnaecker** [comment]
I'm pretty confident one can do this without an interactive transaction (with multiple DB roundtrips). Instead, the `update_and_check()` machinery could be used to attach or detach a floating IP with the desired conditions, such as `parent_id IS NULL` or similar.

**Comment by FelixMcFelix** [comment]
That looks like just the ticket, thanks! I hadn't yet come across it -- I'll see about working that in as a solution alongside #4630.
