### ISSUE TITLE
Remove articles from endpoint summaries

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4741]
They're just noise IMO.

<img width="254" alt="image" src="https://github.com/oxidecomputer/omicron/assets/3612203/99d4762a-72f2-4fc7-9738-dbc0c58eaa13">

<img width="249" alt="image" src="https://github.com/oxidecomputer/omicron/assets/3612203/8370bb4e-1137-4ad4-999a-a228becacfd3">

Example spot:

https://github.com/oxidecomputer/omicron/blob/9274beb0112e50014e8f14cba2f3fbec17a64421/nexus/src/external_api/http_entrypoints.rs#L1911

**Comment by benjaminleonard** [comment]
I agree – happy to make the change unless there' strong protestations from @ahl

**Comment by ahl** [comment]
That would be great. I would encourage a thorough scrub of all description fields.

**Comment by david-crespo** [comment]
It turns out chatgpt is really good at this. Too bad it's not very easy to pipe these back into the file.

https://gist.github.com/david-crespo/446b662ae34ee2d77b5f2f85d37bf527

**Comment by david-crespo** [comment]
Just kidding. I had it write me a giant `sed`.

https://gist.github.com/david-crespo/b5cd941045dc518a61e1eab1a5d1f50e
