### ISSUE TITLE
Nexus rejected a valid certificate chain due to intermediate CN error

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4743]
The Letsencrypt cert failed to be imported as Nexus incorrectly flagged a CN validation error:
```
error; status code: 400 Bad Request
{
  "error_code": "InvalidValue",
  "message": "unsupported value for \"certificate\": Certificate not valid for given hostnames \"oxide.sys.rack2.eng.oxide.computer\": CN: R3",
  "request_id": "598d7872-7965-4fca-8f01-b27969b3ed2b"
}
```
The CNs in the cert:
```
$ curl -fsSL https://lab.eng.oxide.computer/rack2_wildcard/fullchain.pem | openssl x509 -text -noout | grep CN
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Subject: CN = *.sys.rack2.eng.oxide.computer
```
Per @jgallagher
> We’re using OpenSSL’s hostname validation: https://github.com/oxidecomputer/omicron/blob/9274beb0112e50014e8f14cba2f3fbec17a64421/certificates/src/openssl_ext.rs#L54

**Comment by askfongjojo** [comment]
Ugh this is a user error, sorry about the confusion. What happened was that the first line of the cert file was missing a "dash". The openssl on MacOS doesn't complain about it (when viewing the cert content) but it doesn't pass Nexus validation.

**Comment by jgallagher** [comment]
I poked at this a bit to see if we could get a better error message, but AFAICT we're at the mercy of OpenSSL here. We use [`X509::stack_from_pem()`](https://github.com/oxidecomputer/omicron/blob/df67a572756e0f348526a4a86ef691e4e917c6e1/certificates/src/lib.rs#L118) to parse the cert chain, which appears to have the same behavior as command line OpenSSL: if there's something wrong with the `BEGIN CERTIFICATE` header (e.g., missing a dash) for one of the certs, it will be _silently skipped_. E.g.:

```
# Correct fullchain.pem: 3 certs in chain
% openssl crl2pkcs7 -nocrl -certfile fullchain.pem | openssl pkcs7 -print_certs -text -noout | grep Subject:
        Subject: CN=*.sys.rack2.eng.oxide.computer
        Subject: C=US, O=Let's Encrypt, CN=R3
        Subject: C=US, O=Internet Security Research Group, CN=ISRG Root X1
```

```
# Remove a dash from the header of the first cert
% openssl crl2pkcs7 -nocrl -certfile fullchain-missing-dash.pem | openssl pkcs7 -print_certs -text -noout | grep Subject:
        Subject: C=US, O=Let's Encrypt, CN=R3
        Subject: C=US, O=Internet Security Research Group, CN=ISRG Root X1
```

```
# Remove a dash from the header of the second cert
% openssl crl2pkcs7 -nocrl -certfile fullchain-missing-dash.pem | openssl pkcs7 -print_certs -text -noout | grep Subject:
        Subject: CN=*.sys.rack2.eng.oxide.computer
        Subject: C=US, O=Internet Security Research Group, CN=ISRG Root X1
```

I looked around the OpenSSL docs but couldn't find a way to say "parse this PEM file and give me an error if it's malformed". :-/
