### ISSUE TITLE
Want a way to test data migrations

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4747]
While working on #4261, I found it hard to get confidence in my data migrations using existing tooling. One thing I found helpful was using DB Fiddle to write some similar tables and running similar migrations on them to make sure I got the expected results.

https://www.db-fiddle.com/f/pzmM69My6mZWq1NEKm56PG/1

However, this is lacking in ways that formal tooling could improve on:

1. It's Postgres 15, not CRDB, and especially not the version of CRDB we're running
2. The tables are simplified because making them match exactly is annoying to do by hand, even though it would be easy to do automatically

So what I have in mind is essentially a way of:

1. Running migrations up to but not including the one under test
2. Running some SQL to insert rows in the DB
3. Running the migration under test
4. Asserting stuff about the resulting DB state

**Comment by smklein** [comment]
https://github.com/oxidecomputer/omicron/blob/cfcf209c4f4b278bbfe27d19c115d657c63b5d76/nexus/tests/integration_tests/schema.rs#L479-L506 and https://github.com/oxidecomputer/omicron/blob/cfcf209c4f4b278bbfe27d19c115d657c63b5d76/nexus/tests/integration_tests/schema.rs#L808-L850 seem *close* to what you're describing for (1), but it's unfortunately not super cheap to perform "all schema upgrades in order from 1.0.0 to latest". I've been eyeing these tests anyway for optimization purposes, so I wonder if we could share that workload somehow.

(That said, the idea of "update to right before my schema change, populate some test data, do the change, then validate the state" seems super reasonable)
