### ISSUE TITLE
Give end user a way to tell which IP pool is silo default

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4752]
#4261 makes `is_default` a property of the link to the silo (`IpPoolSilo`) and not of the `IpPool` itself, which means that when `/v1/ip-pools` lists `IpPool`s for the current silo, there is no way to tell which is the default, i.e., which one instance create will pull an IP from if they don't specify a pool.

The fastest way to do this would be to add `is_default: true` to the default pool in the list (if there is one). What gives me pause is that it means the endpoint no longer returns the same `IpPool` object that we are using in all the other endpoints — this one now has an `is_default` property, so it would need to be a new struct. Maybe that's fine.

Another (probably worse) approach would be to add another endpoint like `/v1/ip-pools/default` (that path only makes sense if we don't intend to add `/v1/ip-pools/{name-or-id}`, and we probably do intend to for symmetry even though it's not very important). That way `/v1/ip-pools` would not have to change, but we could still hit this other endpoint in the console to show which is the default. I am inclined against this because only the console would really benefit from it — a CLI or SDK consumer would have to do extra work to match what we do in the console.

**Comment by karencfv** [comment]
> The fastest way to do this would be to add is_default: true to the default pool in the list (if there is one). What gives me pause is that it means the endpoint no longer returns the same IpPool object that we are using in all the other endpoints — this one now has an is_default property, so it would need to be a new struct. Maybe that's fine.

Why can't we add the `is_default` field to the IpPool object that is used for all the other endpoints?

**Comment by david-crespo** [comment]
Because after #4261, a pool is default or not for a particular silo, so if they’re just listed across all silos, like a fleet admin listing all pools, there is no single value for is_default for a given pool. You’d have to list silos where it’s the default. Only when pools are listed in the context of a particular silo is there a well-defined single answer for is_default.

**Comment by karencfv** [comment]
Ah! Gotcha. Hmm, then I think you're right. Your first option of returning a slightly different object for the list command makes sense :thinking: Not sure I can think of a better option
