### ISSUE TITLE
Need operator endpoint to list IP pools for a silo

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4763]
#4261 allows operators to list linked silos for a specified IP pool and allows non-operators to list available pools in their silo only. But it is probably more natural for the operator to think in the latter way as well: for a given silo, what are the IP pools available (and which is the default).

**Comment by askfongjojo** [comment]
Marking this for the v6 release for visibility. Please re-target if needed. Thanks.
