### ISSUE TITLE
Test flake: Failed to start ClickHouse keeper 1: waiting to discover if ClickHouse is ready for connections

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#4782]
Seen at https://github.com/oxidecomputer/omicron/pull/4780/checks?check_run_id=20282268352 with `oximeter-db client::tests::test_ensure_schema_walks_through_multiple_steps_replicated`.

We currently don't upload ClickHouse logs for failing tests -- we should probably start doing that.

**Comment by sunshowers** [comment]
nvm, this was an issue with https://github.com/oxidecomputer/omicron/issues/4780.

**Comment by karencfv** [comment]
:sweat_smile:
