### ISSUE TITLE
Invalid IP pool error when creating instances with ephemeral IP address

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4806]
This happens after the removal of fleet-level IP pool. Regardless of whether a silo has a custom default IP pool or no default originally, and whether I specified the bulit-in "default" pool or a pool that I created, I'm getting the following error:
```
error; status code: 404 Not Found
{
  "error_code": "ObjectNotFound",
  "message": "not found: ip-pool with id \"Default pool for current silo\"",
  "request_id": "47276fc3-a859-4566-9bf1-1eb5b8e04678"
}
```
There are two bugs according to @david-crespo:
1. The select SQL that determines the pools available returns duplicate values instead of distinct values if a pool is mapped to more than one silo (in this case, it's the one built-in "default" pool).
2. The software update data migration did not set a default pool if a silo has one or more custom pools but none of them has `is_default` set to `true`.

**Comment by david-crespo** [comment]
Instance create with default network settings (1 ephemeral IP from default pool) now works on dogfood. I flipped pool `default` to have `is_default: true` for the `oxide` silo.
