### ISSUE TITLE
Ability for fleet admin to see which IP pools a silo is associated with

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4818]
Increasing the visibility of IP pool information to the fleet admin will be useful for ensuring proper IP pool configuration. To achieve that, we'd want:
1. Presenting default IP pool information as part of the silo GET response, as discussed in #4005
2. Provide a way to list all IP pools associated with a given silo and indicate which one is set as the default

The 2nd one is probably more useful and consistent with the API atomicity pattern. @david-crespo - thoughts?

**Comment by david-crespo** [comment]
Planning on 2, covered in https://github.com/oxidecomputer/omicron/issues/4763

**Comment by askfongjojo** [comment]
Ah ok, sorry for missing to find that ticket. This is certainly a dup.
