### ISSUE TITLE
Publish per-instance vCPU usage information to `oximeter`

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#4851]
Information about vCPU usage for each instance is maintained by the hypervisor in a set of `kstat`s:

- `vmm` is the module, with an integer instance that is unique per VMM.
- `vmm::vm:vm_name` lists the instance's UUID as its name. We may not need to collect this through `kstat`s since we already have it in the sled agent, but it exists.
- There are per-vCPU statistics which provide the cumulative time (in nanoseconds, through `gethrtime()`) in a number of microstates:
  - `time_emu_kern` tracks emulation performed in kernel space
  - `time_emu_user` tracks emulation performed in userspace
  - `time_idle` tracks idle time, such as when the guest is halted
  - `time_init` is time prior to the guest running at all
  - `time_run` is, well, when the guest is running
  - `time_sched` is time off-CPU, such as during for an interrupt or waiting for a lock

We should publish these to `oximeter`. It might make sense to track the state as an enum (string in ClickHouse), so that we can easily aggregate over it, or break out the usage by state. 

We should also include metadata about the instance itself, including at least the silo, project, and instance UUIDs.

**Comment by gjcolombo** [comment]
A couple of thoughts: Do we want to gather these from sled agent or from Propolis itself? (*Can* we gather them from Propolis given that's running in a zone?) To me there's something Neat and Tidy about having VMMs produce statistics describing their own components, but I'm not sure there are any *technical* advantages to that, at least as far as kstat gathering is concerned. (Would implementing this in sled agent require that sled agent remember the number of CPUs each instance has? I'm not sure it actually remembers that today.)

**Comment by bnaecker** [comment]
It looks like the zones are indeed able to get `kstat`s, at least through the command line tool. That suggests that Propolis could do the work too. One advantage to the sled-agent doing the work is that it already has to troll through `kstat`s for the physical data link stats (and presumably more in the future). But I don't feel strongly about it.

As far as the number of vCPUs, the sled-agent currently does accept that in the instance-creation request, and it looks like it stores it in the `InstanceInner.properties.vcpus` field. But even if it did not do that, the vCPU is indexed in the `kstat` name as well, such as `vmm:0:vcpu0:time_idle`, so we could pull it out of there if needed. I think it'd be better to use the instance properties to find the right kstats though.

**Comment by bnaecker** [comment]
The silo / project IDs are not currently part of the [`InstanceEnsureBody`]](https://github.com/oxidecomputer/omicron/blob/1ae97e49d8698974989fe23ba5e5a8c421a24949/sled-agent/src/params.rs#L87), so they'll need to be added as part of this work.

**Comment by bnaecker** [comment]
After conversations with folks more familiar with Propolis, I think the actual publishing of these data to `oximeter` will be handled by Propolis. This Omicron-specific work will be split into a few smaller chunks:

- [ ] Add basic definitions of the relevant `oximeter::Target`s and `oximeter::Metrics` into `oximeter-instruments`. There's a bit of a judgement call here, since these definitions could also live in Propolis, where the data will be produced. I'm inclined to keep them in `oximeter-instruments` behind a feature-gate, for a few reasons: (1) other code may need those definitions, (2) they're produced via `kstat`s and the `KstatSampler` type lives in `oximeter-instruments`. But I'm open to moving them over to Propolis if it makes sense, after prototyping further.
- [ ] Update the sled-agent API to accept metadata about an instance needed for those statistics. That's currently the silo ID and project ID, but we may want to extend that with more data.
- [ ] A PR in Propolis to actually generate the vCPU stats. That's currently a WIP on [this branch](https://github.com/oxidecomputer/propolis/tree/vcpu-usage-stats).
- [ ] Update the Propolis dependency in Omicron, and pass the instance metadata from the sled-agent to Propolis in the instance-ensure requests.
