### ISSUE TITLE
test flake: 'integration_tests::sp_updater::test_sp_updater_delivers_progress' panicked at nexus/tests/integration_tests/sp_updater.rs:574:18

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#4911]
See 
- https://buildomat.eng.oxide.computer/wg/0/details/01HN4PESXPQF9QBHDEF7BDDCAW/JkbzZ4e3pCTe4Rf0JkcawMf5VsCMkGdlnSvzzfSrVvC4ph2E/01HN4PFAFKAMHTDE91X4W57BGK

**Comment by jgallagher** [comment]
I think I see from the logs what happened. Working on reproducing / fixing.
