### ISSUE TITLE
Exclude non-discoverable silos from list of linked silos for IP pool

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#4955]
Note that the fix here might be to avoid linking them to this pool in the first place rather than to directly exclude them from the list when we fetch them.

---

We show the `default-silo` and `oxide-internal` on the list of linked silos:
 
![Screenshot 2024-02-01 at 9 50 51 AM](https://github.com/oxidecomputer/omicron/assets/3612203/f7e0144a-571e-4a75-a7bf-c31ec5a36bae)

And we can even click on them and see a detail page:

<img width="1324" alt="image" src="https://github.com/oxidecomputer/omicron/assets/3612203/26226eb6-39cd-4710-9d66-c284104f2585">

But neither of these silos actually shows up in the list of silos shown to the operator, and rightly so!

![Screenshot 2024-02-01 at 9 52 58 AM](https://github.com/oxidecomputer/omicron/assets/3612203/35a66dcc-9341-4528-9665-c8148fe20e4b)

**Comment by zephraph** [comment]
non-discoverable silos strike again!
