### ISSUE TITLE
Change `FloatingIpCreate` `address` field to `ip` to match everything else

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#5046]
We should pick one or the other. To me, `ip` is clear and short and seems to be used in more places, but has the grammatical issue of being the IP of a `FloatingIp`. If that's fine we should probably stick with it. I don't like `address` as much.

https://github.com/oxidecomputer/omicron/blob/e1c3dd75b818147b545f9a46acfcf3fc19291473/nexus/types/src/external_api/params.rs#L879-L891

https://github.com/oxidecomputer/omicron/blob/e1c3dd75b818147b545f9a46acfcf3fc19291473/nexus/types/src/external_api/views.rs#L369-L379

The above is the user-facing disparity, but notably, the DB model and table use `ip`.

https://github.com/oxidecomputer/omicron/blob/e1c3dd75b818147b545f9a46acfcf3fc19291473/nexus/db-model/src/external_ip.rs#L131-L141

https://github.com/oxidecomputer/omicron/blob/e1c3dd75b818147b545f9a46acfcf3fc19291473/schema/crdb/dbinit.sql#L1726-L1727

**Comment by taspelund** [comment]
I expected to be quite opinionated about the terminology here, but I'm surprisingly not.  I think as long as we're consistent about using the same type and nomenclature everywhere, the actual nomenclature doesn't matter to me a whole lot.

Perhaps unrelated, but I think both `ip` and `address` get the point across in a version-agnostic (IPv4 / IPv6) fashion... assuming we want this API to eventually support both v4 and v6.

**Comment by david-crespo** [comment]
I believe the API already supports v4 and v6.
