### ISSUE TITLE
Allow direct triggering of inventory collection?

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#5058]
Currently, when adding a sled to a rack, I"m not able to generate a blueprint from a collection that exists. I have to wait for the next round of inventory collection which can take up to 10 minutes. I believe this is because the new sled isn't in the old inventory. Once the next collection is made things work as we expect.

I'm wondering if we should add an OMDB command to trigger a collection to speed up testing.

```
root@oxz_switch:~# omdb nexus blueprints generate-from-collection 0fe01f0a-9d18-4575-8d33-91b56f00ca12
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd00:1122:3344:102::5]:12221
Error: creating blueprint from collection id

Caused by:
    Error Response: status: 500 Internal Server Error; headers: {"content-type": "application/json", "x-request-id": "233de1ba-672b-410f-947a-7a52c90fc879", "content-length": "124", "date": "Wed, 14 Feb 2024 00:17:54 GMT"}; value: Error { error_code: Some("Internal"), message: "Internal Server Error", request_id: "233de1ba-672b-410f-947a-7a52c90fc879" }
root@oxz_switch:~# omdb db inventory collections list
note: database URL not specified.  Will search DNS.
note: (override with --db-url or OMDB_DB_URL)
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using database URL postgresql://root@[fd00:1122:3344:103::3]:32221,[fd00:1122:3344:102::3]:32221,[fd00:1122:3344:102::4]:32221,[fd00:1122:3344:101::4]:32221,[fd00:1122:3344:101::3]:32221/omicron?sslmode=disable
note: database schema version matches expected (33.0.1)
ID                                   STARTED              TOOK   NSPS NERRORS
0fe01f0a-9d18-4575-8d33-91b56f00ca12 2024-02-14T00:07:18Z 148 ms 5    0
0551af6b-4de7-4719-8bde-01a97c8d990f 2024-02-14T00:07:18Z 143 ms 5    0
36d00d44-91f2-41b5-97bf-9963adc4781f 2024-02-14T00:08:24Z 129 ms 5    0
908993fe-3c61-43a1-bd6b-5bbb48c94fce 2024-02-14T00:17:17Z 177 ms 5    0
a5e62f12-5b53-4881-b543-f2fd9287536d 2024-02-14T00:17:17Z 167 ms 5    0
root@oxz_switch:~# omdb nexus blueprints generate-from-collection a5e62f12-5b53-4881-b543-f2fd9287536d
note: Nexus URL not specified.  Will pick one from DNS.
note: using DNS server for subnet fd00:1122:3344::/48
note: (if this is not right, use --dns-server to specify an alternate DNS server)
note: using Nexus URL http://[fd00:1122:3344:102::5]:12221
created blueprint bf187e55-dc7d-4475-abab-8902953d7d60 from collection id
root@oxz_switch:~#
```

cc @davepacheco

**Comment by davepacheco** [comment]
Yeah, it seems useful to have a human interface for this.  It really belongs in the RFD 399 "Service and Support API" but it could go in the Nexus internal one for now.

But also, it sounds like we should activate the inventory collection background task from the add sled flow so that you don't have to do this automatically?

**Comment by andrewjstone** [comment]
> But also, it sounds like we should activate the inventory collection background task from the add sled flow so that you don't have to do this automatically?

That's a good idea. Maybe I'll take a stab at this tomorow.

**Comment by andrewjstone** [comment]
I don't think this is immediately necessary now that #5066 is in. Closing for now. We can always re-open as necessary or go ahead and add the real RFD 399 level support :)

**Comment by andrewjstone** [comment]
Re-opening as a result of https://github.com/oxidecomputer/omicron/issues/5111

**Comment by davepacheco** [comment]
As before, we can still do this.  In #5111, it looks like the reason this didn't happen automatically was a result of 1-2 bugs (client-side timeout followed by a 500 error).

**Comment by andrewjstone** [comment]
@sunshowers is working on this in https://github.com/oxidecomputer/omicron/issues/5058
