### ISSUE TITLE
Let Nexus control "when Physical Disks, Zpools, and Datasets are created", rather than relying on self-reporting from sleds

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#5151]
Blocked on #5150  (disks need to appear in inventory before we know they exist).

**Comment by davepacheco** [comment]
@smklein is this a blocker for the Q1 milestone (details in https://github.com/orgs/oxidecomputer/projects/44?pane=info project README)?

**Comment by smklein** [comment]
I believe it is, yes. I think this is a pre-requisite for making the lifecycle information work correctly - otherwise, Nexus and Sled Agent would both be able to create new "control plane physical disk" objects, which seems racy to me.

(TL;DR: I think it's doable, and I think trying to defer it would make the lifecycle more complicated + worse)

**Comment by smklein** [comment]
With #5172, this is done for "Physical Disks" and "Zpools".

"Datasets" are implicitly controlled by zone allocation. I'd like for them to be more explicitly managed. But I believe this is "done enough" for our Q1 goals.
