### ISSUE TITLE
Maybe track spawned spdm responders for debugging purposes

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#517]
In the current `trust_quorum::Server::run` code we spawn a responder for each connection, but we don't track it's lifetime or how many responders are currently in progress. We can track that with a [FuturesUnordered](https://docs.rs/futures/0.3.16/futures/stream/struct.FuturesUnordered.html). This may be useful for debugging.

**Comment by jgallagher** [comment]
SPDM was removed in favor of sockets as of #1182
