### ISSUE TITLE
Make Blueprint::all_omicron_zones take BlueprintZoneFilter as an argument

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#5315]
> I also have a question: Should `all_omicron_zones` also take a `BlueprintZoneFilter` as an argument? I'd do that in a subsequent PR since the blast radius of that would be bigger.

After reading the changes, I think I would very strongly vote "yes", and at that point we could probably drop `all_blueprint_zones` altogether? It looks like all the current callers of that are only using it because `all_omicron_zones` _doesn't_ take a filter.

_Originally posted by @jgallagher in https://github.com/oxidecomputer/omicron/issues/5238#issuecomment-2015223256_

---

We found at least one bug while looking at the code here -- quiesced zones were being deployed to external DNS.

All of the callsites need to take into account expunged zones -- which means that this blocks the expunged zone deliverable.

**Comment by davepacheco** [comment]
This was resolved by a combination of #5348 and maybe #5438.
