### ISSUE TITLE
OxQL: want better response when zero results for query

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#5439]
When I make this otherwise perfectly valid query with a time range small enough to exclude all existing data points, I get back a 400 `InvalidRequest` with a confusing message. Should this really be an error? If we think so, the error message could still be more helpful.

```
get collection_target:cpus_provisioned 
  | filter timestamp > @now() - 1h && id == "001de000-1334-4000-8000-000000000000"
```

```
errorCode: "InvalidRequest"
message: "Table contains no timeseries to filter"
```

<img width="1186" alt="image" src="https://github.com/oxidecomputer/omicron/assets/3612203/2e4cfd1f-bb6c-434a-aaa5-2156f27217f1">

**Comment by bnaecker** [comment]
There was a reason I made this an error originally, to keep parity with how we remove empty timeseries entirely when we fetch them from the DB. That might not be a good one one, I'm happy to amend this to "filter" an empty timeseries.
