### ISSUE TITLE
`support` user is missing PATH entries

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#5474]
When logging in as [the support user](https://github.com/oxidecomputer/omicron/blob/120b2ee38dae7b5b8cf3c52d341ad4549d648cd9/wicket/zone-etc/ssh/sshd_config#L40-L43) via a support yubikey, the path is not set up to allow calling `omdb`, `mgadm`, etc., binaries that are present in the switch zone. (This is probably an easy fix but this just bit us, so opening the issue before I forget.)

**Comment by citrus-it** [comment]
Something like https://github.com/oxidecomputer/omicron/pull/5476 should resolve this.
We already have the profile files we need in `smf/profile/` and they're bundled into the switch zone archive for root, we can just use the same ones for the support user when we create it. It will also get the switch number in the prompt in the same way that root has.
