### ISSUE TITLE
Nexus must create "Control Plane Disks" for disks automatically

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#5503]
This is the root case of https://github.com/oxidecomputer/omicron/issues/5502 .

(The decision to create a new issue is a little arbitrary, I just wanted to deep-dive onto the root cause here, while letting the symptoms stay visible on #5502).

As of https://github.com/oxidecomputer/omicron/pull/5172 , RSS / Nexus are responsible for managing "control plane disks" and "control plane zpools". In this world, the sled agent no longer autonomously formats disks, but waits for the "go-ahead" from Nexus.

For bootstrapping, RSS also has this responsibility:
- It creates a cofiguration based on inventory: https://github.com/oxidecomputer/omicron/blob/20299e0b472586014054bc2ebc325e0f4d44b511/sled-agent/src/rack_setup/plan/service.rs#L345-L370
- Sends the configuration to sleds: https://github.com/oxidecomputer/omicron/blob/20299e0b472586014054bc2ebc325e0f4d44b511/sled-agent/src/rack_setup/service.rs#L348-L350
- And tells Nexus about it in the RSS handoff, where the info is stored in CRDB: https://github.com/oxidecomputer/omicron/blob/20299e0b472586014054bc2ebc325e0f4d44b511/nexus/db-queries/src/db/datastore/rack.rs#L739-L760

So, this works in the initialization case.

However, in the case of "sled addition", we're missing the follow-up parts:

- [ ] Nexus needs to assemble the `OmicronPhysicalDisksConfig` that gets sent to sleds
  - [ ] For "new disks": This means scanning the inventory for physical disks, and creating a new control plane object if one does not exist. Note that "expunged disks" still exist, and should not be automatically re-added.
  - [ ] For "existing disks": This means using control plane disks that are not expunged.
- [ ] As a part of blueprint execution, Nexus needs to actually send `OmicronPhysicalDisksConfig` to individual sleds

Regarding new disk addition, there's a bit of uncertainty about "when we should perform this action".
- We could do it once during "sled add" - take a specific point-in-time view of inventory, adopt everything then, and subsequently refuse to auto-online disks
- ... or we could have "auto-online" be the default policy, until the disk is expunged, at which time it must be explicitly re-added

My opinion incoming: I think we've gone back-and-forth on this a bit because it's a policy decision. An operator *could* explicitly opt into an "add physical disk" API for each addition. Or they could just want all disks to auto-attach and start working. We *could* save this as a toggle, and enable both pathways? But that might be unnecessary effort, if we end up recommending / observing that customers prefer a particular option.

**Comment by andrewjstone** [comment]
> Regarding new disk addition, there's a bit of uncertainty about "when we should perform this action".

We could do it once during "sled add" - take a specific point-in-time view of inventory, adopt everything then, and subsequently refuse to auto-online disks
... or we could have "auto-online" be the default policy, until the disk is expunged, at which time it must be explicitly re-added

I think my preference is to always 'auto-online' right now. We don't know timing wise which disks we'll get first and we still need to add APIs for explicit adoption. Once we add those APIs we can choose not to auto-online. If we don't auto-online, we may also want to show the customers what disks they are getting when they add a sled by showing them in `list-uninitialized`.
