### ISSUE TITLE
Reconfigurator: Executor should not try to talk to expunged sleds

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#5594]
As part of testing in https://github.com/oxidecomputer/omicron/issues/5480, we found that the executor still tries, and fails, to send `OmicronPhysicalDisksConfig` to expunged sleds. This causes the rest of the executor to not complete on the error and so zones don't get deploye.

**Comment by smklein** [comment]
Within the blueprint builder, we create a mapping of "sled -> resources" for all sleds, even expunged ones:

https://github.com/oxidecomputer/omicron/blob/7adf6d276c87bd6da63aa41609b079c8b29e3b81/nexus/reconfigurator/planning/src/blueprint_builder/builder.rs#L366-L371

Within the executor, we send requests to "deploy disks" and "deploy zones" to all sleds by ID -- this does not filter out expunged sleds:

https://github.com/oxidecomputer/omicron/blob/7adf6d276c87bd6da63aa41609b079c8b29e3b81/nexus/reconfigurator/execution/src/lib.rs#L133-L145

Although we're hitting this issue with disks (it happens first!) I think we also have the same issue for zone deployment.

**Comment by jgallagher** [comment]
Both of those are given `sleds_by_id`, which comes from `datastore.sled_list_all_batched()`. Should that function take a `SledFilter`, similar to how `.all_omicron_zones()` takes a zone filter?

**Comment by andrewjstone** [comment]
> Both of those are given `sleds_by_id`, which comes from `datastore.sled_list_all_batched()`. Should that function take a `SledFilter`, similar to how `.all_omicron_zones()` takes a zone filter?

Yup, that's what Sean and I were just discussing.

**Comment by andrewjstone** [comment]
> > Both of those are given `sleds_by_id`, which comes from `datastore.sled_list_all_batched()`. Should that function take a `SledFilter`, similar to how `.all_omicron_zones()` takes a zone filter?
> 
> Yup, that's what Sean and I were just discussing.

We're actually not going to filter there, since there is also config that can refer to these disks and zones and will error out later. Instead we're going to go with an "additive" approach and add an expunged field to the `Sled` type in the executor. That is the most explicit and then each method can also log its decisions.
