### ISSUE TITLE
SAML idp signed requests need to respond with an appropriate name id format

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/omicron#5604]
Currently we always omit the `NameIDFormat` when generated SAML requests. Okta fails to handle our requests due to omitting the Name Id Format. Okta expects that requests match the format value that is specified. We are unclear yet if we only need to match one of the formats in the metadata.

**Comment by augustuswm** [comment]
https://help.okta.com/oie/en-us/content/topics/apps/aiw-saml-reference.htm?cshid=csh-apps-aiw-saml-advanced

**Comment by jmpesp** [comment]
I tested in the Canada region with the following samael patch:

```patch
diff --git a/src/service_provider/mod.rs b/src/service_provider/mod.rs
index a237052..aed7a73 100644
--- a/src/service_provider/mod.rs
+++ b/src/service_provider/mod.rs
@@ -236,11 +236,8 @@ impl ServiceProvider {
         self.authn_name_id_format
             .clone()
             .and_then(|v| -> Option<String> {
-                let unspecified = NameIdFormat::UnspecifiedNameIDFormat.value();
                 if v.is_empty() {
                     Some(NameIdFormat::TransientNameIDFormat.value().to_string())
-                } else if v == unspecified {
-                    None
                 } else {
                     Some(v)
                 }
@@ -478,11 +475,13 @@ impl ServiceProvider {
                 value: entity_id,
                 ..Issuer::default()
             }),
-            name_id_policy: Some(NameIdPolicy {
-                allow_create: Some(true),
-                format: self.name_id_format(),
-                ..NameIdPolicy::default()
-            }),
+            name_id_policy: self.name_id_format().map(|format|
+                NameIdPolicy {
+                    allow_create: Some(true),
+                    format: Some(format),
+                    ..NameIdPolicy::default()
+                }
+            ),
             force_authn: Some(self.force_authn),
             ..AuthnRequest::default()
         })
```

This patch:

- only creates a `Some(NameIdPolicy)` if `name_id_format` returns `Some`
- if `self.authn_name_id_format`is `Some(Unspecified)`, then return that.

With those changes, Nexus sent Okta an AuthnRequest that contained

```xml
<saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" AllowCreate="true"/>
```

and it was accepted.

**Comment by jmpesp** [comment]
I've opened https://github.com/oxidecomputer/samael/pull/2 on our fork, and will be creating an Omicron PR shortly, as well as an upstream PR.

**Comment by jmpesp** [comment]
Upstream PR is https://github.com/njaremko/samael/pull/53

**Comment by jmpesp** [comment]
So, Nexus patched with the above PR is not sufficient when configuring Okta to only accept signed requests. This seems to enable additional request verification. If Okta is configured with `NameIDFormat = emailAddress` causing the following 400 error if `Unspecified` is set by Nexus:

```
Your request resulted in an error. NameIDPolicy 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified' is not the configured Name ID Format 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress' for the app
```

If _no_ NameIDPolicy tag is sent, then Okta returns a 400 saying:

```
Your request resulted in an error. NameIDPolicy '' is not the configured Name ID Format 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress' for the app
```

**Comment by jmpesp** [comment]
We dove into this in today's SAML meeting: if Nexus sends an authentication request that uses the first NameIdFormat in the IDP's metadata document string as a NameIDPolicy, then it is accepted. I _still believe_ this is non-spec behaviour, because of the following quoted line from the spec:

```
        // 3.4.1.1 Element <NameIDPolicy>: If the Format value is omitted or set
        // to urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified, then the
        // identity provider is free to return any kind of identifier
```

However, in order to integrate with Okta when requests must be signed (and to _not_ break existing SAML deployments!) the fix for Nexus will be to optionally specify a NameIDPolicy to send in the request. If this is unset (i.e. existing behaviour), then Unspecified should be sent.
