### ISSUE TITLE
Nexus API should limit the number of firewall rules

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#5662]
There does not appear to be a limit on the number of firewall rules that a user can express in an API call to Nexus. We should probably add one to avoid huge requests or blowing up OPTE itself with a massive number of rules to match.

**Comment by david-crespo** [comment]
Will need to test it, but this compiles. It might be as easy as this.

```rs
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
pub struct VpcFirewallRuleUpdateParams {
    #[schemars(length(max = 32))]
    pub rules: Vec<VpcFirewallRuleUpdate>,
}
```

**Comment by bnaecker** [comment]
That would be great! I think we might need to add some constraints on the `VpcFirewallRuleFilter` inside these as well, but I'm not sure how to combine those.
