### ISSUE TITLE
non-gimlet dev pc losing ssh connection after creating virtual hardware after 10-ish minutes

### ISSUE THREAD

**Issue by ubedan** [oxidecomputer/omicron#5696]
I'm having an issue in a non-gimlet dev-pc losing ssh connection after 5 to 10 minutes-ish after running the latest xtask create virtual hardware. As of 4/30 or so I didn't have this problem, and was able to stay connected  for 12 hours waiting for the omicron to sync (another problem)...

Duplicate address on the igb0 address?

proxy ARP problem on the helios gateway address?

My setup:

10.0.0.17 - Upstream router ip address.   ( I thought I read somewhere that Omicron/the sleds like to take .1... .16 for it's own use.)

10.0.0.18 - igb0 assigned address

Running: 
source env.sh

export GATEWAY_IP=10.0.0.17             # The gateway IP address for your local network (see above)
export PXA_START=10.0.0.1       # The first IP address your Oxide cluster can use (see above)
export PXA_END=10.0.0.99         # The last IP address your Oxide cluster can use (see above)

cargo xtask virtual-hardware create --gateway-ip 10.0.0.17 --pxa-start 10.0.0.1 --pxa-end 10.0.0.99

dmesg reports:
..:15 helios genunix: [ID 408114 kern.info] /pseudo/zconsnex@1/zcons@0 (zcons0) online
..:34 helios ip: [ID 195243 kern.warning] WARNING: proxy ARP problem?  Node 'xx:xx:xx:xx:xx' is using 010.000.000.018 on igb0
...:34 helios last message repeated 2 times
...:34 helios ip: [ID 759807 kern.warning] WARNING: igb0 has duplicate address 010.000.000.018 (in use by xx:xx:xx:xx:xx); disabled
...:34 helios in.routed[1565]: [ID 238047 daemon.warning] interface igb0 to 10.0.0.18 turned off
...:24 helios in.routed[1565]: [ID 464608 daemon.error] route 0.0.0.0 --> 10.0.0.17 nexthop is not directly connected
...:34 helios in.routed[1565]: [ID 238047 daemon.warning] interface igb0 to 10.0.0.18 turned off

**Comment by ubedan** [comment]
Changing to:

cargo xtask virtual-hardware create --gateway-ip 10.0.0.17 --pxa-start 10.0.0.20 --pxa-end 10.0.0.99

Seems to fix this issue, but I have a foggy memory of needing the gateway_ip to be in the pxa-start:end range. 

Testing...  will report any new developments.

**Comment by ubedan** [comment]
Still losing connection after a number of minutes if the gateway-ip address is in the pxa-start/end range.

Of note, dladm and ipadm don't display a proxy ARP problem or duplicate address issue until the ssh connection is lost.

New data:  
 - Destroying the virtual hardware restores the illumos/helios ssh connectivity.

 - sled-agent smf error reports that the gateway needs to be in the internal services ip pool ranges. Is this the pxa-start / pxa-end...   I've been unable to figure it out.

My next test will be to move the igb0 address to an address past pxa-end.

**Comment by jclulow** [comment]
So, I'm not sure what's going on here except that those syslog messages from in.routed suggest you have **ipv4-routing** enabled on this system, and it's thus doing something at least confusing if not actively harmful with RIP.  We turn that off in several of our images using an SMF site profile, but you can also turn it off with a **routeadm** command; see https://www.illumos.org/issues/14006

**Comment by ubedan** [comment]
Thanks... I really appreciate the help!

It only worked when I also 'svcadm disable ndp' the routing package that was enabled, possibly by mistakenly running the simulated virtual hardware setup script.  If setting up a simulated dev system enables ipv4-forwarding, ipv4-routing and the ndp routing service, then it might be a good idea to disable the same features when setting up non-simulated hardware.

**Comment by jclulow** [comment]
I don't believe we ever enable ipv4-routing on purpose.  If you look at the bug I linked, the issue is that it defaults to on in some cases and should not.

I also don't believe you should disable NDP, as I believe that's necessary for IPv6 to work at all.

**Comment by ubedan** [comment]
Drat...   That fixed the nexthop issue, but I'm still seeing the ssh connection freeze with the duplicate 10.0.0.18 igb0 address.

Errors:
 - kern.notice ip: joining multicasts failed (4) on vopte0
 
 - kern.warning] WARNING: proxy ARP problem? Node 'xx:xx:xx:xx:xx:xx' is using 010.000.000.018 on igb0
...:34 helios last message repeated 2 times
...:34 helios ip: [ID 759807 kern.warning] WARNING: igb0 has duplicate address 010.000.000.018 (in use by xx:xx:xx:xx:xx:xx); disabled

It took a lot longer than 10 minutes to lose the connection, but most of that time was compiling the new sled-agent, etc.

I'm still having a sync issue, even though chronyc target reports 0.017 secs synchronization.

**Comment by ubedan** [comment]
Enabling ndp and ipv6 forwarding didn't change the ssh connection loss...  (and it only took about 3 minutes this time.)

In a previous test I had ipv6 forwarding disabled, but enabling svcadm enable ndp also enabled ipv6 forwarding, and that didn't make any difference in the ssh connection loss.

One guess I have is that I'm doing something simple wrong...  current omicron git pull, helios was updated yesterday.

Current testing procedure:
- Log in as non-root user
- source  env.sh script
- export GATEWAY_IP=10.0.0.17             # The gateway IP address for your local network (see above)
- export PXA_START=10.0.0.1       # The first IP address your Oxide cluster can use (see above)
- export PXA_END=10.0.0.99         # The last IP address your Oxide cluster can use (see above)
- export PHYSICAL_LINK=igb0

cargo xtask virtual-hardware create --gateway-ip 10.0.0.17 --pxa-start 10.0.0.1 --pxa-end 10.0.0.99

cargo run --release --bin omicron-package -- -t default target create -i standard -m non-gimlet -s softnpu -r single-sled

cargo run --release --bin omicron-package -- package

cargo build --release --bin omicron-package

pfexec ./target/release/omicron-package install

---

netstat -rn  Loses the 10.0.0.0 routing to 10.0.0.18 line when the ssh connection

Routing Table: IPv4
  Destination            Gateway          Flags  Ref     Use     Interface 
-------------------- -------------------- ----- ----- ---------- --------- 
default              10.0.0.17            UG        3      29945           
10.0.0.0             10.0.0.18            U         3          0 igb0      
127.0.0.1            127.0.0.1            UH        2          0 lo0 

Is there any other information that would help? 

Thanks in advance.

**Comment by jclulow** [comment]
I'm not that familiar with the virtual hardware stuff, but what the OS is telling you is that it's detected someone else using your IP address (which I assume is the .18 address) and it's shutting it off.  You've told Omicron that it's allowed to use that address for itself, and it presumably is doing that, at which point the host stops being able to use it.  I would also think the gateway IP is the same deal.

I think the proxy ARP range has to be addresses that are _not_ in use anywhere on the network, even (and perhaps especially) on existing IP interfaces on the system itself.
