### ISSUE TITLE
gzonly.txt missing

### ISSUE THREAD

**Issue by ubedan** [oxidecomputer/omicron#5702]
Attempting an up to date helios dev-pc install of omicron:

Excerpt of sled-agent default log:

{"msg":"request completed","v":0,"name":"SledAgent","level":30,"time":"2024-05-06T06:23:12.983216628Z","hostname":"helios","pid":1774,"uri":"/omicron-zones","method":"PUT","req_id":"f16ed110-bb1c-4335-8771-fc72278b9800","remote_addr":"[fd00:1122:3344:101::1]:61261","local_addr":"[fd00:1122:3344:101::1]:12345","component":"dropshot (SledAgent)","file":"/home/d/.cargo/git/checkouts/dropshot-a4a923d29dccc492/29ae98d/dropshot/src/server.rs:837","error_message_external":"Int
ernal Server Error","error_message_internal":"Failed to initialize zones: [(\"oxz_internal_dns_7fb9d6dd-5322-4bbf-8712-d861c71f2be4\", ZoneInstall(InstallZone { zone: \"oxz_internal_dns_7fb9d6dd-5322-4bbf-8712-d861c71f2be4\", image_path: \"/opt/oxide/internal_dns.tar.gz\", err: AdmError { op: Install, zone: \"oxz_internal_dns_7fb9d6dd-5322-4bbf-8712-d861c71f2be4\", err: CommandOutput(CommandOutputError(\"exit code 1\\nstdout:\\nA ZFS file system has been created for thi
s zone.\\nINFO: omicron: installing zone oxz_internal_dns_7fb9d6dd-5322-4bbf-8712-d861c71f2be4 @ \\\"/pool/ext/0f5e23aa-2cde-4d49-b6b0-f07c4aaa280f/crypt/zone/oxz_internal_dns_7fb9d6dd-5322-4bbf-8712-d861c71f2be4\\\"...\\nINFO: omicron: replicating /usr tree...\\nINFO: omicron: replicated /usr: 27498 files, 686468604, bytes, 9212 msec\\nINFO: omicron: replicating /lib tree...\\nINFO: omicron: replicated /lib: 255 files, 3271685, bytes, 191 msec\\nINFO: omicron: replicat
ing /sbin tree...\\nINFO: omicron: replicated /sbin: 0 files, 0, bytes, 3 msec\\nINFO: omicron: pruning SMF manifests...\\nINFO: omicron: pruning global-only files...\\nstderr:\\nError: could not locate \\\"gzonly.txt\\\" in any baseline directory\")) } })), (\"oxz_internal_dns_c8e911b9-255b-445c-ab2e-8029cb0b8acc\", ZoneInstall(InstallZone { zone: \"oxz_internal_dns_c8e911b9-255b-445c-ab2e-8029cb0b8acc\", image_path: \"/opt/oxide/internal_dns.tar.gz\", err: AdmError {
op: Install, zone: \"oxz_internal_dns_c8e911b9-255b-445c-ab2e-8029cb0b8acc\", err: CommandOutput(CommandOutputError(\"exit code 1\\nstdout:\\nA ZFS file system has been created for this zone.\\nINFO: omicron: installing zone oxz_internal_dns_c8e911b9-255b-445c-ab2e-8029cb0b8acc @ \\\"/pool/ext/8355f40d-8e0b-4165-b334-89ea2988bbc2/crypt/zone/oxz_internal_dns_c8e911b9-255b-445c-ab2e-8029cb0b8acc\\\"...\\nINFO: omicron: replicating /usr tree...\\nINFO: omicron: replicated
/usr: 27498 files, 686468604, bytes, 11574 msec\\nINFO: omicron: replicating /lib tree...\\nINFO: omicron: replicated /lib: 255 files, 3271685, bytes, 23 msec\\nINFO: omicron: replicating /sbin tree...\\nINFO: omicron: replicated /sbin: 0 files, 0, bytes, 2 msec\\nINFO: omicron: pruning SMF manifests...\\nINFO: omicron: pruning global-only files...\\nstderr:\\nError: could not locate \\\"gzonly.txt\\\" in any baseline directory\")) } })), (\"oxz_internal_dns_338bf3bd-9b
c2-424b-9bf0-399a6827785d\", ZoneInstall(InstallZone { zone: \"oxz_internal_dns_338bf3bd-9bc2-424b-9bf0-399a6827785d\", image_path: \"/opt/oxide/internal_dns.tar.gz\", err: AdmError { op: Install, zone: \"oxz_internal_dns_338bf3bd-9bc2-424b-9bf0-399a6827785d\", err: CommandOutput(CommandOutputError(\"exit code 1\\nstdout:\\nA ZFS file system has been created for this zone.\\nINFO: omicron: installing zone oxz_internal_dns_338bf3bd-9bc2-424b-9bf0-399a6827785d @ \\\"/pool
/ext/e7c86737-527f-4a14-a3c0-fcb5fe0341fd/crypt/zone/oxz_internal_dns_338bf3bd-9bc2-424b-9bf0-399a6827785d\\\"...\\nINFO: omicron: replicating /usr tree...\\nINFO: omicron: replicated /usr: 27498 files, 686468604, bytes, 9362 msec\\nINFO: omicron: replicating /lib tree...\\nINFO: omicron: replicated /lib: 255 files, 3271685, bytes, 3262 msec\\nINFO: omicron: replicating /sbin tree...\\nINFO: omicron: replicated /sbin: 0 files, 0, bytes, 7 msec\\nINFO: omicron: pruning S
MF manifests...\\nINFO: omicron: pruning global-only files...\\nstderr:\\nError: could not locate \\\"gzonly.txt\\\" in any baseline directory\")) } }))]","latency_us":12972637,"response_code":"500"}

root >   find / -name gzonly.txt            unsuccessful...

Thanks in advance, and I apologize in advance if it's my fault again.

**Comment by jclulow** [comment]
Do you have `omicron1/tools` installed and is the `baseline` service online?

**Comment by jclulow** [comment]
See also:  [omicron1(7)](https://github.com/oxidecomputer/helios-omicron-brand/blob/main/README.md).

**Comment by davepacheco** [comment]
For what it's worth, I noticed 13 similar messages in my sled-agent log leading up to a successful Nexus handoff (i.e., the success case):

```
23:16:20.047Z WARN SledAgent (ServiceManager): Failed to initialize switch zone: Failed to install zone 'oxz_switch' from '/opt/oxide/switch.tar.gz': Failed to execute zoneadm command 'Install' for zone 'oxz_switch': Failed to parse command output: exit code 1
    stdout:
    INFO: omicron: installing zone oxz_switch @ "/zone/oxz_switch"...
    INFO: omicron: replicating /usr tree...
    INFO: omicron: replicated /usr: 23247 files, 372443399, bytes, 2025 msec
    INFO: omicron: replicating /lib tree...
    INFO: omicron: replicated /lib: 256 files, 3273194, bytes, 28 msec
    INFO: omicron: replicating /sbin tree...
    INFO: omicron: replicated /sbin: 0 files, 0, bytes, 2 msec
    INFO: omicron: pruning SMF manifests...
    INFO: omicron: pruning global-only files...
    stderr:
    Error: could not locate "gzonly.txt" in any baseline directory
    file = sled-agent/src/services.rs:4362
```

It looks like those messages predate the time when the omicron/baseline service came online:

```
root@g0:~# svcs baseline
STATE          STIME    FMRI
online         23:16:20 svc:/system/omicron/baseline:default
```

After that timestamp, the messages stopped and setup proceeded.

@jclulow do you think the sled agent SMF service should depend on omicron/baseline, or is this behavior basically okay?

**Comment by jclulow** [comment]
The **svc:/system/omicron/baseline:default** is essentially an enabling workaround for running Omicron bits on mutable install-to-disk systems like workstations, etc.  The service doesn't exist at all on production systems because, as described in **omicron1(7)**, we create the baseline during the _build_ of the ramdisk image and ship it in place.

With this in mind, I think you could give **sled-agent** an **optional_all** dependency on the **baseline* service, which should give the correct startup sequencing on a development system but be silently ignored in the production ramdisk.

**Comment by davepacheco** [comment]
Thanks.  Filed #6326.
