### ISSUE TITLE
Check for remote address in allow-list update should ignore underlay

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#5735]
When attempting to update the allow-list for user-facing services, Nexus ensures that the address of the peer sending the request is contained in the allow-list itself. This is a safety mechanism to prevent locking oneself out. However, there are still ways one can get locked out. As an example, if a user sets the allow-list to enable traffic from some external proxy, but that proxy is issued a new IP address without notice, they won't be able to get back into the rack to change the list.

To address this, we could make use of the Nexus external API proxy offered by `wicketd`. This works at the transport layer, and runs over the _underlay_ network. That means it's not subject to the allow-list checks at all, since it's over a completely different interface. However, clients will never be able to actually update the allow-list from the proxy, because the containment mentioned at the beginning will fail! Users don't know (and can't know) the underlay address, so Nexus will always reject the list.

We should relax this check in Nexus. The remote address must either be on the allow-list, or on the underlay network. It's not yet clear to me if that means "same rack subnet" or "any rack subnet", or if we want to do an explicit lookup in the database to make sure it's in a known-valid rack.

**Comment by jgallagher** [comment]
An idle thought - the nexus techport proxy is an entirely separate dropshot server: https://github.com/oxidecomputer/omicron/blob/c472464a4972e91a576f439de3866829b19f807b/nexus/src/lib.rs#L179-L192

I wonder if it would be easier to stash something in the respective server contexts to indicate which was which, and this disable the check of the request IP based on which dropshot server is handling the request?

**Comment by bnaecker** [comment]
That's an interesting idea, I like it. I'm looking at the server contexts now, and they're all currently shared between the three servers (internal, external, and techport), through an `Arc`. I think we'd need a deeper copy to make this work, or split the internal fields up in a more structured way so that we can add a new field like this. The `ServerContext` has clearly grown organically, it looks like from before we even had the internal server, since it includes the latency tracking for the internal API endpoints. So this might be a good time to make such a change in any case!
