### ISSUE TITLE
CI: clippy job is not failing on documentation errors

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#5739]
For example [this error](https://buildomat.eng.oxide.computer/wg/0/details/01HXJ80W8YKB1YA1Y4K5T49SYE/nteebnilFt3b4zUtsy9uBipehqtIHjn9HtnY7a2WLGMuqNSc/01HXJ817EA3TK3MB3SP634Y66K#S2909) and many others like it are currently making it through CI.

```
warning: unresolved link to `StNestedBuilder::make_subsection`
   --> nexus/types/src/sectioned_table.rs:145:7
    |
145 | /// [`StNestedBuilder::make_subsection`].
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `StNestedBuilder` in scope
    |
    = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
```

**Comment by iliana** [comment]
I figure what is missing in our clippy task is `RUSTDOCFLAGS="-Dwarnings"`:

https://github.com/oxidecomputer/omicron/blob/e30978a040d4f87cccafa3e4475cd3056df1cc31/.github/buildomat/jobs/clippy.sh#L30-L33

But while trying to test that theory, I found I can't reproduce those messages locally running `cargo doc`. Not sure why.

**Comment by iliana** [comment]
Finally figured it out. `RUSTDOCFLAGS="-Dwarnings"` is indeed what we were missing, but this caused the errors to go away, because it overrides this:

https://github.com/oxidecomputer/omicron/blob/3549436604b76aaf70459ac2561e99e9e3b2dbfa/.cargo/config.toml#L1-L8

Fix forthcoming.
