### ISSUE TITLE
Error response types in OpenApi spec

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#578]
A successful VPC subnet PUT correctly returns a 204 No Content, and this is encoded into the OpenAPI spec.

https://github.com/oxidecomputer/omicron/blob/939adec4de865caf4c0339fced7fdc75f8bfa5b0/openapi/nexus.json#L2562-L2566

A 400 error returns JSON, but this is not indicated in the spec. I don't know that it necessarily should be, but the fact that it isn't is causing me a minor inconvenience in the console: the [generated TS client](https://github.com/oxidecomputer/console/blob/7e2707bde25bcc4a6e43ce26da2622b366ffc48c/libs/api/__generated__/Api.ts#L3142-L3164) does not know that the response here might be JSON and therefore doesn't even attempt to parse the JSON.

This may well be two separate problems — the spec and the generator — and we could fix one without fixing the other. For example, I could patch the generator to always assume JSON in the response and attempt to parse it regardless of what the spec says. Only if parsing fails do we fall back to a null value for the parsed response body.

```ts
vpcSubnetsPost: (
  { organizationName, projectName, vpcName }: VpcSubnetsPostParams,
  data: VpcSubnetCreate,
  params: RequestParams = {}
) =>
  this.request<VpcSubnet, any>({
    path: `/organizations/${organizationName}/projects/${projectName}/vpcs/${vpcName}/subnets`,
    method: 'POST',
    body: data,
    type: ContentType.Json,
    format: 'json',   // <--------- LOOK
    ...params,
  }),

vpcSubnetsPutSubnet: (
  {
    organizationName,
    projectName,
    subnetName,
    vpcName,
  }: VpcSubnetsPutSubnetParams,
  data: VpcSubnetUpdate,
  params: RequestParams = {}
) =>
  this.request<void, any>({
    path: `/organizations/${organizationName}/projects/${projectName}/vpcs/${vpcName}/subnets/${subnetName}`,
    method: 'PUT',
    body: data,
    type: ContentType.Json,
    ...params,
  }),
```

**Comment by ahl** [comment]
@davepacheco and I were literally talking about this yesterday... and trying to convince ourselves that this was a problem that could be deferred... but it sounds like that may not be the case.

What generator are you using for ts? Would it suffice for the moment to add something like:

```json
"responses": { 
   "204": { 
     "description": "resource updated" 
   } ,
   "4xx": { 
     "description": "I got 4xx problems, but a response ain't one" 
   } ,
   "5xx": { 
     "description": "I got 5xx problems, but a response ain't one" 
   } 
 } 
```

**Comment by david-crespo** [comment]
I'm using [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api). Based on [this](https://github.com/acacode/swagger-typescript-api/blob/7df956c236d1e7fc051658cd7012c8ea22286b44/templates/default/procedure-call.eta#L64) it seems to only look at the success response to decide what type the response is in general. Not very fancy.

We can change that pretty easily. We're already [patching](https://github.com/oxidecomputer/console/blob/7e2707bde25bcc4a6e43ce26da2622b366ffc48c/patches/swagger-typescript-api%2B9.3.1.patch) some logic in the main code and in a template. Not sure how this _should_ work, though. Like I said above, a simple hack would be to always try to parse JSON and if it fails (e.g., due to being empty) say the result is `null`.

**Comment by david-crespo** [comment]
Well this is simple. Turns out I can give it a default format to use when there isn't one. That solves my immediate problem.

https://github.com/oxidecomputer/console/pull/593/commits/bd3604aae7625d9601695e34d48a6cf6116fd06d#diff-8e227a30e2de75228212f53e021617d2b5a898c17744a80c9077614266365045R19

**Comment by david-crespo** [comment]
So I’d say this is now entirely a question of how good and fancy we want the OpenAPI spec to be, and that depends on whether people expect error responses to be in an OpenAPI spec. It’s not a problem for me anymore. Probably puntable.   Though I do think it would be good to have a more robust error format for things like field-level errors. The current errors have me doing bad things:

```ts
export function getParseError(message: string | undefined): string | undefined {
  if (!message) return undefined
  const inner = /^unable to parse body: (.+) at line \d+ column \d+$/.exec(
    message
  )?.[1]
  return inner && capitalize(inner)
}
```

**Comment by jessfraz** [comment]
something like 
```
{
  "responses": {
    "204": {
      "description": "resource updated"
    },
    "4xx": {
      "description": "I got 4xx problems, but a response ain't one",
      "application/json": {
        "schema": {}
      }
    },
    "5xx": {
      "description": "I got 5xx problems, but a response ain't one",
      "application/json": {
        "schema": {}
      }
    }
  }
}
```
would be helpful for generating the docs @ahl

**Comment by david-crespo** [comment]
We have this on every endpoint. Good enough.

https://github.com/oxidecomputer/omicron/blob/aff0d7ace4d92612619289b3e75c597269282166/openapi/nexus.json#L6999-L7004
