### ISSUE TITLE
wicket ignition control shows 'I', but only responds to 'i'

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/omicron#5796]
While using ignition to try to cycle things, it took me a bit to get to the right keypress. It was shown as `Ignition <I> `, which led me to think I had to use a capital I to use it. However, only a lowercase 'i' would get there based on the current contents of `keymap.rs`. That took me a while to get. It'd be nice if either:

* The capital `I` actually worked for ignition like shown
* The message was changed so a lowercase `i` was shown

**Comment by jclulow** [comment]
In facade, as a UI principle, I have attempted to make sure we don't ever need to distinguish upper and lower case key presses.  If I absolutely needed to do it, I would render it as **Shift-I** or something like that to make it clear, I think.
