### ISSUE TITLE
IP pool linked silos endpoint pagination broken

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/omicron#5837]
The linked silo tab only looks to be displaying the first page of results: https://oxide.sys.r3.oxide-preview.com/system/networking/ip-pools/default?tab=silos

Clicking next page results in an empty list of results, and we know that there are more than 25 linked silos.

Looking at the API calls that are being made this may be an issue in Nexus itself. The API itself with the page token is not returning any results, whereas if we request more than 25 results we can the expected amount back.

**Comment by david-crespo** [comment]
Confirmed in #5847, am I able to reproduce the empty second page in a test:

```
assertion `left == right` failed
  left: []
 right: [d9184cf8-578d-44e7-9d21-925e8f20fb2f, e0518aa9-664d-4f5e-8259-c7ba3d663c4e, f605f0d5-3759-4ccd-b7a2-d19f3e19eefc]
```
