### ISSUE TITLE
API: description for Name (type String) should explicitly mention the maximum length (63)

### ISSUE THREAD

**Issue by elaine-oxide** [oxidecomputer/omicron#5940]
The API docs do not say the maximum length of a name of type STRING.

Code location that needs to be fixed is here: https://github.com/oxidecomputer/omicron/blob/main/common/src/api/external/mod.rs#L304-L309

It looks like the maximum length is 63 (a few lines below the location linked above):
https://github.com/oxidecomputer/omicron/blob/main/common/src/api/external/mod.rs#L315

See discussion here: https://github.com/oxidecomputer/docs/pull/382#discussion_r1651739844

**Comment by david-crespo** [comment]
It won't show up on the production docs site until v9 is released, but you can see the effect of this change here:

https://docs-git-integration-oxidecomputer.vercel.app/api/disk_create

<img width="1203" alt="image" src="https://github.com/oxidecomputer/omicron/assets/3612203/6c09b517-01d4-4a66-8006-3dd56e2e180f">

**Comment by elaine-oxide** [comment]
Thank you!
