### ISSUE TITLE
device auth flow

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/omicron#595]
this is a nice to have for the cli so that the flow is like:

```
oxide auth login

# user chooses to do interactively

# cli gives a code

# browser opens to auth page and asks for code (can prepoulate as well)

# user logins w browser

# cli updates that it is logged in
```

https://oauth.net/2/device-flow/

this is in addition to using tokens, basically this returns to the cli a auth token

see also https://github.com/oxidecomputer/cli/issues/35

**Comment by plotnick** [comment]
Done with #1194.
