### ISSUE TITLE
test flake: oximeter-impl quantile::tests::test_against_baseline_normal_distribution

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#6100]
Example failure: https://buildomat.eng.oxide.computer/wg/0/details/01J2YJ5FHWHY57M6CP66358GPQ/SDeSqZtkcBivwNPt3raoXlpJng6mTQMP6qgSbm0esdbP3QEl/01J2YJ5ZJE2DTFCCJZ6A8JTBYA#S5370

```
5370	2024-07-16T20:37:33.824Z	--- STDOUT:              oximeter-impl quantile::tests::test_against_baseline_normal_distribution ---
5371	2024-07-16T20:37:33.824Z	
5372	2024-07-16T20:37:33.824Z	running 1 test
5373	2024-07-16T20:37:33.825Z	Base: 612.6506854922482, Est: 622.8491701905514
5374	2024-07-16T20:37:33.825Z	test quantile::tests::test_against_baseline_normal_distribution ... FAILED
5375	2024-07-16T20:37:33.825Z	
5376	2024-07-16T20:37:33.825Z	failures:
5377	2024-07-16T20:37:33.825Z	
5378	2024-07-16T20:37:33.825Z	failures:
5379	2024-07-16T20:37:33.825Z	    quantile::tests::test_against_baseline_normal_distribution
5380	2024-07-16T20:37:33.826Z	
5381	2024-07-16T20:37:33.826Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 103 filtered out; finished in 0.35s
5382	2024-07-16T20:37:33.826Z	
5383	2024-07-16T20:37:33.826Z	
5384	2024-07-16T20:37:33.826Z	--- STDERR:              oximeter-impl quantile::tests::test_against_baseline_normal_distribution ---
5385	2024-07-16T20:37:33.826Z	thread 'quantile::tests::test_against_baseline_normal_distribution' panicked at oximeter/impl/src/quantile.rs:598:9:
5386	2024-07-16T20:37:33.826Z	Difference 10.198484698303218 is not less than 10
5387	2024-07-16T20:37:33.826Z	stack backtrace:
5388	2024-07-16T20:37:33.827Z	   0: rust_begin_unwind
5389	2024-07-16T20:37:33.827Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
5390	2024-07-16T20:37:33.827Z	   1: core::panicking::panic_fmt
5391	2024-07-16T20:37:33.827Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
5392	2024-07-16T20:37:33.827Z	   2: test_against_baseline_normal_distribution
5393	2024-07-16T20:37:33.827Z	             at ./src/quantile.rs:598:9
5394	2024-07-16T20:37:33.827Z	   3: oximeter_impl::quantile::tests::test_against_baseline_normal_distribution::{{closure}}
5395	2024-07-16T20:37:33.827Z	             at ./src/quantile.rs:576:51
5396	2024-07-16T20:37:33.828Z	   4: core::ops::function::FnOnce::call_once
5397	2024-07-16T20:37:33.828Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
5398	2024-07-16T20:37:33.828Z	   5: core::ops::function::FnOnce::call_once
5399	2024-07-16T20:37:33.828Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
5400	2024-07-16T20:37:33.828Z	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zeeshanlakhani** [comment]
> Example failure: https://buildomat.eng.oxide.computer/wg/0/details/01J2YJ5FHWHY57M6CP66358GPQ/SDeSqZtkcBivwNPt3raoXlpJng6mTQMP6qgSbm0esdbP3QEl/01J2YJ5ZJE2DTFCCJZ6A8JTBYA#S5370
> 
> ```
> 5370	2024-07-16T20:37:33.824Z	--- STDOUT:              oximeter-impl quantile::tests::test_against_baseline_normal_distribution ---
> 5371	2024-07-16T20:37:33.824Z	
> 5372	2024-07-16T20:37:33.824Z	running 1 test
> 5373	2024-07-16T20:37:33.825Z	Base: 612.6506854922482, Est: 622.8491701905514
> 5374	2024-07-16T20:37:33.825Z	test quantile::tests::test_against_baseline_normal_distribution ... FAILED
> 5375	2024-07-16T20:37:33.825Z	
> 5376	2024-07-16T20:37:33.825Z	failures:
> 5377	2024-07-16T20:37:33.825Z	
> 5378	2024-07-16T20:37:33.825Z	failures:
> 5379	2024-07-16T20:37:33.825Z	    quantile::tests::test_against_baseline_normal_distribution
> 5380	2024-07-16T20:37:33.826Z	
> 5381	2024-07-16T20:37:33.826Z	test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 103 filtered out; finished in 0.35s
> 5382	2024-07-16T20:37:33.826Z	
> 5383	2024-07-16T20:37:33.826Z	
> 5384	2024-07-16T20:37:33.826Z	--- STDERR:              oximeter-impl quantile::tests::test_against_baseline_normal_distribution ---
> 5385	2024-07-16T20:37:33.826Z	thread 'quantile::tests::test_against_baseline_normal_distribution' panicked at oximeter/impl/src/quantile.rs:598:9:
> 5386	2024-07-16T20:37:33.826Z	Difference 10.198484698303218 is not less than 10
> 5387	2024-07-16T20:37:33.826Z	stack backtrace:
> 5388	2024-07-16T20:37:33.827Z	   0: rust_begin_unwind
> 5389	2024-07-16T20:37:33.827Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
> 5390	2024-07-16T20:37:33.827Z	   1: core::panicking::panic_fmt
> 5391	2024-07-16T20:37:33.827Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
> 5392	2024-07-16T20:37:33.827Z	   2: test_against_baseline_normal_distribution
> 5393	2024-07-16T20:37:33.827Z	             at ./src/quantile.rs:598:9
> 5394	2024-07-16T20:37:33.827Z	   3: oximeter_impl::quantile::tests::test_against_baseline_normal_distribution::{{closure}}
> 5395	2024-07-16T20:37:33.827Z	             at ./src/quantile.rs:576:51
> 5396	2024-07-16T20:37:33.828Z	   4: core::ops::function::FnOnce::call_once
> 5397	2024-07-16T20:37:33.828Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
> 5398	2024-07-16T20:37:33.828Z	   5: core::ops::function::FnOnce::call_once
> 5399	2024-07-16T20:37:33.828Z	             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
> 5400	2024-07-16T20:37:33.828Z	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

Yeah, this hit up right against the threshold. I should make this more lenient in general.
