### ISSUE TITLE
Possible race between sled-agent and self-assembling switch zone

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#6149]
I've been having trouble deploying Omicron on my local Helios machine, using the a recent main (38575abf11e463993bdb953fc3ad3653cbf8a3b6 as of this writing). This is using the workflow "Bare-metal operating system" from `docs/how-to-run.adoc`. The behavior is sporadic, but here's what I've learned so far. I will fill in more details as I get them.

I generally see the first few zones being created: the switch zone, the internal DNS zones, and sometimes the NTP zone. At some point, things stall out. The zones don't fail, but the sled-agent makes no further progress creating new zones. I also see errors like this in the sled-agent log:

```
04:34:51.998Z ERRO SledAgent (HardwareMonitor): Failed to activate switch
    error = Failed to create address Static(V6(Ipv6Network { addr: fd00:1122:3344:101::2, prefix: 64 })) with name oxControlService0/omicron6 in oxz_switch: Zone execution error: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist: Zone execution error: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist: Command [/usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlService0/omicron6] executed and failed with status: exit status: 1  stdout: \n  stderr: ipadm: Could not create address: Interface does not exist
    file = sled-agent/src/hardware_monitor.rs:237
```

In most cases, I also see that MGS in the switch zone is not happy:

```
bnaecker@shale : ~/omicron $ pfexec svcs -Zx
svc:/oxide/mgs:default (Oxide Management Gateway Service)
  Zone: oxz_switch
 State: maintenance since July 24, 2024 at 04:49:31 AM UTC
Reason: Restarting too quickly.
   See: http://illumos.org/msg/SMF-8000-L5
   See: /zone/oxz_switch/root/var/svc/log/oxide-mgs:default.log
Impact: This service is not running.
```

Why is that process not running?

```
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch 'tail $(svcs -L mgs)'
Jul 24 04:49:31.212 INFO received discovery response (not used for location), sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:376
Jul 24 04:49:31.212 INFO received discovery response (used for location), pos: 1, sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:367
Jul 24 04:49:31.212 INFO received discovery response (used for location), pos: 0, sp_port: One, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f, file: gateway/src/management_switch/location_map.rs:367
Jul 24 04:49:31.212 DEBG received location determination response, refined_locations: {"switch0"}, interface: (direct socket handle), component: ManagementSwitch, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG registered endpoint, path: /ignition, method: GET, local_addr: [::1]:12225, component: dropshot, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG registered endpoint, path: /ignition/{type}/{slot}, method: GET, local_addr: [::1]:12225, component: dropshot, name: 16e98f48-2a21-4f98-8f5a-665e85bcb01f
Jul 24 04:49:31.212 DEBG mgs: initializing http server listening at [fd00:1122:3344:101::2]:12225: error creating server listener: Cannot assign requested address (os error 126)
registered endpoint, path: /ignition/{type}/{slot}/{command}, method: POST, local_addr: [::1]:12225, component[ Jul 24 04:49:31 Stopping because all processes in service exited. ]
[ Jul 24 04:49:31 Executing stop method (:kill). ]
[ Jul 24 04:49:31 Restarting too quickly, changing state to maintenance. ]
```

It's a bit hard to read, but the last message with `DEBG` says that MGS could not bind to the requested address. That's the switch-zone's address on the underlay. In the past, that was created by the sled-agent using `zone_enter()` to run `ipadm` in the zone. With the changes to make the zone self-assembling, I'm not sure who is responsible for that yet.

Does that address exist?

```
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch ipadm
ADDROBJ           TYPE     STATE        ADDR
lo0/v4            static   ok           127.0.0.1/8
lo0/v6            static   ok           ::1/128
tfportrear0_0/ll  addrconf ok           fe80::8846:60ff:fefc:dfc9%tfportrear0_0/10
oxBootstrap0/ll   addrconf ok           fe80::8:20ff:fe63:7251%oxBootstrap0/10
oxBootstrap0/bootstrap6 static ok       fdb0:18c0:4d87:4d6a::2/64
bnaecker@shale : ~/omicron $ pfexec zlogin oxz_switch dladm
LINK        CLASS     MTU    STATE    BRIDGE     OVER
tfportrear0_0 simnet  9000   up       --         ?
tfportqsfp0_0 simnet  9000   up       --         ?
oxBootstrap0 vnic     1500   up       --         ?
oxControlService0 vnic 9000  up       --         ?
```

No, neither the link-local nor the static underlay address exist in the zone, though the VNIC `oxControlService0` that is supposed to underly those does exist. That's good.

Does anyone ever create or operate on that address? Is it just never created, or somehow not plumbed correctly into or inside of the zone? Tracing this through `ipmgmtd` is a bit hard, but luckily we still shell out to `ipadm` for all or almost all of these operations. Let's see what's going on there, while I start the control plane:

```
bnaecker@shale : ~/helios $ pfexec dtrace -n 'proc:::exec-success /execname == "ipadm" && strstr(curpsinfo->pr_psargs, "oxControlService0") != NULL || strstr(curpsinfo->pr_psargs, "fd00:1122:3344:101::2") != NULL/ { printf("zone %d: '%s'\n", curpsinfo->pr_zoneid, curpsinfo->pr_psargs); }'
dtrace: description 'proc:::exec-success ' matched 1 probe
CPU     ID                    FUNCTION:NAME
 14  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  3  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll

  8  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll

  9  15105         exec_common:exec-success zone 138: bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox

  9  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS

 22  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  1  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm delete-if oxControlService0

 17  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm create-if -t oxControlService0

  1  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0

 12  15105         exec_common:exec-success zone 138: /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0

```

It looks like the link-local and static underlay addresses are created, and then the underlying IP interface is deleted with `delete-if`! Just to confirm, that's coming from zone 138 which is indeed the switch zone:

```
bnaecker@shale : ~/omicron $ zoneadm list -p oxz_switch | grep oxz_switch
138:oxz_switch:running:/zone/oxz_switch:a3ddcd13-5f85-4e9d-bc72-658f2db7c3f5:omicron1:excl
```

So who's doing that? It's a bit hacky and ugly, but we can print the process tree when we intercept the `ipadm` commands we're interested in. I'm sure there's a better way to do this, but the following seems to show what's going on:

```
bnaecker@shale : ~/helios $ pfexec dtrace -x strsize=16k -wn 'proc:::exec-success /execname == "ipadm" && strstr(curpsinfo->pr_psargs, "oxControlService0") != NULL || strstr(curpsinfo->pr_psargs, "fd00:1122:3344:101::2") != NULL/ { stop(); printf("zone %d: \"%s\"\n", curpsinfo->pr_zoneid, curpsinfo->pr_psargs); system("ptree $(pgrep sled-agent)"); system("ptree -z %d %d", curpsinfo->pr_zoneid, curpsinfo->pr_pid); system("prun %d", pid); }'
dtrace: description 'proc:::exec-success ' matched 1 probe
dtrace: allowing destructive actions
CPU     ID                    FUNCTION:NAME
  2  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2782   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o ADDR oxControlServi
      2789   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6
2789   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

 12  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2886   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o TYPE oxControlServi
      2893   /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll
    2974   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
2893   /usr/sbin/ipadm show-addr -p -o TYPE oxControlService0/ll

 20  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    2980   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T addrconf oxContro
      2981   /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll
2981   /usr/sbin/ipadm create-addr -t -T addrconf oxControlService0/ll

  7  15105         exec_common:exec-success zone 229: "bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3004   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:11
      3008   bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox
3008   bash -c /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 ox

  7  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3004   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm create-addr -t -T static -a fd00:11
      3008   /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS
3008   /usr/sbin/ipadm create-addr -t -T static -a fd00:1122:3344:101::2/64 oxControlS

 12  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3091   /usr/sbin/zlogin oxz_switch /usr/sbin/ipadm show-addr -p -o ADDR oxControlServi
      3092   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6
3092   /usr/sbin/ipadm show-addr -p -o ADDR oxControlService0/omicron6

  5  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm delete-if oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    3156   /usr/bin/pfexec /usr/sbin/route add -inet6 default -inet6 fd00:1122:3344:101::1
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    3115   /usr/sbin/ipadm delete-if oxControlService0

  9  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm create-if -t oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
    4152   /usr/sbin/svccfg -s svc:/oxide/mgd:default addpropvalue config/dns_servers astr
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    3168   /usr/sbin/ipadm create-if -t oxControlService0

  5  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    4198   /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv4 oxControlService0

  2  15105         exec_common:exec-success zone 229: "/usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0"
1314   ctrun -l child -o noorphan,regent /opt/oxide/sled-agent/sled-agent run /opt/oxi
  1315   /opt/oxide/sled-agent/sled-agent run /opt/oxide/sled-agent/pkg/config.toml
1732   /lib/svc/bin/svc.startd
  3100   /opt/oxide/zone-setup-cli/bin/zone-setup common-networking -d oxControlService0
    4740   /usr/sbin/ipadm set-ifprop -t -p mtu=9000 -m ipv6 oxControlService0
```

Here's what I see:

1. The sled-agent appears to be using `zlogin` to create the link-local and underlay addresses.
2. The `zone-setup common-networking` command appears to be calling `delete-if` after this
3. The `zone-setup common-networking` command appears to be calling `create-if` again, and then setting the MTU on that interface.

Those latter two steps look like they're from here:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/zone-setup/src/bin/zone-setup.rs#L669

which calls into this:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/illumos-utils/src/ipadm.rs#L17-L31

So this sure looks like the zone-setup service and the sled-agent are racing. I do see this succeed about 1/3rd the time, and in that case, the zone-setup service `delete-if` call does in fact appear before the `sled-agent`'s call to `create-addr`. It looks like the sled-agent does still create the underlay address in the zone, here:

https://github.com/oxidecomputer/omicron/blob/38575abf11e463993bdb953fc3ad3653cbf8a3b6/sled-agent/src/services.rs#L3916-L3952

This needs to be coordinated with the zone-setup service, to prevent it deleting the interface under these addresses; or the zone-setup service needs to not delete those interfaces, and instead only _ensure_ they exist.

**Comment by karencfv** [comment]
Hey @bnaecker thanks for catching this bug and finding the culprit! I must have ran this tens of times on a4x2 and madrid but didn't really run following the instructions on `docs/how-to-run.adoc`. I'm curious as to why this bug only appears to manifest on a single sled set up :thinking: 

I see you have a commit with a fix on the way, but please let me know if there's any way I can help. I introduced this bug after all!

**Comment by bnaecker** [comment]
I'm working on a fix now, tweaking both the SMF manifest and the details of the zone-setup service itself. Since it's a race, it's definitely possible that we only run into on systems like my machine, where there may be more overlap between the sled-agent and the zone startup process. My machine is usually quite taxed when installing Omicron, so I'm guessing the race window is embiggened relative to a Gimlet or other more powerful machines.

**Comment by karencfv** [comment]
Ah! That makes sense. Thanks again! I'm glad you caught this race before we shipped out to customers.

**Comment by bnaecker** [comment]
Ok, I believe I have a solid fix. It's a bit tricky, since there are bi-directional dependencies between `zone-setup common-networking` and the `sled-agent` in the case of the switch zone.

Here is the flow as I understand it:

- The sled agent configures the `zone-network-setup` service, which runs `zone-setup common-networking`. It provides a gateway (the sled agent's underlay address), the name of the datalink (`oxControlService0`) and a static address that is only `::1` at this point
- The sled-agent boots the zone
- The `zone-network-setup` service currently has a dependency on `svc:/milestone/multi-user:default`, which means it won't start until very late in the boot process
- When it runs, that service will: (1) create an IP interface on `oxControlService0` (it currently deletes and recreates this, which is part of the original bug); (2) set the MTU; (3) create a default route to the gateway of the sled-agent's IP address; (4) populate the file `/etc/hosts`. Importantly, it does **not** create any underlay IP addresses, because it only [does that if it has any other than `::1`](https://github.com/oxidecomputer/omicron/blob/18f2520b3a70c51d28b4230a9c595960bd515095/zone-setup/src/bin/zone-setup.rs#L683-L699), and at this point it **just** has `::1`.
- Since this service depends on `multi-user`, and the sled-agent only depends on `single-user`, the sled-agent will consider the zone up, and then [add the underlay addresses once it knows them](https://github.com/oxidecomputer/omicron/blob/18f2520b3a70c51d28b4230a9c595960bd515095/sled-agent/src/services.rs#L3919-L3981). This is another part of the race -- the `zone-setup` tool would delete these addresses if it started after the sled-agent created them. It's also why we cannot fix this by having `single-user` depend on this service: if we do that, as written, the `zone-setup` binary will spin [here](https://github.com/oxidecomputer/omicron/blob/18f2520b3a70c51d28b4230a9c595960bd515095/zone-setup/src/bin/zone-setup.rs#L714-L739), because the network _is not_ reachable at that point. It doesn't have an IPv6 address on the sled-agent's `/64`, so `route` correctly considers that network to not be directly connected. This has been relying on the sled-agent to create those underlay addresses in the past. It also explains why we don't see that on the other zones -- the sled agent only creates them once it _has_ the underlay addresses, so the `zone-setup` tool creates them directly.

My proposed fix is pretty conservative right now:

- Remove the call to `ipadm delete-if` in the `zone-setup` tool. Just ensure the interface exists, but otherwise do the same things it's always done.
- Instead of having the `zone-network-setup` SMF manifest depend on `multi-user`, let's move it "earlier" to just depend on `manifest-import` and `svc:/milestone/network`. That means it runs basically as soon as the properties applied by the sled agent are available and the network stack is up.

@citrus-it made a larger proposal, which is having the sled-agent wait on `multi-user` to start messing with the zone. We agreed to defer that because it's a much bigger and more uncertain change.

**Comment by ubedan** [comment]
Although the problem presents differently, I'm almost positive issue 6179 is related.
