### ISSUE TITLE
Blueprint execution: Nexuses operating on different blueprints could stomp on each other's external IP resource allocation

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#6239]
Reading this, I'm now concerned our current executor implementation isn't correct for IP address allocation :grimacing:. I need to go back and look at this; the specific thing that came to mind is:

* Nexus A is executing an old blueprint where zone Z has an external IP address
* Nexus B is executing a new blueprint where zone Z has been expunged

I think we could get in a situation where Nexus B deallocates the IP, then Nexus A reallocates the IP, which might cause Nexus B to fail somewhere later in execution (e.g., if it wanted to assign that IP to a different zone) or might not (if that IP is not being reassigned).

This would eventually resolve itself when Nexus A caught up to the correct blueprint, but maybe the intermediate failures here are bad and this needs some rework?

_Originally posted by @jgallagher in https://github.com/oxidecomputer/omicron/pull/6207#discussion_r1701982773_

**Comment by davepacheco** [comment]
Oops -- I just saw #6240.  Sounds like we're on the same page anyway!
