### ISSUE TITLE
500 error returned on BGP config create.

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#6244]
Further details will be provided as they become available.

**Comment by rcgoodfellow** [comment]
Ok. Don't really need more info, can just read the code. This call stack.

- https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/src/external_api/http_entrypoints.rs#L3902-L3919
- https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/src/app/bgp.rs#L18-L26
- https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/db-queries/src/db/datastore/bgp.rs#L31-L114

ends with

- https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/db-queries/src/db/datastore/bgp.rs#L113

Which means any error from this call is going to result in a 500.

**Comment by rcgoodfellow** [comment]
In the parts of the datastore code that are returning errors.

This should probably return something 404-ish on error.

https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/db-queries/src/db/datastore/bgp.rs#L48-L54


This should probably return something 409-ish

https://github.com/oxidecomputer/omicron/blob/95f1842413da10f56f27241aeb7d76b9fc9bdbdd/nexus/db-queries/src/db/datastore/bgp.rs#L89-L102

**Comment by taspelund** [comment]
@rcgoodfellow do you want me to take a swing at fixing this one?

**Comment by rcgoodfellow** [comment]
This is a part of #6245 that @internet-diglett is currently working on. But please feel free to coordinate with Levon to potentially pair up on this.
