### ISSUE TITLE
Audit BGP configuration error squashing.

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#6245]
It's been observed in 

- [x] #6244
- [ ] Report of 500 returned from deleting a BGP configuration.

There are places in the networking API where we squash errors that should carry useful diagnostic information into generic 500s. This is bad for operators as it leaves them guessing about what's going wrong. We should audit the networking APIs to seek out and correct the places where this is happening.

**Comment by internet-diglett** [comment]
#6246 can also be covered under this resolution
