### ISSUE TITLE
API should return an error when attempting to add multiple BGP configurations to a switch

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#6246]
We built the API to support multiple BGP instances with distinct ASNs per switch. However, the back end has not caught up to that aspiration yet. Until this gets implemented, we should return an error from the API when this sort of configuration is requested.

**Comment by internet-diglett** [comment]
Adding a note: the constraint we need to apply (temporarily) is that if nexus detects that the user is requesting to have more than one "local" asn on a given switch, we should respond with some sort of error saying that the request is not allowed, and if they apply multiple configs for the same asn, we should report a conflict (config for asn already exists).
