### ISSUE TITLE
Links to rfds are broken in README.md

### ISSUE THREAD

**Issue by digitalsanctum** [oxidecomputer/omicron#629]
I'm guessing this is because the rfd repo is not public...yet?

**Comment by davepacheco** [comment]
Yeah, that's right.  I'm not sure how best to handle this because I'm not sure we'll be able to make public all the RFDs that might be relevant.  I'll ask around internally.  Sorry about this!

**Comment by davepacheco** [comment]
@digitalsanctum Sorry things aren't in a better state here.  I updated the README and CONTRIBUTING.md to better communicate the current state (and not have these dead-end links!).  Is there specific information that you're looking for?  We're not trying to keep design notes secret -- it's more a matter of focusing on building the product first.

**Comment by digitalsanctum** [comment]
> @digitalsanctum Sorry things aren't in a better state here.  I updated the README and CONTRIBUTING.md to better communicate the current state (and not have these dead-end links!).  Is there specific information that you're looking for?  We're not trying to keep design notes secret -- it's more a matter of focusing on building the product first.

No, just mainly curious. I appreciate the updates. Thanks!
