### ISSUE TITLE
test failed on "main": wicket test_inventory

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#6300]
Here's a test failure from "main": https://github.com/oxidecomputer/omicron/runs/28677241691
Log: https://buildomat.eng.oxide.computer/wg/0/details/01J549359YCSA4Y921PHPZGQVM/kTzmJcz1Mc8NSLB99WIu2CWqB1KFBnc7diulpdI2Zn5NXKBa/01J5493FW2PTJ2JW51X2Q0RN9J

Excerpt:

```
--- STDERR:              wicketd::mod integration_tests::inventory::test_inventory ---
log file: /var/tmp/omicron_tmp/mod-0a881862c5602f71-test_inventory.20657.0.log
note: configured to log to "/var/tmp/omicron_tmp/mod-0a881862c5602f71-test_inventory.20657.0.log"
thread 'integration_tests::inventory::test_inventory' panicked at wicketd/tests/integration_tests/inventory.rs:84:9:
assertion `left == right` failed
  left: []
 right: [BootstrapSledDescription { id: SpIdentifier { slot: 0, type_: Sled }, baseboard: Gimlet { identifier: "SimGimlet00", model: "i86pc", revision: 0 }, bootstrap_ip: None }, BootstrapSledDescription { id: SpIdentifier { slot: 1, type_: Sled }, baseboard: Gimlet { identifier: "SimGimlet01", model: "i86pc", revision: 0 }, bootstrap_ip: None }]
```

Given that this passed on the parent commit as well as on this PR itself, I suspect this is a flake, but I haven't looked into it at all.

**Comment by faithanalog** [comment]
this test passed on my local machine on commit `914f5fd7d51f9b060dcc0382a30b607e25df49b2` so i also think it is a flake

**Comment by sunshowers** [comment]
Another failure: https://buildomat.eng.oxide.computer/wg/0/details/01J5BVA4K80CA7M27G0KKNK0DB/t4N5e5yPiF1oiJjAD8kNDVy99ybJF9rsu2TkBc2XaQL4YSx5/01J5BVAQZJFZKMYF2SD0FWA991#S5563

Naively, my guess would be a synchronization issue.

**Comment by jclulow** [comment]
This failed on the **rel/v10** branch, it seems, as well:

https://buildomat.eng.oxide.computer/wg/0/details/01J69AR918WAQNFKSBS85EAQPV/kkFMDYhAM3Vxb5ujRHlyAO9thmIAc7mHjHuicct0gS2bL8xu/01J69ARHYXXSKXKG8J49SRZVTA#S5609

**Comment by sunshowers** [comment]
https://github.com/oxidecomputer/omicron/pull/6456 is a proposed fix.
