### ISSUE TITLE
helios-deploy test failed in CI: time not synchronized

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#6367]
This CI run failed:
https://github.com/oxidecomputer/omicron/runs/28876935637

This is on a PR, not main, but that PR only changes Nexus logging and this failure happened long before Nexus was on the scene so I think this is a problem in "main".  The failure is the usual:

```
+ zoneadm list
+ grep nexus
+ [[ 301 -gt 300 ]]
+ echo 'Failed to start at least one nexus zone after 300 seconds'
+ exit 1
Failed to start at least one nexus zone after 300 seconds
```

([full log](https://buildomat.eng.oxide.computer/wg/0/details/01J5ECV6ZP1XJMP67RGMYPENE5/kmdxmkIVaQQ2xKx2tgtYF76SoEXEifuXZG65b9wY68aDh8yu/01J5ECVPV32C18GM04QW7KYG9N#S2008))

Over in the [sled agent log](https://buildomat.eng.oxide.computer/wg/0/artefact/01J5ECV6ZP1XJMP67RGMYPENE5/kmdxmkIVaQQ2xKx2tgtYF76SoEXEifuXZG65b9wY68aDh8yu/01J5ECVPV32C18GM04QW7KYG9N/01J5EFB2WH6PP2452BX89DGVC2/oxide-sled-agent:default.log?format=x-bunyan), sled agent started deploying the NTP zone at 20:46:03Z:

```
2024-08-16T20:46:03.175Z	INFO	SledAgent (ServiceManager): Configuring new Omicron zone: oxz_ntp_990ff81a-3ab0-4629-88a5-438861e8c0cc
    file = illumos-utils/src/zone.rs:316
```

but 4.5 minutes later (which is almost as long as the test waits) time is still not synchronized:

```
2024-08-16T20:50:29.580Z	WARN	SledAgent (RSS): Time is not yet synchronized
    error = "Time is synchronized on 0/1 sleds"
    file = sled-agent/src/rack_setup/service.rs:663
```

**Comment by bnaecker** [comment]
I think we hit this again [here](https://buildomat.eng.oxide.computer/wg/0/details/01J81914NN4KCB4MK0GQ61DR6Y/OXFkwtEFF1kS4girhVNWDBq8pLOTM48s85mkIcflzACuTI8B/01J8191DFYB1YNTBSBT1NJR975), as part of [this](https://github.com/oxidecomputer/omicron/pull/6593/checks?check_run_id=30289793672) CI checksuite.

Similar to above, the [sled agent log](https://buildomat.eng.oxide.computer/wg/0/artefact/01J81914NN4KCB4MK0GQ61DR6Y/OXFkwtEFF1kS4girhVNWDBq8pLOTM48s85mkIcflzACuTI8B/01J8191DFYB1YNTBSBT1NJR975/01J81BPHAX9A7MBM5RSMBATPJK/oxide-sled-agent:default.log?format=x-bunyan) shows that it started to launch the NTP zone here:

```
2024-09-18T01:19:22.542Z	INFO	SledAgent (ServiceManager): Configuring new Omicron zone: oxz_ntp_a090d464-308f-4a12-a591-e64fb9217d52
    file = illumos-utils/src/zone.rs:316
```

and that it's still not synchronized [at the end of the file](https://buildomat.eng.oxide.computer/wg/0/artefact/01J81914NN4KCB4MK0GQ61DR6Y/OXFkwtEFF1kS4girhVNWDBq8pLOTM48s85mkIcflzACuTI8B/01J8191DFYB1YNTBSBT1NJR975/01J81BPHAX9A7MBM5RSMBATPJK/oxide-sled-agent:default.log?format=x-bunyan#L811), which is about 5 minutes later:

```
2024-09-18T01:24:40.909Z	WARN	SledAgent (RSS): Time is not yet synchronized
    error = "Time is synchronized on 0/1 sleds"
    file = sled-agent/src/rack_setup/service.rs:682
```

**Comment by davepacheco** [comment]
Closing as a dup of #5349.
