### ISSUE TITLE
Upgrade from CRDB schema version 88.0.0 failed: null value in column "lldp_link_config_id" violates not-null constraint

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#6433]
Schema update failed when execute `schema-updater` on rack2
```
  ...
  86.0.0
  87.0.0
  88.0.0 (reported by database)
  89.0.0
  90.0.0 (expected by Nexus)
root@oxz_nexus_2898657e:~# /opt/oxide/omicron-nexus/bin/schema-updater --crdb postgresql://root@[fd00:1122:3344:107::3]:32221/omicron?sslmode=disable up
Upgrading to 90.0.0
Aug 25 20:13:10.841 WARN Retryable transaction failure, retry_after (ms): 46, transaction: apply_schema_update, unit: schema_updater
Error: update to 89.0.0-step.1, applying step "up2.sql"

Caused by:
    Internal Error: unexpected database error: null value in column "lldp_link_config_id" violates not-null constraint

**Comment by smklein** [comment]
Originally added in https://github.com/oxidecomputer/omicron/pull/6185

The SQL being rejected is the following:

```sql
ALTER TABLE omicron.public.switch_port_settings_link_config ADD COLUMN IF NOT EXISTS lldp_link_config_id UUID NOT NULL;
```

In retrospect, this makes sense, for any SQL of the form:

```sql
ALTER TABLE t ADD COLUMN IF NOT EXISTS c c_type NOT NULL;
```

If the table `t` exists, and the column `c` doesn't exist, then there's no instruction for back-filling the `c` column with data.

This column should probably be nullable until we're confident it is populated for all tables. For other columns, we've used a `DEFAULT` value, but that probably doesn't make much sense for a UUID type.

**Comment by askfongjojo** [comment]
Thanks for weighing in @smklein. LLDP config should be optional, I believe; so making the field nullable is probably the fix we need.
