### ISSUE TITLE
ClickHouse native TCP ports need to go into internal DNS

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#6598]
Right now, we create SRV records in internal DNS for the ClickHouse HTTP addresses. We need to also add records for the addresses where it listens for the native protocol. I'm actually not sure how to do that, since we already use the `_clickhouse._tcp.***` DNS name for the HTTP ports. We might need to name that something like `_clickhouse-native._tcp.***` or similar. That definitely cannot go in the same SRV record, since those are very different backends.

**Comment by davepacheco** [comment]
Yeah I think we'd just add a different name for this since it's logically a different service.
