### ISSUE TITLE
Default 128 KB TCP receive buffer causes slow image uploads when using a single TCP connection

### ISSUE THREAD

**Issue by wfchandler** [oxidecomputer/omicron#6601]
Browsers using HTTP/2 with the to the image upload web console interface will multiplex the bulk write calls over a single TCP connection. The default maximum TCP receive buffer of 128 KB severely limits to total throughput available to a single connection, vs the eight separate TCP connections used by the CLI for the same function. This causes image uploads via the console to be several times slower than the CLI. Increasing the maximum receive buffer to 1 MB gives a roughly 3x improvement in upload speed, see https://github.com/oxidecomputer/console/issues/2096 for further details.

For testing purposes we increased the buffer size by running `ipadm set-prop -t -p recv_buf=1024000 tcp` in the nexus zone, but I don't know if a broad change like that is the best approach for a permanent fix. Perhaps it would be better to only update `SO_RCVBUF` on specific sockets to limit the scope.

**Comment by davepacheco** [comment]
It's worth mentioning that this is the most untrusted interface to the system (exposed on the customer network) and soaking up memory in receive buffers is a way for malicious (or broken) clients to tie up server resources.  I've no reason to think that 1 MiB is too large (nor that 128 KiB is safe, for that matter!) -- just that this is a risk in making the value _too_ large.

**Comment by jclulow** [comment]
It may also be worth changing the congestion control algorithm to **cubic**.
