### ISSUE TITLE
spoof authn could use Bearer scheme

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#675]
HTTP Authentication supports [a bunch of schemes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes), including Bearer per [RFC 6750](https://datatracker.ietf.org/doc/html/rfc6750).  @jessfraz mentioned it would be a big help in developing clients if we had the "spoof" authn mode use the RFC 6750 bearer scheme rather than a custom header.

I've only taken a quick pass but I don't see any problems with doing this.  There's basically nothing about the semantics of the token aside from being a bearer token.  The standard uuid format is a subset of what's allowed for the token.  And I don't think we're already using this header for console session authn.  We're violating basically all of the security recommendations of the RFC by having this be a well-known uuid, but it's no more insecure than the "spoof" scheme is today, and that's the nature of the "spoof" scheme -- it's intended for environments where we haven't _yet_ built the rest of the infrastructure required to do this properly (e.g., short-lived API tokens, key distribution for signature verification, signed certificate distribution to protect confidentiality in flight, etc.)

**Comment by david-crespo** [comment]
Confirmed we are not using it in console now or in the future.

**Comment by davepacheco** [comment]
Okay, the format here is going to be a header `Authorization: Bearer <token>`.  The question is: what's `token`?  Here are some ideas.  In all of these, `$uuid` is the uuid that you currently put into the `x-oxide-spoof` header:

- `$uuid`.  Super simple, but not very future-proof if we decide to support any kind of bearer token.  Also, the RFC implies this is a base64-encoded thing -- in this case, this only happens to work because the uuid character set is a subset of the base64 character set.
- a base64-encoded JSON value of something like `{ "v": 1", "kind": "spoof", "id": "$uuid" }`.  This is more future-proof and seems more consistent with the RFC (because we're base64-encoding structured data) but we might find in the future we want some other kind of format and this over-engineering will be for naught.
- `oxide-spoof-$uuid`, where `$uuid` is the uuid that you would be picking.  This strikes me as a good middle ground because it's easy for us to identify and still lets us support other schemes in the future as long as they don't happen to start with "oxide-spoof-".

In all of these cases, I think we _can_ support other formats in the future provided that they can be distinguished unambiguously.  If we control those formats, we can always make that the case.  If we don't control them, we can't necessarily...but given the intended scope of this mechanism (a demo/dev/test-only mechanism, and a potentially short-lived one at that), I'd suggest not worrying about this too much right now.

I'm going to go with `oxide-spoof-$uuid`. (CC @jessfraz)

**Comment by jessfraz** [comment]
i dont mind either way
