### ISSUE TITLE
Split `clickhouse-admin` into 2 separate servers

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#6779]
Right now, the same `clickhouse-admin` service run in the `ClickhouseKeeper` and `ClickhouseServer` zones. However, each of those zones uses a disjoint set of endpoints which implies that we should have two separate admin servers: `clickhouse-admin-server` and `clickhouse-admin-keeper`.

**Comment by andrewjstone** [comment]
As part of this, we should move types required by nexus into `clickhouse-admin-types` (or an equivalent types library).

**Comment by davepacheco** [comment]
Thanks.  That is part (but unfortunately only part) of #6829.
