### ISSUE TITLE
clickhouse-admin-client is missing API metadata

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#6827]
If you run `cargo xtask ls-apis apis` (or any other subcommand), you get this warning:

```
$ cargo xtask ls-apis apis
...
warning: workspace omicron: found client package missing from API manifest: clickhouse-admin-client
...
```

This is because we've recently added a package called `clickhouse-admin-client` that depends on Progenitor.  `ls-apis` correctly infers that it's a Progenitor-based API client.  But it has no metadata about the API.

**Comment by andrewjstone** [comment]
I can likely take care of this when working on https://github.com/oxidecomputer/omicron/issues/6779

**Comment by davepacheco** [comment]
I wound up doing it in #6830, for what it's worth.
