### ISSUE TITLE
InsertVpcSubnetQuery only detects conflicts if CIDR mask is >= than the CIDR mask of an existing VPC Subnet

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/omicron#6870]
When using the external API to create a new VPC Subnet (POST /v1/vpc-subnets), an HTTP 400 (Bad Request) response is returned with the message `IP address range '{subnet}' conflicts with an existing subnet` when there is a pre-existing VPC Subnet whose IP Block overlaps with the proposed new IP Block in the request.

However, the conflict detection logic seems to be flawed, as this 400 error is only returned if the conflict occurs when the CIDR/subnet mask is greater than or equal to the CIDR mask of the pre-existing subnet.  If the new IP Block has a CIDR mask that is less than the mask of the pre-existing subnet, the new VPC Subnet is created without an error... allowing for multiple subnets to be created with overlapping IP ranges.

The following example is created simply by adding new VPC Subnets to the Default VPC, all using the default network prefix (172.30.0.0) but with different CIDR masks.

The Default subnet is 172.30.0.0/24.  When you attempt to create a new subnet from 172.30.0.0 with a mask >= /24, the HTTP 400 response is returned as expected:
![Image](https://github.com/user-attachments/assets/a12ba3ea-63ec-4143-bb23-c8b7f4624a27)

But the API incorrectly allows the user to create new subnets with progressively shorter masks (<= the shortest CIDR mask for this block, i.e. starting with  <= /23).  The following screenshot shows 3 subnets that the API allowed me to create (which all have overlapping IPs e.g. 172.30.0.10), so long as I created them in an order of descending CIDR mask lengths (/23 -> /22 -> /21 -> /20 -> ...)
![Image](https://github.com/user-attachments/assets/7201477e-3985-4cee-a7c8-0913d680b5b0)

**Comment by taspelund** [comment]
It looks to me like the issue is likely somewhere in the massive SQL/diesel blob for `pub struct InsertVpcSubnetQuery` in nexus/db-queries/src/db/queries/vpc_subnet.rs

**Comment by taspelund** [comment]
There's a good chance I'm not understanding all the logic or nuances of the SQL query we're using, but from my initial glances at the cockroachdb docs, it seems like maybe the function we're using to detect collisions is being misused, or it doesn't cover all the cases we need.

The [CRDB v22.1 function docs](https://www.cockroachlabs.com/docs/v22.1/functions-and-operators) seem to indicate that `inet_contains_or_equals` takes two positional arguments of different types, `container: inet` and `val: inet`, and checks whether the val is present in the container.

Maybe this could be explained if we're only evaluating variables x and y in one order, i.e. `inet_contains_or_equals(x, y)`.
e.g.
If `x = 172.30.0.0/24` and `y = 172.30.0.0/25`, then `x` would contain `y`.
However, if `x = 172.30.0.0/24` and `y = 172.30.0.0/23`, then `x` would not contain `y` but the two ranges would still overlap.

If I'm on the right track, then I imagine we'd want to do something akin to calling `inet_contains_or_equals(x, y)` in addition to `inet_contains_or_equals(y, x)` in order to ensure the overlap is compared in both directions.  Another option might be to implement the logic our own way using different functions (e.g. maybe `masklen()`).

**Comment by bnaecker** [comment]
Nice catch, thanks! I definitely thought that method tested both directions already, but I was either reading different documentation or just didn't understand it. I think the simplest thing is to switch from calling the method to using the `&&` operator. It's not 100% clear from the CRDB documentation, but Postgres makes it clear that tests overlap in either direction. And checking against our version of CRDB, we see the same behavior:

```
bnaecker@flint : ~/file-cabinet/oxide/omicron $ cockroach sql --url postgresql://root@[::1]:32221/omicron?sslmode=disable
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v22.1.9 (x86_64-apple-darwin19, built 2022/10/17 18:39:01, go1.17.11) (same version as client)
# Cluster ID: 22407a3b-17ed-49b2-8359-48d6d6ebc32d
#
# Enter \? for a brief introduction.
#
root@[::1]:32221/omicron> select inet_contains_or_equals('192.168.1.0/24', '192.168.1.0/28');
  inet_contains_or_equals
---------------------------
           true
(1 row)


Time: 2ms total (execution 1ms / network 1ms)

root@[::1]:32221/omicron> select inet_contains_or_equals('192.168.1.0/28', '192.168.1.0/24');
  inet_contains_or_equals
---------------------------
           false
(1 row)


Time: 1ms total (execution 1ms / network 0ms)

root@[::1]:32221/omicron> select '192.168.1.0/24' && '192.168.1.0/28';
  ?column?
------------
    true
(1 row)


Time: 9ms total (execution 9ms / network 0ms)

root@[::1]:32221/omicron> select '192.168.1.0/28' && '192.168.1.0/24';
  ?column?
------------
    true
(1 row)


Time: 1ms total (execution 0ms / network 0ms)

root@[::1]:32221/omicron>
```
