### ISSUE TITLE
[reconfigurator] Builder API does not provide guarantees that datasets are provisioned for zones, but should

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#6990]
Today, if you use the planner to provision a new zone, it'll provision a new zone in the constructed blueprint, and then invoke `sled_ensure_datasets`, which will create necessary records for that zone to exist.

However, if you use the `reconfigurator-cli` to provision a new zone, it'll make a new zone in the blueprint, but it will be missing a corresponding dataset (see also: https://github.com/oxidecomputer/omicron/issues/6987 , where we could catch this!). I believe our `live-tests` are also suffering from the same defect.

This issue tracks two things:
- [ ] We should patch these callsites, where zones are provisioned without datasets, to ensure that datasets are actually getting provisioned
- [ ] We should update the API to the builder to make it harder to misuse - provisioning a new zone should likely immediately provision a corresponding dataset (or datasets).

FYI @jgallagher

**Comment by jgallagher** [comment]
Fixed by https://github.com/oxidecomputer/omicron/pull/7105
