### ISSUE TITLE
unexpected response rebooting a "stopped" instance

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#705]
I tried to reboot a "stopped" instance with `oxapi_demo`.  I got back this response:

```
$ ./tools/oxapi_demo instance_reboot o1 p1 i1
+ curl -sSq http://127.0.0.1:12220/organizations/o1/projects/p1/instances/i1/reboot -X POST -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "request_id": "e9862eb9-168d-4a37-8c63-efa50eab371c",
  "error_code": "InvalidRequest",
  "message": "Unexpected Response Response { url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: \"/instances/3d15b388-ced1-490d-a966-bb83f56250ae\", query: None, fragment: None }, status: 400, headers: {\"content-type\": \"application/json\", \"x-request-id\": \"bc23b9b3-37da-4029-8605-59a753d411d8\", \"content-length\": \"152\", \"date\": \"Fri, 25 Feb 2022 16:59:35 GMT\"} }"
}
```

The 400 status code seems reasonable, as does the "InvalidRequest" "error_code".  But the message is not at all right.

Interestingly, what Nexus logged _is_ right:

```
Feb 25 16:59:35.812 INFO request completed, error_message_external: cannot reboot instance in state "stopped", error_message_internal: cannot reboot instance in state "stopped", response_code: 400, uri: /instances/3d15b388-ced1-490d-a966-bb83f56250ae, method: PUT, req_id: bc23b9b3-37da-4029-8605-59a753d411d8, remote_addr: 127.0.0.1:57093, local_addr: 127.0.0.1:12345, component: dropshot 
```

Also weird: the request id in the log message doesn't match the request id in the response.  You might think I was looking at a response for a different request.  But I reproduced this with:

```
dap@ivanova omicron $ ./tools/oxapi_demo organization_delete o1 
+ curl -sSq http://127.0.0.1:12220/organizations/o1 -X DELETE -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
dap@ivanova omicron $ ./tools/oxapi_demo organizations_list
+ curl -sSq http://127.0.0.1:12220/organizations -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "next_page": null,
  "items": []
}
dap@ivanova omicron $ ./tools/oxapi_demo organization_create_demo o1
+ curl -sSq http://127.0.0.1:12220/organizations -X POST -T - -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "id": "04dae283-c58d-4abb-80a8-7f541ef4226d",
  "name": "o1",
  "description": "an organization called o1",
  "time_created": "2022-02-25T17:03:13.632470Z",
  "time_modified": "2022-02-25T17:03:13.632470Z"
}
dap@ivanova omicron $ ./tools/oxapi_demo project_create_demo o1 p1
+ curl -sSq http://127.0.0.1:12220/organizations/o1/projects -X POST -T - -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "id": "7ab7a7ab-c994-4f44-bd84-b5230b9a7fde",
  "name": "p1",
  "description": "a project called p1",
  "time_created": "2022-02-25T17:03:17.996272Z",
  "time_modified": "2022-02-25T17:03:17.996272Z",
  "organization_id": "04dae283-c58d-4abb-80a8-7f541ef4226d"
}
dap@ivanova omicron $ ./tools/oxapi_demo instance_create_demo o1 p1 i1
+ curl -sSq http://127.0.0.1:12220/organizations/o1/projects/p1/instances -X POST -T - -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "id": "b085b59c-f81f-4a6e-8b17-32b0f409a03b",
  "name": "i1",
  "description": "an instance called i1",
  "time_created": "2022-02-25T17:03:26.161127Z",
  "time_modified": "2022-02-25T17:03:26.161127Z",
  "project_id": "7ab7a7ab-c994-4f44-bd84-b5230b9a7fde",
  "ncpus": 1,
  "memory": 268435456,
  "hostname": "i1",
  "run_state": "starting",
  "time_run_state_updated": "2022-02-25T17:03:26.170406Z"
}
dap@ivanova omicron $ ./tools/oxapi_demo instance_stop o1 p1 i1
+ curl -sSq http://127.0.0.1:12220/organizations/o1/projects/p1/instances/i1/stop -X POST -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
+ json -ga
{
  "id": "b085b59c-f81f-4a6e-8b17-32b0f409a03b",
  "name": "i1",
  "description": "an instance called i1",
  "time_created": "2022-02-25T17:03:26.161127Z",
  "time_modified": "2022-02-25T17:03:26.161127Z",
  "project_id": "7ab7a7ab-c994-4f44-bd84-b5230b9a7fde",
  "ncpus": 1,
  "memory": 268435456,
  "hostname": "i1",
  "run_state": "stopping",
  "time_run_state_updated": "2022-02-25T17:03:34.667260Z"
}
dap@ivanova omicron $ curl -i http://127.0.0.1:12220/organizations/o1/projects/p1/instances/i1/reboot -X POST -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
HTTP/1.1 400 Bad Request
content-type: application/json
x-request-id: 6bdd2b3c-f515-4eb6-ba1b-dcfacd100ab6
content-length: 562
date: Fri, 25 Feb 2022 17:03:59 GMT

{
  "request_id": "6bdd2b3c-f515-4eb6-ba1b-dcfacd100ab6",
  "error_code": "InvalidRequest",
  "message": "Unexpected Response Response { url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: \"/instances/b085b59c-f81f-4a6e-8b17-32b0f409a03b\", query: None, fragment: None }, status: 400, headers: {\"content-type\": \"application/json\", \"x-request-id\": \"0d5a1cc2-f0fb-4dac-a58e-d73c7172430e\", \"content-length\": \"152\", \"date\": \"Fri, 25 Feb 2022 17:03:59 GMT\"} }"
}
```

Note for that last one I used `curl` directly so I could use `-i` to get the response headers.  The request_id in the response headers matches what's in the error response.  But in the Nexus log I have:

```
Feb 25 17:03:59.822 INFO request completed, error_message_external: cannot reboot instance in state "stopped", error_message_internal: cannot reboot instance in state "stopped", response_code: 400, uri: /instances/b085b59c-f81f-4a6e-8b17-32b0f409a03b, method: PUT, req_id: 0d5a1cc2-f0fb-4dac-a58e-d73c7172430e, remote_addr: 127.0.0.1:55892, local_addr: 127.0.0.1:12345, component: dropshot
```

That's at the same time as the client request and I have no request in the Nexus log with request id `6bdd2b3c-f515-4eb6-ba1b-dcfacd100ab6`.

**Comment by smklein** [comment]
Is this with the simulated sled agent?

**Comment by davepacheco** [comment]
Ah, good news about the request id: I _was_ looking at the wrong thing.  The log message above is from the sled agent log.  The Nexus log has this for the first request:

```
Feb 25 16:59:35.813 INFO request completed, error_message_external: Unexpected Response Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: "/instances/3d15b388-ced1-490d-a966-bb83f56250ae", query: None, fragment: None }, status: 400, headers: {"content-type": "application/json", "x-request-id": "bc23b9b3-37da-4029-8605-59a753d411d8", "content-length": "152", "date": "Fri, 25 Feb 2022 16:59:35 GMT"} }, error_message_internal: Unexpected Response Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: "/instances/3d15b388-ced1-490d-a966-bb83f56250ae", query: None, fragment: None }, status: 400, headers: {"content-type": "application/json", "x-request-id": "bc23b9b3-37da-4029-8605-59a753d411d8", "content-length": "152", "date": "Fri, 25 Feb 2022 16:59:35 GMT"} }, response_code: 400, uri: /organizations/o1/projects/p1/instances/i1/reboot, method: POST, req_id: e9862eb9-168d-4a37-8c63-efa50eab371c, remote_addr: 127.0.0.1:51749, local_addr: 127.0.0.1:12220, component: dropshot_external, name: e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c
```

and this for the second one:

```
Feb 25 17:03:59.823 INFO request completed, error_message_external: Unexpected Response Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: "/instances/b085b59c-f81f-4a6e-8b17-32b0f409a03b", query: None, fragment: None }, status: 400, headers: {"content-type": "application/json", "x-request-id": "0d5a1cc2-f0fb-4dac-a58e-d73c7172430e", "content-length": "152", "date": "Fri, 25 Feb 2022 17:03:59 GMT"} }, error_message_internal: Unexpected Response Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(12345), path: "/instances/b085b59c-f81f-4a6e-8b17-32b0f409a03b", query: None, fragment: None }, status: 400, headers: {"content-type": "application/json", "x-request-id": "0d5a1cc2-f0fb-4dac-a58e-d73c7172430e", "content-length": "152", "date": "Fri, 25 Feb 2022 17:03:59 GMT"} }, response_code: 400, uri: /organizations/o1/projects/p1/instances/i1/reboot, method: POST, req_id: 6bdd2b3c-f515-4eb6-ba1b-dcfacd100ab6, remote_addr: 127.0.0.1:33648, local_addr: 127.0.0.1:12220, component: dropshot_external, name: e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c
```

So the request ids are okay, although it does raise the question of whether we should preserve the request-id for calls to internal services.  This can be kind of a mixed bag, since it means request-ids aren't necessarily unique in those remote services.

---

What about that error?  I think maybe this is coming back from Progenitor.  I'd expect the first error to be generated here, where we invoke the progenitor-generated `instance_put` function:
https://github.com/oxidecomputer/omicron/blob/main/nexus/src/nexus.rs#L1253-L1263

The log message looks like it's trying to log information about a request to the Sled Agent server (based on the local port and URL, though it's a little hard to read as `Debug` output).  It failed with a 400.  That makes sense.  I'm not sure why that produced an "Unexpected Response" error.  And I'm not sure why we serialized it straight out the front door -- that seems potentially bad, as these contain internal details from the Sled Agent.

**Comment by davepacheco** [comment]
> Is this with the simulated sled agent?

Yes.  I set up this set of services using the README instructions to run CockroachDB, Nexus, and a simulated sled agent.

**Comment by davepacheco** [comment]
From [the Progenitor docs](https://github.com/oxidecomputer/progenitor/blob/main/docs/progenitor-client.md), it looks like we'd get an unexpected response if we got a response that wasn't in the OpenAPI doc.  Maybe the fix here is just to get generic error responses into the OpenAPI schema (which is covered by a few open issues right now, I think).

Once we do that, though, will we still wind up serializing the response right back out the front door?

**Comment by smklein** [comment]
The behavior in the sled agent makes this behavior look like it's "working as intended", though perhaps the error message could be more about indicating what are "valid" states to reboot from:

https://github.com/oxidecomputer/omicron/blob/53c6dc75dc49365983c032a73761320fbfe7e4f7/sled-agent/src/common/instance.rs#L240-L262

The behavior of "reboot" is aligned with the notion within Propolis itself - in order to reboot, the instance must be currently running.  Otherwise, I think the expected behavior is that a caller will invoke "start" to initialize a stopped instance.

Granted, we *could* make the case of "call reboot on a stopped instance" treat the request identically to calling "start"?

**Comment by davepacheco** [comment]
> The behavior in the sled agent makes this behavior look like it's "working as intended"

I agreed -- I don't think there's a problem with the simulated Sled Agent here.

**Comment by smklein** [comment]
Ah, apologies, I think I misread what was being called out as a problem in the initial issue.

**Comment by davepacheco** [comment]
I wrote:

> Once we do that, though, will we still wind up serializing the response right back out the front door?

I think the reason we're sending it back out the front door is because we're taking the result of `instance_put` and using `map_err(Error::from)`:
https://github.com/oxidecomputer/omicron/blob/main/nexus/src/nexus.rs#L1263

which I believe lands us here:
https://github.com/oxidecomputer/omicron/blob/07575e561f034fd58cd9163497bf09b393c8a876/common/src/api/external/error.rs#L258-L286

and more specifically L279-281.

I suspect what we want to do here is look at the returned error for specific, known problems (like rebooting a stopped instance) and generated appropriate front-door errors.  There maybe should be a catch-all for 500s and 503s that send them back out the front door.  (The current implementation does this for 500s, but would translate a 503 to a 500, which I don't think is right.)  And if we find some other response that we didn't expect, I think that should probably be a 500 out the front door.

**Comment by ahl** [comment]
> (The current implementation does this for 500s, but would translate a 503 to a 500, which I don't think is right.)

I would argue that a 503 from an internal service is not that different from, say, a function call that returns a `Result::Err` unexpectedly. It's also similar to receiving a success response we didn't anticipate or an error response with a body of an unknown schema. I think all of those are "internal server errors" from the perspective of the external client making a 500 the right response. It seems like a 503 in that situation could leak information; I'm also not sure how a client could make use of it--and it could be confused with a 503 from Nexus if that "boundary" service were unavailable.

**Comment by askfongjojo** [comment]
With the recent API error handling improvements to surface Nexus errors, we can consider this issue fixed?
```
curl -i http://127.0.0.1:12220/v1/instances/6f10eb54-69f3-4294-8950-ed46c703a506/reboot -X POST -H 'Authorization: Bearer oxide-spoof-001de000-05e4-4000-8000-000000004007'
HTTP/1.1 400 Bad Request
content-type: application/json
x-request-id: d154c7b1-715c-4e05-96eb-57a96c484ea7
content-length: 152
date: Mon, 03 Apr 2023 23:54:36 GMT

{
  "request_id": "d154c7b1-715c-4e05-96eb-57a96c484ea7",
  "error_code": "InvalidRequest",
  "message": "cannot reboot instance in state \"stopped\""
```

**Comment by davepacheco** [comment]
I think so, especially given that approximately all of this code has changed since the issue was filed.
