### ISSUE TITLE
test failed in CI: `test_read_only_region_reference_counting_layers`

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#7074]
This test failed on a CI run on **"main"**:

https://github.com/oxidecomputer/omicron/runs/33007030367

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01JCP2PVH1NQBJ6W13CHTRTAYK/mPg71nJsUy40c1kKZsbCgTFv4rnQRCVS3Msv0d5KXvuKVtHe/01JCP2QC00CGVNC8P5NEQ6AHA9#S6088

Excerpt from the log showing the failure:

```
--- STDERR:              omicron-nexus::test_all integration_tests::volume_management::test_read_only_region_reference_counting_layers ---
log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.0.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.0.log"
DB URL: postgresql://root@[::1]:35541/omicron?sslmode=disable
DB address: [::1]:35541
log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.2.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.2.log"
log file: /var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.3.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-6bfc5f3ebb6481b6-test_read_only_region_reference_counting_layers.23339.3.log"
[]
[]
[]
[]
[]
thread 'integration_tests::volume_management::test_read_only_region_reference_counting_layers' panicked at /work/oxidecomputer/omicron/nexus/test-utils/src/background.rs:338:6:
called `Result::unwrap()` on an `Err` value: TimedOut(20.437606308s)
```

I don't have context, but is the timeout a bit low for CI while the system is being slammed with all the other concurrent tests?

**Comment by jmpesp** [comment]
> I don't have context, but is the timeout a bit low for CI while the system is being slammed with all the other concurrent tests?

That's from `run_replacement_tasks_to_completion` which will run the background tasks related to region replacement and region snapshot replacement until they aren't doing anything anymore. Let's bump that to 60s: https://github.com/oxidecomputer/omicron/pull/7077

**Comment by jmpesp** [comment]
Leaving this open for a bit to see if that PR fixed it
