### ISSUE TITLE
Clickhouse migration to v13 dropped some data

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#7181]
Apologies if this is expected behavior, but @plotnick and I weren't sure so figured we'd err on the side of filing.

To test #7171, we installed R11 on london, left it running overnight, then upgraded to that branch. Prior to the upgrade, clickhouse was on version 12. To confirm we didn't lose any data across the upgrade, I spot checked the number and age of the values in `measurements_f64`:

```
oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select * from version;

SELECT *
FROM version

Query id: 7ec809e8-2e6b-447f-922f-79e135ea210c

┌─value─┬─────────────────────timestamp─┐
│    12 │ 2024-11-26 22:33:13.000000000 │
└───────┴───────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.

oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select count(*) from measurements_f64;

SELECT count(*)
FROM measurements_f64

Query id: b881dc0a-0d1f-4689-8a60-9b7ff9eeaebf

┌─count()─┐
│   12941 │
└─────────┘

1 row in set. Elapsed: 0.011 sec.

oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select timestamp from measurements_f64 order by timestamp asc limit 1;

SELECT timestamp
FROM measurements_f64
ORDER BY timestamp ASC
LIMIT 1

Query id: de8d576d-4cc4-4020-a209-332c5b4b5ac5

┌─────────────────────timestamp─┐
│ 2024-11-26 22:34:24.679307106 │
└───────────────────────────────┘

1 row in set. Elapsed: 0.004 sec. Processed 12.94 thousand rows, 103.54 KB (2.88 million rows/s., 23.08 MB/s.)
Peak memory usage: 300.57 KiB.
```

After running the schema migration to v13, there were no values left in `measurements_f64`:

```
oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select * from version;

SELECT *
FROM version

Query id: 03de5cb8-d071-4bed-a72e-984ae6842547

┌─value─┬─────────────────────timestamp─┐
│    12 │ 2024-11-26 22:33:13.000000000 │
└───────┴───────────────────────────────┘
┌─value─┬─────────────────────timestamp─┐
│    13 │ 2024-11-27 19:37:58.000000000 │
└───────┴───────────────────────────────┘

2 rows in set. Elapsed: 0.003 sec.

oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select count(*) from measurements_f64;

SELECT count(*)
FROM measurements_f64

Query id: fd499a0d-4cdd-4073-9698-4855c256e565

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.011 sec.
```

However, the existence of the version=12 fow and the oldest values in `measurements_f32` dating to the day before confirm we didn't wipe _all_ the data:

```
oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select count(*) from measurements_f32;

SELECT count(*)
FROM measurements_f32

Query id: febd88d5-d473-44e4-b599-1abdab2a3bbb

┌──count()─┐
│ 92010401 │
└──────────┘

1 row in set. Elapsed: 0.011 sec.

oxz_clickhouse_279f1152-6c8d-4b2b-956f-458b495b2795.local :) select timestamp from measurements_f32 order by timestamp asc limit 1;

SELECT timestamp
FROM measurements_f32
ORDER BY timestamp ASC
LIMIT 1

Query id: 2986f6fd-f7c7-499e-8057-93d9a8cd3dd3

┌─────────────────────timestamp─┐
│ 2024-11-26 22:27:36.342757447 │
└───────────────────────────────┘

1 row in set. Elapsed: 1.151 sec. Processed 92.01 million rows, 736.08 MB (79.93 million rows/s., 639.41 MB/s.)
Peak memory usage: 35.02 MiB.
```

I'm not sure what's expected across a clickhouse migration; I do see a [timeseries-to-delete.txt](https://github.com/oxidecomputer/omicron/blob/888876a62c91131f4f8ae31536ea46673646a30b/oximeter/db/schema/single-node/13/timeseries-to-delete.txt) so maybe all the f64 values were in timeseries that we intentionally deleted?

**Comment by bnaecker** [comment]
It’s possible that the data was intentionally deleted, if it’s in the list of timeseries to delete during the upgrade. I also notice that the earliest timestamp is almost exactly one month ago. That is near the current TTL of 30 days for the data. Is it possible that all the data is older than the TTL at this point?

To add to the confusion, data is only deleted during a merge, which is a background task that’s not really controllable or predictable.

**Comment by jgallagher** [comment]
This was on london which had only been set up for ~24 hours, so we definitely weren't near the TTL (although also we don't have any timestamps from a month ago, I hope? 😅)

**Comment by bnaecker** [comment]
Oh, I misread that as last month on the 26th, so yeah it’s not the TTL! You could look at the query log to see if the deletion query ran?

**Comment by jgallagher** [comment]
Sorry, this setup is long gone. I'm inclined to close this as "working as expected"? Feel free to reopen if you think we need to test it more carefully.

**Comment by bnaecker** [comment]
I'm inclined to agree. The `dendrite:sample_collection_duration` timeseries was in the list of those to delete in v13. The data for that would show up in the `measurements_f64` table. It's also sampled every 10 seconds, and this was left running for around 21 hours, so we'd expect 21 * 60 * 10 samples. That's 12,600, which is very close to the 12,941 samples you did observe.
