### ISSUE TITLE
[packaging][uninstall] Uninstall command should also uninstall zones

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#723]
Note: This issue tracks follow-up work from https://github.com/oxidecomputer/omicron/pull/686

`omicron-package uninstall` currently uninstalls all services, but does not yet uninstall zones. Instead, it relies on the "next boot of the sled agent" to remove them.

Having the packaging tool disable zones would actually be doable, with the following:
- Refactor the `halt_and_remove` code from `src/illumos/zone.rs` into a location accessible across other Omicron packages
- Query for omicron-owned zones within the packaging tool
- Invoke `halt_and_remove` on those zones

**Comment by bnaecker** [comment]
Closed by #909
