### ISSUE TITLE
[sled-agent] Initialize multi-node CockroachDB, rather than single-node

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#727]
Note: This issue tracks a follow-up from https://github.com/oxidecomputer/omicron/pull/686

CockroachDB is initialized using "start-single-node" instead of "start".

This works for testing, but is obviously not representative of an actual production-ready rack. We should ensure that CRDB instances can be initialized / booted jointly, across multiple nodes.

**Comment by smklein** [comment]
As an FYI for whoever picks this up - maybe future me - CRDB is picky about the clocks of all nodes being in sync. This will require clock synchronization between nodes, likely via NTP or some equivalent.

**Comment by davepacheco** [comment]
Yeah, I recommend we use chrony for this.  When I was testing CockroachDB in late 2020, I found that the stock illumos ntpd was not even close to good enough to keep clocks in sync.  CockroachDB expects something like 250ms of drift.  After a few days or a few VM restarts in AWS, it was common for the clocks to drift further than this.  After setting up crony (which was pretty straightforward), the clocks were generally within 1ms (as measured by CockroachDB).

There are open questions about what we'd point any NTP server at.  RFD 34 remains open.

**Comment by smklein** [comment]
Blocked on https://github.com/oxidecomputer/omicron/issues/2219
