### ISSUE TITLE
Implement "Snapshot" API

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#735]
- [x] Add API stubs
- [ ] Add to Database
- [ ] Plumb through to Crucible
- [ ] Add support in simulated sled agent / crucible
- [ ] Add integration tests in Nexus

**Comment by smklein** [comment]
Working on stubs right now

**Comment by jmpesp** [comment]
All of the tasks for this issue should be complete now, am I ok to mark them done?

**Comment by smklein** [comment]
> All of the tasks for this issue should be complete now, am I ok to mark them done?

Sounds good; closing now.
