### ISSUE TITLE
Network Interfaces need authz checks

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#739]
See [this](https://github.com/oxidecomputer/omicron/pull/713#discussion_r822002838_) for the original context.

Currently, the `Nexus::instance_lookup_network_interface` method does authorization checks on the instance to which the interface is attached. This tracks adding authz checks to the network interface. For example, we should move these `Action::ListChildren` checks on the instance to `Action::Read` checks on the network interface itself.

**Comment by davepacheco** [comment]
@bnaecker I think this wound up getting fixed, right?

**Comment by bnaecker** [comment]
Ah yes, meant to close when #713 merged. Thanks.
