### ISSUE TITLE
Update plans

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#764]
Currently Nexus is not very smart at all about when it tells Sled Agent to apply updates.

https://github.com/oxidecomputer/omicron/blob/6f6aba6b5ca5c73bcba789a0e36cece89b93ffd5/nexus/src/nexus.rs#L2873-L2890

Nexus needs to know:
* Versions of software and firmware across the rack, so it can determine what needs updates
* Update constraints (e.g. "this is an OS ramdisk; the sled must be evacuated of workloads so we can reboot", but also "the customer wants to hold back this component to this version because of Reasons")

With this information, Nexus needs to create an _update plan_ that is a list of ordered steps for any running Nexus to execute. Nexus will periodically re-evaluate its plan to match the current state of the system and what new updates are available.

(From #717)

**Comment by davepacheco** [comment]
There are many individual work items implied here and I think they're covered by the [automated update project](https://github.com/orgs/oxidecomputer/projects/44) so I'm closing this.
