### ISSUE TITLE
Nexus datastore: combine `update_available_artifact_{upsert,hard_delete_outdated}`

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#766]
https://github.com/oxidecomputer/omicron/blob/6f6aba6b5ca5c73bcba789a0e36cece89b93ffd5/nexus/src/db/datastore.rs#L3194-L3228

These are two separate datastore methods, but are always called together. Combine these into one method and use a transaction to ensure the list of artifacts in the database remains consistent.

(From #717)

**Comment by david-crespo** [comment]
Working on this in #2866

**Comment by sunshowers** [comment]
I believe this is obviated by the new design with blueprints and #4690.
