### ISSUE TITLE
Rename `organizations` in paths to `orgs`?

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#796]
It's very long! We've discussed this in various places I can't find, but never got consensus. Once people started typing it all the time I think they started to agree it felt quite long. For me the motivation for making this change is that `/organizations` is long to appear in the console URLs. Right now I have it as `/orgs` in the console and it works fine, but ultimately it will be confusing for users to have it be different from the API. I don't really see a downside of making this in the API other than the ugly diff.

Changing just the paths would be a reasonable-sized PR. Changing it in variable names is bigger, not sure we want to get into that.

**Comment by davepacheco** [comment]
As a developer I prefer predictability of names over shortness (so I like that nothing's abbreviated because otherwise I wouldn't know what _was_ abbreviated -- `Proj`? `Inst`?).  I think I'm unusual in this regard though so I'm interested in what others prefer.

**Comment by david-crespo** [comment]
That's a good concern. I'd hope people would be used to it because of GitHub, where they abbreviate [`orgs`](https://docs.github.com/en/rest/reference/orgs) and [`repos`](https://docs.github.com/en/rest/reference/repos), but nothing else. That's probably why it feels natural to me. Interestingly, they do not abbreviate the names in prose, only in URLs. Repo is a bit different from org in that people say "repo" like 95% of the time IRL.

**Comment by andrewjstone** [comment]
FWIW, I think `orgs` and `repos` are very reasonable abbreviations, where as `proj` and `inst` are not. Using @david-crespo's example, I will often verbalize "org". There is also the term "org-chart". In short, "orgs" and "repos" are unambiguous and common enough that I don't think shortening them is problematic. I would be against shortening everything though unless it met this arbitrary guideline :)

**Comment by david-crespo** [comment]
This is irrelevant now that we are going to get rid of organizations entirely. Best solution!
