### ISSUE TITLE
Limit number of NICs an instance can have attached

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/omicron#810]
https://github.com/oxidecomputer/omicron/pull/771 makes the arbitrary decision that an instance can have a maximum of eight disks attached to an instance, but leaves as a TODO the question of what the maximum should be for NICs.

This issue tracks adding a similar limit for NICs.

**Comment by bnaecker** [comment]
Good idea! Is this during instance creation, or a limit to also be respected when creating a new NIC for an existing instance?

**Comment by rmustacc** [comment]
> Good idea! Is this during instance creation, or a limit to also be respected when creating a new NIC for an existing instance?

This is a permanent limit of 8 each for both disks and NICs for a given instance at this time. The reason for this is a bit of a result from the decisions in [RFD 135 Virtual Storage Interfaces](https://github.com/oxidecomputer/rfd/pull/188). As a part of that, we started with basically having a virtual machine that is leveraging PCI -- critically not PCIe, and the associated ACPI PCI hotplug mechanism. The latter works by taking a single PCI bus and creating one hotpluggable slot per device on that bus. The PCI device is afforded 5 bits in the general PCI scheme, giving us a total of 32 devices. rom there, it's 8 NICs, 8 volumes to start with. The remaining devices are getting used up by other things as well (e.g. USB, VGA, etc.) though more of those can be multi-function devices.

**Comment by bnaecker** [comment]
Closed by #816
