### ISSUE TITLE
docker-image build sometimes fails with 403 error

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#86]
The `docker-image` GitHub workflow sometimes fails with a 403 error.  @jessfraz mentioned that this appears to be flakiness on the GitHub side and that they're working on it and so we shouldn't move to something else right now.

Here's one example:
https://github.com/oxidecomputer/omicron/pull/81/checks?check_run_id=2568268766

```
...
#19 exporting to image
#19 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#19 exporting layers 1.7s done
#19 exporting manifest sha256:268c1a40093b019941fe12b6e222ced6d882f4dc3e89ea9e17e4a6d2bc154c90 done
#19 exporting config sha256:85dc4d0253b0bae7cf5d43ced4f0584936dfd5a35b2b476e1ebe316f744462a3 done
#19 pushing layers
#19 pushing layers 0.5s done
#19 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
error: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
```

This sometimes succeeds on rerun.

For some data: Dependabot opened 5 PRs today.  All 5 failed this check.  I reran all 5.  2 of them succeeded, while the other 3 failed.  So that was a failure rate of 80%.  I haven't noticed it be this bad on my own PRs, but I don't have real data.  I'm not sure if concurrency or the Dependabot user makes this more likely.

**Comment by smklein** [comment]
See: https://github.com/oxidecomputer/omicron/pull/2691 -- closing
