### ISSUE TITLE
[Github Actions] Build Flake

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#868]
Taking a look at [The Github actions run on main](https://github.com/oxidecomputer/omicron/actions?query=branch%3Amain), there appears to a [build flake](https://github.com/oxidecomputer/omicron/runs/5789991654?check_suite_focus=true#step:11:587) related to linking Nexus.

In the logs, this issues presents as the following:

```
Running `rustc --crate-name omicron_nexus ...
error: linking with `cc` failed: exit status: 1
...
  = note: collect2: error: ld returned 1 exit status
error: could not compile `omicron-nexus` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name omicron_nexus ...`
```

AFAICT, the first sign of this issue happening is roughly co-located with the following PRs:

- First appeared in https://github.com/oxidecomputer/omicron/actions/runs/2078057645 , in @jgallagher 's merge of https://github.com/oxidecomputer/omicron/pull/786
- This was preceded by a handful of changes by @davepacheco for the "new internal lookup API"

However, given the flaky nature of the build, it is difficult to determine a root cause quite yet.

@jgallagher , @davepacheco  - any chance this error looks familiar? Any known changes to linkage?

**Comment by jgallagher** [comment]
@bnaecker Where do you see that error? But certainly "link failed due to not enough disk space" sounds like a potential cause.

**Comment by bnaecker** [comment]
@jgallagher That's at the bottom of this page: https://github.com/oxidecomputer/omicron/actions/runs/2078057645, under the "Annotations" section, so _not_ the captured output from the run.

**Comment by davepacheco** [comment]
> @jgallagher , @davepacheco - any chance this error looks familiar? Any known changes to linkage?

I didn't see any such errors during my recent work on the lookup API.  I used to see these more often until I switched to a system with more memory and added a swap device.

**Comment by jgallagher** [comment]
Any objecting to adding an "output disk space" step to CI a la https://github.com/oxidecomputer/omicron/commit/12d3296e56217b350d9a721936d6d960fb97ceb7? Might narrow down if the flake looks space related.

**Comment by smklein** [comment]
> Any objecting to adding an "output disk space" step to CI a la [12d3296](https://github.com/oxidecomputer/omicron/commit/12d3296e56217b350d9a721936d6d960fb97ceb7)? Might narrow down if the flake looks space related.

I think that's a great idea, more visibility in the build would help.

**Comment by jgallagher** [comment]
Maybe a bit more of a smoking gun that this is disk space related:

https://github.com/oxidecomputer/omicron/actions/runs/2097859388 is a failure on `main`. The pre-build step that reports disk usage claims there's 32GiB free. We made it through building (including linking), and the job appears to have died while running tests. The annotations on the run itself include

```
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.289.2/_diag/Worker_20220405-174524-utc.log'
```

**Comment by jgallagher** [comment]
It looks like #880 fixed this:

1. We saw some evidence this was disk space related, and that PR increased the available space by > 50%.
2. Between [the first failure](https://github.com/oxidecomputer/omicron/actions/runs/2078057645) and the PR being merged, there were 14 failures and only 3 successes of the `Rust` workflow on `main`.
3. Since the merge, there have been 7 successes and only [1 failure](https://github.com/oxidecomputer/omicron/actions/runs/2102865534), which looks like an ephemeral external-service-related issue.

Based on that I'm going to close this, but please reopen if you disagree or want to keep an eye on it for longer.

**Comment by smklein** [comment]
Thanks @jgallagher for following through on this! Very much appreciated

**Comment by davepacheco** [comment]
That all sounds good -- and also it seems likely we're going to run into this again.  We probably don't need to do anything now but it maybe should be on our radar to think about moving away from GitHub Actions.

**Comment by davepacheco** [comment]
Thanks for digging in and fixing this, @jgallagher!

**Comment by jgallagher** [comment]
Sure thing! It's certainly possible we'll run into this again, but based on https://github.com/easimon/maximize-build-space there's a fair bit more room to grow beyond what #880 did; I just grabbed what looked like the biggest bang-for-the-buck without impacting build times too much. I don't know what the growth over time of "disk space used in CI" is, but if we bump into this again in N months, we might be able to squeeze another x*N months out by using more of its techniques (for `x` somewhere around 1).
